### ISSUE TITLE
⚙Tech Debt: Will this amazing library get support for Svelte 5?

### ISSUE THREAD

**Issue by willpinha** [melt-ui/melt-ui#1001]
Will the library receive it? I don't know if with the change from Svelte 4 to Svelte 5, the library will continue to work normally.

I am interested in creating a component library using Melt UI and Svelte 5, but I don't know if it's safe due to this version change

**Comment by TGlide** [comment]
It will! Check out https://github.com/melt-ui/runes-experiment
