### ISSUE TITLE
🌟Feature request: ``Select`` keyboard behavior

### ISSUE THREAD

**Issue by Lakelimbo** [melt-ui/melt-ui#101]
When using the [Select element](https://www.melt-ui.com/docs/builders/select), when focused on the trigger, the arrow keys behave almost like the Space key, opening the select menu, so then you can use the arrows to select the next or previous option.

In my opinion, the default behavior from HTML's ``<select>`` is a more natural approach when navigating with the keyboard, so when the focus is on the trigger, the arrow keys just go to the next and previous options (including the left and right keys as well, not just up and down).

**Describe alternatives you've considered**
When writing this, I was thinking about making a request to be able to customize any keyboard behavior directly, which would be awesome, but considering that this is a very new project, this would be a very low priority feature for now.

**Comment by huntabyte** [comment]
While I agree this may feel more natural for most - if you read this page [here](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/), which this component is designed around, it explains the accessibility benefits of the way it's currently implemented.

More specifically - this bit here:
> Navigating the list of options does not set the value of the input. This gives screen reader users, who need to navigate among the options to perceive them, the ability to explore options without losing the current value of the input. The value is set when users press Space, Enter, or Tab, or when focus moves out of the combobox. The current value is retained if the listbox is closed with Escape or if the user collapses the list by clicking the input.

Along with the keyboard section on that page as well.

Our primary focus right now is building out all the components on our roadmap with strict adherence to specific design patterns.

I'll defer to @TGlide on the possibly of that being a "configuration option" in the future.

**Comment by TGlide** [comment]
I'm torn on this. While we do by default want to have strict adherence to WAI-ARIA design patterns, we usually allow overriding them. e.g. the `closeOnEscape` option on Dialog.

I'll leave this issue open to think about it.

**Comment by huntabyte** [comment]
I think we should be able to close this now with the additional controls added in #234, thoughts @TGlide ?

**Comment by TGlide** [comment]
Agreed! @Lakelimbo you can now override what the `keydown` event does in the trigger 😄 

We could provide examples on how to implement it though 🤔 as it's not super duper simple

**Comment by TGlide** [comment]
Okay done! Example created 😄
