### ISSUE TITLE
[Tooltip]: content styles reset when open state changes given content is always mounted and forceVisible is true

### ISSUE THREAD

**Issue by anatolzak** [melt-ui/melt-ui#1010]
### Describe the bug

If you pass `forceVisible: true` and always keep the content mounted, whenever `$open` changes, the content styles reset (`top: auto; left: auto`) and quickly go back to the trigger's position.

https://github.com/melt-ui/melt-ui/assets/53095479/ce93277a-6ecd-4d95-9a9e-35bf5cfdec8c

### Reproduction

https://github.com/anatolzak/melt-ui-tooltip-content-floating-styles-overriding-bug
https://melt-ui-tooltip-content-floating-styles-overriding-bug.vercel.app/

### System Info

```bash
System:
    OS: macOS 14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 608.16 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.11.0 - /usr/local/bin/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 122.1.63.161
    Chrome: 120.0.6099.109
    Edge: 114.0.1823.82
    Safari: 17.3
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    svelte: ^4.2.9 => 4.2.9
```

### Severity

annoyance

**Comment by anatolzak** [comment]
@mcmxcdev what is the melt-ui version you are using?
you might be experiencing this issue https://github.com/melt-ui/melt-ui/issues/1005 that got fixed recently

**Comment by mcmxcdev** [comment]
> @mcmxcdev what is the melt-ui version you are using? you might be experiencing this issue #1005 that got fixed recently

I upgraded to latest just before making this issue comment. I think my issue is actually more related to the fact that the popover closes and then the tooltip loses its anchor point, so I might just need to disable closeOnOutsideClick for popover.

**Comment by anatolzak** [comment]
@mcmxcdev your issue is actually a different one that what this one was about.
I just created and reproduced your issue. https://github.com/melt-ui/melt-ui/issues/1036

**Comment by mcmxcdev** [comment]
> @mcmxcdev your issue is actually a different one that what this one was about. I just created and reproduced your issue. #1036

Thanks man, really appreciate it! Gonna follow the new issue you opened.
