### ISSUE TITLE
Reduce required nanoid version to 4.x

### ISSUE THREAD

**Issue by caschbre** [melt-ui/melt-ui#1022]
**Is your feature request related to a problem? Please describe.**
It looks like [this pull request](https://github.com/melt-ui/melt-ui/pull/851) upgraded the required version of nanoid to ^5. Nanoid v5 drops support for nodejs 16 and below. This ends up becoming a breaking change for those still on v16.

**Describe the solution you'd like**
I skimmed over how melt-ui uses nanoid... and it appears that dropping back down to nanoid 4.x should still work. So I would recommend dropping the required version back down to 4.x.

**Describe alternatives you've considered**
To work-around the issue, I've used pnpm to override the nanoid requirement back to 4.x... and that does work locally... however I'd prefer to not override versions unless absolute necessary.

**Comment by mcmxcdev** [comment]
I asked about declaring official node version support in https://github.com/melt-ui/melt-ui/issues/925 and there was no interest in doing so.

Personally, I would say upgrade your node version since v16 is not part of LTS any more, but I understand that consumer projects can have all kinds of specific constraints.

**Comment by caschbre** [comment]
Yeah, I would love to upgrade the node version... we're working on it but hasn't been the priority. :-/  My main reason for requesting the reduced nanoid version is to avoid the breaking change.

**Comment by TGlide** [comment]
Finally have the time to come back to this. 

Seeing as [Node 16 has already reached EOL](https://nodejs.org/en/blog/announcements/nodejs16-eol), I think it does not make sense to worry about supporting it further, I'm afraid.

I understand this may bring issues, but I genuinely do recommend you update your Node version ASAP, sicne you'll also be missing out on security updates.
