### ISSUE TITLE
Controlled opening of `Combobox` $menu requires an `$input` element unless `defaultOpen: true` is used

### ISSUE THREAD

**Issue by silenceofthewans** [melt-ui/melt-ui#1032]
### Describe the bug

#1020 fixed the `open.set(true)` controlled usage of combobox but in `v74.4` 🔥 users will still need to have an `$input` element outside `{#if $open}` otherwise `$menu` never renders. The only way to solve it currently is either keep using `$input` builder on a button instead of a click handler with `open.set(true)` which solves all the issues and nested shallow routing of dialog works perfectly or add a `defaultOpen: true` after which it works but is not ideal because that will open the nested dialog if you are syncing combobox's $open store with sheet instead of other way round. I'm not familiar with how they work under the hood but as a consumer of this builder I would love a bit more flexibility and decoupling of triggering and rendering of `$menu`. Maybe, this gets solved by #1024 but as a workaround, I'm back to using $input on a button which albeit semantically weird, works perfectly with minimal state maintenance when shallow routing and using sheets.

### Reproduction

https://stackblitz.com/edit/github-mvb7xe-kghd81?file=src%2Flib%2Fcomponents%2FCombobox.svelte

- Observe current behavior with `defaultOpen: false` and `open.set(true)` (no $menu renders)
- uncomment `defaultOpen: true` while keeping `open.set(true)` or use the `<button/>` with `$input` builder and $menu works fine

### System Info

```bash
wSL2
```

### Severity

annoyance

**Comment by huntabyte** [comment]
_At the moment_, this is the expected behavior until we determine how to proceed with exposing more control over Floating UI.

The positioning of the menu depends on the location of its anchor, which in the case of the combobox is the `input`. Without the input being in the DOM, Floating UI has no idea where to render your menu.

This experience and your workaround should be solved once #1024 is implemented, so will close this for the time being.

Thanks for raising this issue! It has now made me think about how we'll implement the button and the priority it will have over the input in terms of rendering!

**Comment by huntabyte** [comment]
You can also place the open combobox with the input inside of a popover!

**Comment by silenceofthewans** [comment]
I'm not super informed about which one is semantically correct between popover and dialog but I do need that overlay and portal since in my context I purposely implement only the missing draggable bottom sheet part and wanted to offload rest of it (portal,closeOnClickOutside,states etc) on melt. Also, I portal all my sheets/dialog to a single div with `display: grid` at the top most level and use CSS grid for all overlay positioning ([ref ](https://css-tricks.com/positioning-overlay-content-with-css-grid/)) so no relative and absolute which is why I usually do `positioning: null` on all of these. I could try it with popover too once #1025 is merged but I do wonder what would be the differentiating factor between all these when overlay is added apart from maybe no portal? Because both can be used for a contextual user action.

Don't know if this is even possible, but maybe one day we could mix and match these builders like lego blocks to make higher level builders just like Select and Combobox use a listbox as common construct underneath with other functionality sprinkled on top. This way we could have a single portal, overlay etc and then if we need a popover or dialog we combine some of these based on recommended accessible patterns.
