### ISSUE TITLE
Select menu is rendered behind some custom dialog components

### ISSUE THREAD

**Issue by jmkmay** [melt-ui/melt-ui#1034]
### Describe the bug

I noticed when evaluating melt via a standard select component that a barebones component (essentially copied the one from documentation) wasn't rendering. I was trying to implement a simple options/settings dialog with a select as one of the fields. Inspecting the element also showed no popover `div` or layout shift in the markup.

I was able to get the component to behave correctly by implementing it top level in `+page.svelte`.

Reproduction shows the issue very clearly.

### Reproduction

https://stackblitz.com/~/github.com/jmkmay/meltui-select-modal-bug

https://github.com/jmkmay/meltui-select-modal-bug

### System Info

```bash
System:
    OS: macOS 13.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 395.51 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 16.6
  npmPackages:
    @melt-ui/svelte: ^0.74.4 => 0.74.4
    @sveltejs/kit: ^2.0.0 => 2.5.2
    svelte: ^4.2.7 => 4.2.12
```

### Severity

blocking all usage of Melt UI

**Comment by huntabyte** [comment]
`z-100` isn't a valid class. Updating the menu to `z-[100]` addresses your issue.
