### ISSUE TITLE
Tooltip Loses Anchor and Stays Open When Clicked inside Popover

### ISSUE THREAD

**Issue by anatolzak** [melt-ui/melt-ui#1036]
### Describe the bug

If you mount a tooltip inside a popover, and then click on the tooltip content, the popover gets unmounts and the tooltip content jumps to the top left of the page (because of losing its anchor).

https://github.com/melt-ui/melt-ui/assets/53095479/6f464c03-c62d-4d40-88d6-e65ec61ddfd7

The reason this happens is because when the popover is open, we are listening for outside clicks to close the popover. However if you have a tooltip mounted inside a popover, and you click inside the tooltip content, you would expect nothing to happen.

I tried adding a listener for `pointerup` on the tooltip content and then calling `e.stopPropagation()` to prevent the popover `pointerup` from running. 

This didn't work since the popover listens for `pointerup` on the document with `capture: true`.

And from what I understand, there is no way to have the tooltip content add another `pointerup` listener that will be able to run before the popover one and be able to stop propagation since we are using `capture: true`.

I also tried adding `sleep(0)` before running the `pointerup` event of the popover and then calling `e.preventDefault` in the event added by the tooltip content, however this breaks some behavior of being able to select text in the tooltip content.

### Reproduction

https://github.com/anatolzak/melt-ui-popover-tooltip-interaction-bug
https://melt-ui-popover-tooltip-interaction-bug.vercel.app/

### System Info

```bash
System:
    OS: macOS 14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 374.56 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.11.0 - /usr/local/bin/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 122.1.63.161
    Chrome: 120.0.6099.109
    Edge: 114.0.1823.82
    Safari: 17.3
  npmPackages:
    @melt-ui/svelte: ^0.74.4 => 0.74.4 
    @sveltejs/kit: ^2.0.0 => 2.5.2 
    svelte: ^4.2.7 => 4.2.12
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Those should be ignored since they are both within a portal.

**Comment by huntabyte** [comment]
I'll take a look to see for certain!

**Comment by anatolzak** [comment]
@huntabyte I assumed you were busy with more important things :) so I went ahead and implemented your suggested fix in the following PR https://github.com/melt-ui/melt-ui/pull/1064
