### ISSUE TITLE
Data State Inconsistency

### ISSUE THREAD

**Issue by anatolzak** [melt-ui/melt-ui#1041]
### Describe the bug

There is currently an inconsistency in how we calculate the `data-state` attribute.

With Dialog Content and Overlay, Tooltip Content:
```typescript
'data-state': $open ? 'open' : 'closed'
```

With the rest of the components (Link Preview Content, Menu Content, Popover Content, etc.):
```typescript
'data-state': $isVisible ? 'open' : 'closed'
```

I believe that the `data-state` should be based on `$open`, because if we use `forceVisible: true` and always keep the content mounted, `data-state` will always be `open`.

The only place where this decision between `$open` and `$isVisible` matters, is when the user uses `forceVisible: true`, in which case if they unmount the component when `$open` is `false` and use a svelte transition, `data-state` will actually stay `open` because of how svelte internally freezes the component to transition it out. But if the user always leaves it as mounted and just changes the content's visibility, `data-state` should be `closed`, which is not currently the case with the codebase.

Now, if we agree that we should change the `data-state` based on `$open`, we need to make sure that we don't override styles set by floating-ui in certain components.

```typescript
'data-state': $open ? 'open' : 'closed',
style: styleToString({
    display: $isVisible ? undefined : 'none',
}),
```

The above code would "rerender" every time the `$open` state changes, and if the user never unmounts the content, the styles will get reset to an empty string, thereby removing the styles set by floating-ui, which causes the component to jump. This was already fixed in the case of the tooltip content here https://github.com/melt-ui/melt-ui/issues/1010

The solution was to use the below code
```typescript
'data-state': $open ? 'open' : 'closed',
style: $isVisible ? undefined : styleToString({ display: 'none' }),
```
... and to remove properties with undefined values returned from the tooltip content, because if we set style to undefined, svelte will also reset the styles set by floating-ui. So we needed to remove the style property altogether.

So since this will be a problem in all builders, we should remove properties with undefined values in the `makeElement` function.

### Reproduction

-

### System Info

```bash
-
```

### Severity

annoyance

**Comment by TGlide** [comment]
I agree it should be based on open state. But display should be based on forceVisible too, meaning it should be based on isVisible

**Comment by anatolzak** [comment]
@TGlide 100%! I accidentally wrote that display should be based on `$open`. In my PR for the tooltip and in my PR that I just created, display is based on `$isVisible`
