### ISSUE TITLE
🌟Feature request: Default scrollbar when js is disabled

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#1065]
**Is your feature request related to a problem? Please describe.**
It would be nice that the scroll-area component renders the default scrollbar when js is disabled

**Describe the solution you'd like**
When js is disabled, the scroll-area is an overflowed container that scrolls automatically. When js is enabled, scroll-area logic takes place

**Describe alternatives you've considered**
Progresive enhancement in userland (e.g. check if js is disabled with `<noscript>` tag and apply css styles to hide the element with scroll-area action)

**Additional context**
n/a

**Comment by huntabyte** [comment]
The scroll functionality still works without JS, just the scrollbar doesn't display. The problem with providing that "fallback" at the library level is that it will cause a layout shift and a flash of a scrollbar in the case of "hover" or "scroll" while the page is loading which looks hideous as a default.

I think this can be accomplished in user-land on an as-desired basis.
