### ISSUE TITLE
Docs: "Modify Writable States" section does not need the `writable` function.

### ISSUE THREAD

**Issue by juangiordana** [melt-ui/melt-ui#1097]
There's an unused `import` in the docs that may lead to confusion.

**"Modify Writable States"** section does not need the `writtable` function.

This may cause confusion with the **"Bring Your Own Store"** section that does rely on `writable`.

https://github.com/melt-ui/melt-ui/blob/fc29cba812b01de27da55ccd0e7957494285aec4/src/docs/content/controlled.md?plain=1#L59-L71

**Comment by yud0uhu** [comment]
I would like to work on this issue.
