### ISSUE TITLE
Docs: replace right/left with logical properties for RTL-supported examples

### ISSUE THREAD

**Issue by mustafa0x** [melt-ui/melt-ui#1098]
See [`/class=.*(right|left)/`](https://github.com/search?q=repo%3Amelt-ui%2Fmelt-ui+%2Fclass%3D.*%28right%7Cleft%29%2F&type=code) matches in this repo. Changing this will make it easier to use the doc examples in rtl projects. Also, it'll make it easier to make an rtl version of the docs. Simply using logical properties solves most problems.

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values/Floating_and_positioning#mapped_properties_and_values
- https://tailwindcss.com/docs/top-right-bottom-left#using-logical-properties

Eg for the first result (of the search linked above), replacing `left-1/2` with `start-1/2` is all that's needed.

**Comment by huntabyte** [comment]
Community contributions are desired for this one, specifically someone who is confident in RTL & LTR to verify everything looks golden in both!

**Comment by huntabyte** [comment]
Closing as we don't have time to tackle this ourselves at the moment. If someone submits a PR we can reopen this.
