### ISSUE TITLE
Select menu always hidden when used within WebComponent Shadow DOM

### ISSUE THREAD

**Issue by JonasGruenwald** [melt-ui/melt-ui#1111]
### Describe the bug

When using the Select builder from within a WebComponent, the `menu` entity has `hidden=true` and `display:none` set on the associated element.

An identical component build with the same parameters works fine outside the WebComponent – I suspect it's because of something related to Shadow DOM isolation within the WebComponent.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-utg59t?file=src%2Fmain.ts

### System Info

```bash
System:
    OS: macOS 14.1.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 45.21 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.4 - /usr/local/bin/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.1
  npmPackages:
    @melt-ui/svelte: ^0.74.4 => 0.74.4 
    svelte: =4.2.12 => 4.2.12
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Duplicate #1083
