### ISSUE TITLE
Webkit Browsers: Dialog overlay doesn't prevent bubbling on mobile

### ISSUE THREAD

**Issue by hugotox** [melt-ui/melt-ui#1115]
### Describe the bug

Initially discovered in [shadcn Dialog](https://github.com/huntabyte/shadcn-svelte/issues/548), this is still happening. I don't have a direct dependency of melt-ui, but just `"bits-ui": "^0.20.0"` 

> When opening a dialog on mobile devices, the overlay is not preventing interactions with elements behind it. This behavior doesn't happen on desktop.

### Reproduction

Just open a dialog on mobile, and notice how the elements behind the overlay are interactive.
<img width="716" alt="291118255-988171c0-b307-4dae-9b5a-5e02d747d569" src="https://github.com/melt-ui/melt-ui/assets/1758062/d7c3e4c4-f72d-4ee8-959f-548bbe9f7879">

https://stackblitz.com/edit/github-hrerew?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 96.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/Library/pnpm/node
    npm: 10.2.3 - ~/Library/pnpm/npm
    pnpm: 8.14.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.59
    Edge: 122.0.2365.92
    Safari: 15.0
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Can this be reproduced using an actual mobile device and not the mobile preview in the browser?

**Comment by hugotox** [comment]
Yes, it happens on webkit browsers: safari, duckduckgo. Doesn't happen on chrome

**Comment by huntabyte** [comment]
Of course, it's the webkit browsers 🤦‍♂️

We'll try to determine what the cause of this is and how we can get around it.

**Comment by anatolzak** [comment]
@huntabyte I was able to fix this issue in this PR https://github.com/melt-ui/melt-ui/issues/1115
