### ISSUE TITLE
Website stop response when change slider min, max

### ISSUE THREAD

**Issue by shana0440** [melt-ui/melt-ui#1123]
### Describe the bug

Website no response when change slider min, max and value constantly.

https://github.com/melt-ui/melt-ui/assets/6259797/3b261b81-8ce2-42d1-9c37-5412c5339be1

When pressing `set min & max & value` button multiple times, the CPU go high and website stop response without any error message.

### Reproduction

https://stackblitz.com/edit/github-9ik5uh?file=src%2Flib%2Fcomponents%2FSlider.svelte

The reproduce code
https://github.com/shana0440/melt-ui/commit/739c04d0d5704b21d7c828d8720c1ccca6923c98

### System Info

```bash
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 147.80 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.7.1 - ~/.asdf/installs/nodejs/21.7.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.5 - /opt/homebrew/bin/pnpm
    bun: 1.0.33 - ~/.asdf/shims/bun
  Browsers:
    Chrome: 123.0.6312.59
    Safari: 16.5
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0
    svelte: ^4.2.9 => 4.2.9
```

### Severity

annoyance

**Comment by shana0440** [comment]
After further research, the problem is caused by invalid max and min values. If min is larger than max, fixValue will keep changing, causing the website to hang.
https://github.com/melt-ui/melt-ui/blob/61a8264a5431b2ce115bf54b83a2b6c491cf418a/src/lib/builders/slider/create.ts#L529-L544

It will be great if the slider can swap $min and $max when $min is larger than $max. I'm not sure if this should be considered a bug or just incorrect usage, feel free to close the issue if this is not considered a bug.

**Comment by bennymi** [comment]
I'm wondering if when updating the min value we could just check if it's actually smaller than the max and if not, just make the max the min and the min the max, and do the same thing when updating the max value. That way they are always correctly defining an increasing range.

**Comment by shana0440** [comment]
If add an effect to fix the min and max like this.
```
effect([min, max], function fixMinMax([$min, $max]) {
  if ($min >= $max) {
    let temp = $max;
    max.set($min);
    min.set(temp);
  }
});
```
In this case, if we change min and max from [0, 100] to [200, 400], and change $min first, the min and max will end up as [100, 400].
