### ISSUE TITLE
⚙Tech Debt: Align `Select` to WAI-ARIA Select-Only Combobox

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#114]
The keyboard behavior for the `Select` component only partially aligns with the [WAI-ARIA Select-Only Combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/).

I'd like to align it perfectly with that example!

**Comment by kyuuaria** [comment]
The current implementation of the typeahead logic only selects the first item that begins with the character and doesn't loop through it like in the example.

**Comment by huntabyte** [comment]
Good catch! @kyuuaria - I'll also look into that as well 👍
