### ISSUE TITLE
Popover not working correctly

### ISSUE THREAD

**Issue by angelvega93** [melt-ui/melt-ui#1177]
### Describe the bug

Since version [v0.76.0](https://github.com/melt-ui/melt-ui/releases/tag/v0.76.0) popover is not working correctly, in the latest version [v0.76.3](https://github.com/melt-ui/melt-ui/releases/tag/v0.76.3) there are some fixes, but there is a new error/bug/feature?, you can open multiple popovers if you press a trigger that opens another popover.

Example:
![image](https://github.com/melt-ui/melt-ui/assets/9835055/0d4a6f5f-23f3-47cf-a390-ccbc608a4d05)

### Reproduction

Click other popover trigger.

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 48.81 GB / 63.92 GB
  Binaries:
    Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.6 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @melt-ui/svelte: ^0.76.3 => 0.76.3
    @sveltejs/kit: ^2.5.4 => 2.5.4
    svelte: ^4.2.12 => 4.2.12
```

### Severity

annoyance

**Comment by Eliophot** [comment]
Hello, yep same problem whith 0.77.0
![image](https://github.com/melt-ui/melt-ui/assets/81296123/bf5f1fb9-36da-4efa-8929-fb177d8b75b5)
Thanks 🙏
