### ISSUE TITLE
`deleteTrigger` on `TagsInput` can not be tabbed to through keyboard usage

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#1189]
### Describe the bug

When playing around with https://melt-ui.com/docs/builders/tags-input, its noticeable that the tags can be selected when hitting Backspace and the tag can be deleted by clicking the x button (`deleteTrigger`). Unfortunately the `deleteTrigger` has tabindex=-1 so it can never be focused by a keyboard user to delete.

I would expect tab and shift+tab to go over both the tag and the x button as tabbable elements, but Backspace to just go over the tags, not the x buttons.

### Reproduction

-

### System Info

```bash
-
```

### Severity

annoyance

**Comment by TGlide** [comment]
You can delete the tag by clicking backspace again, so the button doesn't need to necessarily be tabbable. In fact I'd say it's less intuitive for it to be so, specially as the tabs also aren't. Will close this one!

**Comment by mcmxcdev** [comment]
> You can delete the tag by clicking backspace again, so the button doesn't need to necessarily be tabbable. In fact I'd say it's less intuitive for it to be so, specially as the tabs also aren't. Will close this one!

I agree with you there, I outlined a different expected behavior in the issue description:
"I would expect tab and shift+tab to go over both the tag and the x button as tabbable elements, but Backspace to just go over the tags, not the x buttons."

But its a minor annoyance, so I am fine if the status quo is kept too.
