### ISSUE TITLE
Context Sub Menu Does not function after first instantiation

### ISSUE THREAD

**Issue by davidwoolf** [melt-ui/melt-ui#1205]
### Describe the bug

When using sub menus in a context, the first initialization of the context menu allows you to hover over the sub trigger and open the menu. However, closing the context menu and reopening it breaks the sub menu functionality.

Additionally, arrow navigation is broken for the same flow.

This was tested in both Webkit and Chromium.

### Reproduction

Check your own demo: https://melt-ui.com/docs/builders/context-menu

### Logs

No logs are outputted for this issue.

### System Info

```bash
System:
    OS: macOS 14.4.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 84.05 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 9.0.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.209
    Safari: 17.4.1
```

### Severity

blocking all usage of Melt UI

**Comment by davidwoolf** [comment]
Note that this is a huge bug blocking usage of the context menu, which is an important feature for something I am working on.

**Comment by TGlide** [comment]
Thanks for raising the issue! For a workaround, use `forceVisible: true`, and couple them with `#if` blocks.

**Comment by davidwoolf** [comment]
@TGlide thanks for the tip! I tried that and unfortunately it seems to break it completely. The overall context menu works fine with that pattern, but I can't open the sub menu at all anymore. 

I realize I may be doing this wrong, so let me provide some code:

```
const {
    states: { open },
    elements: { subMenu, subTrigger },
  } = createSubmenu({ forceVisible: true });

<div {...$subTrigger} use:subTrigger>
  Trigger
</div>

{#if $open}
  <div {...$subMenu} use:subMenu>
     <slot />
  </div>
{/if}
```

**Comment by TGlide** [comment]
Try only setting context menu with forceVisbible

**Comment by davidwoolf** [comment]
Ok I figured it out. Yes agreed to applying `forceVisbible` on the root context menu. Additionally, `createSubmenu` returns `subOpen` not `open`:

```
const {
    states: { subOpen },
    elements: { subMenu, subTrigger },
  } = createSubmenu(args);
```

**Comment by pierre-H** [comment]
With Svelte 5, I have the same problem, event with `forceVisible: true,` and the `{#if $subOpen}` block.
