### ISSUE TITLE
🐛Bug: Focus on iOS on melt-ui.com

### ISSUE THREAD

**Issue by multivac61** [melt-ui/melt-ui#123]
**Describe the bug**

Here are some videos where the below bugs are obvious.

https://github.com/melt-ui/melt-ui/assets/4436129/cf792dcf-3223-4c73-8f3c-d1648f49844a

https://github.com/melt-ui/melt-ui/assets/4436129/a547992e-c692-48fb-a3da-e2fc1da51f58

**To Reproduce**
1. Go to melt-ui.com
2. Click on documentation and then hamburger menu
3. Scroll down to list of
4. a) Unable to see last item on the list (Tooltip is invisible). b) Hover acts up when I am using my finger to scroll in the list (see video)

1. Go to melt-ui.com
2. Click on Melt UI logo
3. Looks like focus on the background page (orange pixels on screen)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: Newest
 - Browser stock browser
 - Version: Newest

**Comment by huntabyte** [comment]
Thanks for opening this up and for the detailed reproduction! I also see the issues, will work on getting this fixed asap!
