### ISSUE TITLE
Feature [Tooltip]: Controlled open state

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#128]
**Describe the bug**
This is not a bug but more an enhancement. Sometimes there is a need to keep a tooltip open regardless of mouseout.

In my scenario I am using it for erronous input. I don't want it to close until the input is valid again.

**To Reproduce**
Create a tooltip and mouse over and out. 

**Expected behavior**
A new flag to allow it to remain open regardless of mouseout.

**Comment by huntabyte** [comment]
Got it! So you basically want an option to control the state of the tooltip!

**Comment by geerew** [comment]
Yeah. There is already a control for mouse click. It would be nice to also have a mouse out one too. That way it can be controlled programmatically

**Comment by TGlide** [comment]
Closed as duplicate of #182
