### ISSUE TITLE
✨ Builder: Table of Contents

### ISSUE THREAD

**Issue by bennymi** [melt-ui/melt-ui#129]
Would there be an interest in a ToC component? I created one for my library ([example](https://ato-ui.vercel.app/docs/components/toc-headless)) and since I'm planning to move all dependencies to Melt UI it would make sense to transfer the ToC here albeit with some changes to match the other builders implementations. I also feel like my component is a bit overly complicated so we could probably strip away some of the options.

Let me know, if this is something you would like to add to Melt UI and I could set up a PR for it and we can discuss what the options for it should look like.

**Comment by TGlide** [comment]
Sorry for the late reply. This seems interesting, so basically it finds all headings in an element and creates a TOC? That's quite cool, I think that'd be pretty useful to be honest! Would be important to specify the level of the header too.

**Comment by bennymi** [comment]
Closing this issue since ToC builder has been created already.
