### ISSUE TITLE
🐛Bug: Selected tag stays selected after bluring input

### ISSUE THREAD

**Issue by pawelblaszczyk5** [melt-ui/melt-ui#139]
**Describe the bug**
When I select a tag with arrow keys and then navigate away of it, via either keyboard or mouse, e.g. focus another element, the tag stays selected.

**To Reproduce**
1. Go to https://www.melt-ui.com/docs/builders/tags-input
2. Click on Tag Input
3. Select some tag with arrow keys
4. Use tab to focus next element
5. See the tag still being selected

**Expected behavior**
I'd expect the tag to be unselected after Tags Input loses focus, that's also the behavior that I observed in e.g. Zag.js

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.0 Beta
 - Browser: Safari 
 - Version 17.0

**Additional context**
It seems to be unrelated to the specific system configuration, I've tested it with other devices and browsers and the issue persists

**Comment by geerew** [comment]
PR #124 is in the works. It fixes and many other issues as well as adds some features

**Comment by pawelblaszczyk5** [comment]
> PR #124 is in the works. It fixes and many other issues as well as adds some features
> 
> the newer version works more like the zag implementation :)

Ah, I've read the "documentation" part in PR title and skipped the rest, sorry 😄 I'm closing the issue then, thanks a lot! Awesome work 👏🏽
