### ISSUE TITLE
⚙Tech Debt: Mouse Events -> Pointer Events

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#144]
Right now we're using a mix of mouse and pointer events.

I'm curious if it would make sense to just strictly use pointer events and for those that we *only* want to apply to mouse users, we can use something similar to what I'm using in the menu components, which is an `isMouse()` function that checks the pointer type or `isTouch()` in the hovercard to handle those cases.

I feel like a majority of components can support both, so pointer feels like the better "standard"

The reason I'm evening bringing this up is that as we start to expose more events to the users, like `onMouseOver`, `onMouseLeave`, etc. so that they can override them, and fully customize the components, it'd be nice to have a predictable API. Rather than using `onMouseOver` in one component, and `onPointerEnter` in another, we can just use one or the other consistently across the components.

Definitely interested in hearing thoughts on this, I know it may sound a bit nitpicky, just been doing a lot of thinking on standardizing the APIs and providing the best DX possible :)

**Comment by TGlide** [comment]
mouseEvents also works on touch events, supposedly: https://stackoverflow.com/questions/69899775/pointerdown-vs-onclick-what-is-the-difference

**Comment by TGlide** [comment]
This issue also relates to #170, as we were using pointerDown instead of click in multiple instances

**Comment by TGlide** [comment]
Sometimes we need to use mouseEvents, it seems. Solved an issue with tooltip with it.

I think this is something that depends on each scenario. Closing as I think we shouldn't worry too much about this on a global scope!
