### ISSUE TITLE
📁Docs: support description column

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#145]
It would be nice if the api reference could support a description column to give a bit more context to some of the more ‘complicated’ args

Most args make sense from the name but some may require a little bit more explaination. 

For example, in tags-input there is an add/remove. It would be nice to be able to explain these functions are called before adding/removing the tag from the $tags store. and for add(), it can be used to validate the input, do backend (db, api, etc) work and modify the Id/value to be added to the $tags store

Would this be something worth adding?

**Comment by huntabyte** [comment]
Hi @geerew! Glad you opened this, I was just chatting with Thomas about this exact thing this morning!

I'm working on a few concepts today and will link the PR to this issue once ready!
