### ISSUE TITLE
🐛Bug: Typeahead with nested menus is searching in parent menu

### ISSUE THREAD

**Issue by pawelblaszczyk5** [melt-ui/melt-ui#152]
**Describe the bug**
It applies to components such as "dropdown menu", "menubar", "context menu" (I think it's issue shared across all components with nested menus, I'm not sure whether I've found them all in the docs though 😄). When you're navigating via keyboard and using typeahead to navigate to an option in a nested menu it doesn't work - the typeahead is searching in parent menu and it'll focus option in a parent menu if it matches. 

**To Reproduce**
1. Go to e.g. https://www.melt-ui.com/docs/builders/dropdown-menu
2. Open menu with a keyboard
3. Open nested submenu "Profiles"
4. Write "tho" on your keyboard 
5. "Thomas G. Lopes" isn't being focused 
6. Write "Abo" on your keyboard
7. Option "About Melt UI" from parent menu is matched

**Expected behavior**
If I'm focus in nested submenu, the typeahead search should match the nested options

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.0 Beta
 - Browser: Safari
 - Version: 17.0

**Additional context**
I've tested also in other browser/system combinations and the issue persist, it doesn't seem to be connected to the specific environment.

**Comment by huntabyte** [comment]
Good catch, that definitely wasn't the case when they were first released so it must be something with the shared logic or the renames we recently did. Will look into this!
