### ISSUE TITLE
🌟Feature request: Combobox with search input within listbox

### ISSUE THREAD

**Issue by wysher** [melt-ui/melt-ui#159]
**Describe the solution you'd like**
New Combobox looks awesome. Great work guys!

I wonder if you consider to have Combobox with search input within opened listbox. Like Select with Autocomplete input inside. Like this: https://ui.shadcn.com/docs/components/combobox
One benefit of this behaviour is that user may see currently selected item, as well as "next" search results. It provides great UX for long lists.

**Additional context**
I like example with Country Autocomplete. Let's say user selected "Spain", but opens listbox again and want to pick another Country, like "Portugal".

In current Combobox appearance, when user type "Po" to filter list items, currently selected "Spain" is lost. And when user hit ESC, "Po" is still typed in combobox input.

Now lets have Trigger (button?) on which user at all time sees what is selected, and search input inside listbox. When user hits ESC "Spain" is still shown, and when listbox is open again there's input with "Po" and filtered items list.

**Comment by TGlide** [comment]
This does seem like a pretty cool use-case tbh. Will look into it!

**Comment by brandonp-ais** [comment]
I would in addition request 'multi' support.

We have a custom-made multi-select/combobox with this. Would love to do it the melt-ui way :)

![image](https://github.com/melt-ui/melt-ui/assets/112661861/d78ac601-202d-49a2-a796-76a5efa86099)

**Comment by JVariance** [comment]
> I would in addition request 'multi' support.
> 
> We have a custom-made multi-select/combobox with this. Would love to do it the melt-ui way :)
> 
> ![image](https://github.com/melt-ui/melt-ui/assets/112661861/d78ac601-202d-49a2-a796-76a5efa86099)
> 

Yes, please! For now I use svelte-select, but I would love to switch to a melt solution, too 👌🏼

**Comment by TGlide** [comment]
> I would in addition request 'multi' support.
> 
> We have a custom-made multi-select/combobox with this. Would love to do it the melt-ui way :)
> 
> ![image](https://user-images.githubusercontent.com/112661861/253122096-d78ac601-202d-49a2-a796-76a5efa86099.png)

Created a separate issue for it #344 😉

**Comment by TGlide** [comment]
After reviewing the [APG pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) again, I'd say this would not be representative of a Combobox. A Combobox is an input which has an **associated** popover, which I interpret as being something separate. All APG examples also point to that being the case.

What we could have here is rather a Popover with an input and a listbox inside. This could be an example we could show in docs, and I do think we could have a `createListbox` builder. But it'd be something separate from the combobox, due to accessibility concerns.

**Comment by wysher** [comment]
@TGlide you're totally right, it's not a combobox, but search input within popover.

Take a look at cmdk package: https://cmdk.paco.me/ - it's Command component, which shadcn/ui render inside popover.

**Comment by TGlide** [comment]
> @TGlide you're totally right, it's not a combobox, but search input within popover.
> 
> Take a look at cmdk package: [cmdk.paco.me](https://cmdk.paco.me/) - it's Command component, which shadcn/ui render inside popover.

I'm creating a command center builder actually! It'll be quite different, maybe a bit more opinionated... I'm not sure yet to be honest. Or maybe I'll create a more generic builder, and then create a separate command center component in another package 😄
