### ISSUE TITLE
📂Documentation: Examples for managing state

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#165]
I know at least one other individual as well as myself have run into this "gotcha" and @TGlide and I want to open it up to the community for discussion. I'm just jotting some thoughts down here so we don't forget to address this.

If you're using components within a `+layout.svelte` or a dynamic `+page.svelte` file (think routes/[slug]/+page.svelte), the state of the components/stores are persisted through navigation changes. This is certainly useful for certain use cases, think a theme selector (you wouldn't want it to change on each navigation), or something like that. But it can also be troublesome/confusing for other use cases when it's not what you want.

Whether it's something we can/should handle internally or having a documented "best practice" for resetting that state or disabling preservation on navigation is going to prevent a lot of issues that will inevitably arise from this!

**Comment by TGlide** [comment]
TBH the same would be happening if you had a component. I think it's up to the developer to deal with issues with persistent state. 

We should showcase some examples to deal with changing states though! E.g. let's say you have tabs with keys `frameworks` and `developers`, but then the page changes, and now the tab keys are `fruits` and `vegetables`. The value should be changed accordingly, maybe do a `beforeNavigate(() => {setTabValue('fruits')})`.
