### ISSUE TITLE
🐛Bug: It's possible to interact with components on right click

### ISSUE THREAD

**Issue by pawelblaszczyk5** [melt-ui/melt-ui#170]
**Describe the bug**
A few components act on right click the exact same way as it'd be clicked with a left click.

- Tabs - these can be switched via right clicking tabs
- Dropdown Menu, Select - it's opened on right click on trigger
- Combobox - it's opened on right click on trigger and the items are being selected with right-click
- Slider - the value is changed on right click and then the slider gets buggy - it acts like I was holding if with left click and dragging
- Radio Group - items are being checked

**To Reproduce**
1. Go to the docs of the specific builder
2. Try to interact using right mouse button instead of left one
3. See error

**Expected behavior**
The interactions shouldn't happen while using right mouse button

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS 14.0 Beta
 - Browser Safari
 - Version 17.0

**Additional context**
It seems to occur on other browsers as well (Chrome/Firefox)

**Comment by huntabyte** [comment]
Good catch, that should definitely not be the case!

**Comment by TGlide** [comment]
On Tabs it happens because it triggers focus, and we have `activateOnFocus` set to true. I wonder if we *should* disable focus happening on right-click, even though it's a browser default?

**Comment by TGlide** [comment]
Closed since the others were fixed. But open for discussion on Tabs and RadioGroup behaviour!

**Comment by pawelblaszczyk5** [comment]
Thanks, I'll investigate how other libraries handle this and/or patterns recommend solving it and start some thread on Discord about it
