### ISSUE TITLE
🐛Bug: Alert component icon overlapping with title

### ISSUE THREAD

**Issue by sina-salahshour** [melt-ui/melt-ui#172]
**Describe the bug**

**To Reproduce**
1. Go to 'https://ui.shadcn.com/docs/components/alert'
3. Heads up alert (or any other alert)

**Expected behavior**
icon should be in a separate line from the title, or at the same line with some space between them.

**Screenshots**
![image](https://github.com/melt-ui/melt-ui/assets/59766409/ed19efdc-046d-4bc5-b870-a76949f98ef7)

 - OS: Arch linux
 - Browser firefox
 - Version 114.0.2

**Comment by TGlide** [comment]
ui.shadcn.com doesn't use Melt UI though 🤔
