### ISSUE TITLE
🌟Feature request: Prevent Popover close based on condition (e.g. tainted input fields)

### ISSUE THREAD

**Issue by didier** [melt-ui/melt-ui#176]
**Is your feature request related to a problem? Please describe.**
I'm working on a builder-like application, and some of my profile features are edited using the popovers with some inputs inside. These popovers either need to be saved or canceled. 

**Describe the solution you'd like**
Ideally, I would like to prevent close based on some condition, like unsaved changes or tainted input fields. 

**Describe alternatives you've considered**
I've tried to reopen the popop using the `$open` store and a click outside handler, but as you can expect that does not lead to the desired outcome.

**Additional context**
n.a.

**Comment by TGlide** [comment]
Related: #70

**Comment by geerew** [comment]
It is also somewhat related to #80 whereby I would like to be able to keep the parent popover open while a child popover is open..
