### ISSUE TITLE
🌟Feature request: Expose helper function for handling state programmatically

### ISSUE THREAD

**Issue by winston0410** [melt-ui/melt-ui#179]
**Is your feature request related to a problem? Please describe.**
Currently there is no helper function being exported for updating state. For example, I want to close the popover afterNavigation:

```svelte
<script lang="ts">
	const { trigger, content, open, arrow, close } = createPopover();

	afterNavigate((x) => {
          // trigger a function to make open = false, and aria-open = false here
	});
</script>

<button type="button" {...$trigger} use:trigger aria-label="Show cart item">
	Cart
</button>

{#if $open}
	<div {...$content} use:content>
          <p>Hi</p>
	</div>
{/if}
```

**Describe the solution you'd like**
Every builder expose helper functions that can programatically update state, for example:

```svelte
<script lang="ts">
	const { trigger, content, open, arrow, close, helper } = createPopover();

	afterNavigate((x) => {
           helper.close()
	});
</script>
```

**Describe alternatives you've considered**
I don't think there is any alternative for this

**Additional context**

**Comment by TGlide** [comment]
Popover exports an open store that you can control.
![firefox_8uCjeuLcYE](https://github.com/melt-ui/melt-ui/assets/26071571/cefbe9e6-4061-4c2f-a64c-45bc6f75b558)


So a solution would be:
```html
<script lang="ts">
	const { trigger, content, open, arrow, close} = createPopover();

	afterNavigate(() => {
        open.set(false) // or $open = false
	});
</script>
```
