### ISSUE TITLE
🐛Bug: Accordion Item store inside the Svelte's each block

### ISSUE THREAD

**Issue by dcheglakov** [melt-ui/melt-ui#19]
**Describe the bug**
When I try to create the accordion from an array using Svelte's each block, I get an error for the item store:
```
Stores must be declared at the top level of the component
(this may change in a future version of Svelte) - svelte(contextual-store)
```
I managed to get around this problem like this:
```js
<script lang="ts">
	import { createAccordion } from '@melt-ui/svelte';
	import { get } from 'svelte/store';

	const { content, item, trigger, isSelected, root } = createAccordion();
        ...
	const itemStore = get(item);
</script>
```
And then use it like this
```js
<div class="w-full shadow-lg" {...root}>
	{#each accordion as item}
		<div {...itemStore(item.id)} class="accordion-item">
			...
		</div>
	{/each}
</div>
```

**To Reproduce**
1. Checkout this playground [repo](https://github.com/dcheglakov/melt-ui-playground) or use [Stackblitz example](https://stackblitz.com/edit/stackblitz-starters-zpwu19?file=src%2Froutes%2Fdemos%2Faccordion%2F%2Bpage.svelte)
2. Install dependencies with `pnpm`
3. Go to file src/routes/demos/accordion/+page.svelte
4. Line 31 see error

**Expected behavior**
Ability to use item store in each block if it is possible, like all other stores from `createAccordion()`

**Screenshots**
<img width="892" alt="image" src="https://github.com/melt-ui/melt-ui/assets/7033855/807c9d74-56a2-4681-b85c-e534991cf8a2">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 114

**Smartphone (please complete the following information):**

**Additional context**

To reproduce using Stackblitz, use this [template](https://stackblitz.com/edit/node-rvtbvk?file=package.json) and modify the `src/routes/+page.svelte` file.

**Comment by TGlide** [comment]
Hey! You're redeclaring `item` in your each loop.

Working example forked from yours: https://stackblitz.com/edit/stackblitz-starters-2efqby?file=src%2Froutes%2Fdemos%2Faccordion%2F%2Bpage.svelte

Closing as solved, but please let me know if you have further issues!

**Comment by dcheglakov** [comment]
Thanks. Sorry, stupid mistake.

**Comment by TGlide** [comment]
> Thanks. Sorry, stupid mistake.

No worries, it happens to the best of us 😄
