### ISSUE TITLE
🐛Bug: For hover card, add touch event 

### ISSUE THREAD

**Issue by jasongitmail** [melt-ui/melt-ui#195]
**Describe the bug**
The Hover Card is currently unusable for mobile users. It's not possible to see the content.

**To Reproduce**
1. Go to https://www.melt-ui.com/docs/builders/hover-card
2. Tap on the example 
3. Nothing is shown 

**Expected behavior**
Contents should be visible to users on mobile devices.

**Smartphone (please complete the following information):**
 - OS: iOS16
 - Browser: safari
 - Version unknown

**Comment by huntabyte** [comment]
When looking at [Radix's Hover Card](https://www.radix-ui.com/docs/primitives/components/hover-card), it also doesn't support touch.

It's a link so when it's touched it should take you to the link, right? Are you expecting it to function as both a touch to open the menu and also a link at the same time? @jasongitmail

**Comment by jasongitmail** [comment]
Ah, in that case I'd suggest updating melt UI's description text for this to be more similar to Radix's ![image](https://github.com/melt-ui/melt-ui/assets/50032291/4db017cb-425d-416d-b30d-71eda56f8ad7) ![image](https://github.com/melt-ui/melt-ui/assets/50032291/bcd9944a-3300-432e-87d4-f79f666b65a9) 
and to include a link as part of the example. 

Otherwise, with the current description, I was expecting more of a tooltip-like behavior.

**Comment by huntabyte** [comment]
Ah yeah, I see why that would cause confusion! We'll update the description, thanks for pointing that out!
