### ISSUE TITLE
🐛Bug: For popover, dismissing by tapping background causes page jump

### ISSUE THREAD

**Issue by jasongitmail** [melt-ui/melt-ui#198]
**Describe the bug**
When popover is open, click the surrounding area outside of it closes it but causes a page jump. 

I'm not totally sure if this is a bug or if it's the OS, but given that other components such as Select can be dismissed by clicking the surrounding background _without_ a page jump, I think this may be a bug.

**To Reproduce**
1. Go to https://www.melt-ui.com/docs/builders/popover
2. Tap to open  
3. Tap orange background to close it. It closes successfully, but page jumps unpleasantly 

**Expected behavior**
Closes without causing a page jump, similar to how the Select component (https://www.melt-ui.com/docs/builders/select) can be closed without a page jump by clicking the surrounding background 

**Smartphone (please complete the following information):**
 - OS: iOS16
 - Browser: safari
 - Version unknown

**Comment by huntabyte** [comment]
Yeah, I'm able to reproduce this bug on my phone using the safari browser. None of the other mobile browsers or desktop browsers produce this behavior.

Will look into it!
