### ISSUE TITLE
🐛Bug: Menubar trigger change lags

### ISSUE THREAD

**Issue by Giggiux** [melt-ui/melt-ui#199]
**Describe the bug**
Using the MeltUI website, using the Menubar, on the desktop when the mouse moves between triggers, the close/open action lags. 
On Mobile changing menu requires two clicks: one to close the current one (and focuses the clicked); another to actually open the menu. 

**To Reproduce**
1. Go to ['Melt-UI docs > Menubar'](https://www.melt-ui.com/docs/builders/menubar)
2. Click on "File" trigger opening the menu
3. Move the mouse in any other Trigger (e.g., "Help")
4. The close animation of the Menu will take a little bit and also the open of the new one, making it seems like it's lagghy.

**Expected behavior**
I would expect an instant switch in the menus when changing/overing over the triggers. As it would happen in a native macOS menu bar.

**Video**
Here a couple of videos, [published on Melt's Discord](https://discord.com/channels/1116682155809067049/1117779396992979024/1129006546051936276).
https://cdn.discordapp.com/attachments/1117779396992979024/1129006545515057272/meltui_menubar.mov
https://cdn.discordapp.com/attachments/1129006546051936276/1129011951347957901/RPReplay_Final1689247765.MP4

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1
 - Browser chrome, and safari. Chrome less visible.
 - Version Safari 16.5.1 / Chrome Version 114.0.5735.198 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.5.1 (a)
 - Browser Safari

**Additional context**
Not sure if it's an animation related bug or a trigger configuration issue, or anything else

**Comment by huntabyte** [comment]
Hey thanks for raising this issue @Giggiux, I can definitely reproduce this. This appears to have been introduced when trying to fix some tab index issues on Firefox.

Going to dig back through those commits to see what's causing this behavior specifically.
