### ISSUE TITLE
🐛Bug: VSCode not picking up `melt` attribute in monorepo

### ISSUE THREAD

**Issue by jtlapp** [melt-ui/melt-ui#219]
**Describe the bug**
I don't know if this is a bug or a docs issue.

I have SvelteKit installed in a monorepo workspace, and I have melt-ui building and working in the app. But the VSCode editor reports the following error for each occurrence of the `melt` attribute:

"Object literal may only specify known properties, and '"melt"' does not exist in type 'HTMLProps<"button", HTMLAttributes<any>>'."

Any suggestions for how I might get VSCode to recognize the presence of this attribute in a monorepo workspace?

To get VSCode to recognize TailwindCSS classes in a monorepo workspace, I had to configure the absolute path to `tailwind.config.js` in `postcss.config.js`, but I'm don't see an analogous thing to do for melt-ui.

**Screenshots**
![Screen Shot 2023-07-15 at 09 21 39](https://github.com/melt-ui/melt-ui/assets/138133/f508300a-f8db-4943-8ad0-abbac24a28ca)

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Chrome 114.0.5735.198

**Additional context**
    "@melt-ui/pp": "^0.0.4",

**Comment by AdrianGonz97** [comment]
Hi @jtlapp! Please ensure that your version of `@melt-ui/svelte` is on version `0.22.0` or higher. The `melt` attribute was introduced as part of that release.

**Comment by jtlapp** [comment]
That was it! My monorepo was using an older version, while my experiment in a regular repo was using the new version. Explains why one worked and the other didn't. Thank you!

This is soooo very nice!!!

**Comment by jtlapp** [comment]
For other folks who end up here trying to get melt-ui working in a monorepo, here is what I had to do to be able to melt-ui in component workspaces.

Each component workspace `package.json` includes these dependencies:

```
// package.json
{
  // ...
  "devDependencies": {
    // ...
    "svelte": "^4.0.0",
    "tsconfig": "workspace:*"
  },
  "dependencies": {
    // ...
    "@melt-ui/svelte": "^0.22.2"
  }
```

I also needed the component workspace's `tsconfig.json` to extend the applications `.svelte-kit/tsconfig.json`. You can't just copy this file to a shared location because its `includes` and `excludes` keys will refer to the wrong directory. You could simply copy the file to each component workspace, but then you'll be manually synching them -- and you may not know when SvelteKit updates it (but I don't know if it ever does).

So I instead created a symbolic link to the app's `.svelte-kit/tsconfig.json` from each components workspace and extended that. Here's my component workspace `tsconfig.json`:

```
// tsconfig.json
{
  "extends": ["./tsconfig.svelte-kit.json", "tsconfig/tsconfig.svelte.json"],
  "compilerOptions": {
    "paths": { "@/*": ["./src/*"] }
  }
}
```

I'm extending two tsconfig files. The local `tsconfig.svelte-kit-json` is a symbolic link to the app's `.svelte-kit/tsconfig.json`, and `tsconfig/tsconfig.svelte.json` is a reference to a configuration file in my `tsconfig` workspace that sets my preferred type enforcement rules.

I'll update this post if I learn of a better way.
