### ISSUE TITLE
🌟Feature request: Native dialog element support for the dialog builder

### ISSUE THREAD

**Issue by TheOnlyTails** [melt-ui/melt-ui#221]
**Is your feature request related to a problem? Please describe.**
N
The `<dialog>` element is widely supported today, and I'd prefer it if I could use it instead of the `portal` action with the dialog builder.

**Describe the solution you'd like**
Add an option/new builder which uses the native dialog element directly instead of just a div.

**Comment by TGlide** [comment]
Using the native dialog element together with Melt's dialog JS behaviours would probably cause some really weird clashing, functionality and accessibility wise. I'd say it's best to opt for one or the other.
