### ISSUE TITLE
🐛Bug: Last items in mobile nav aren't visible

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#226]
The mobile navigation needs to have additional padding at the bottom to ensure it all the items can be seen on every phone.

**Comment by TGlide** [comment]
Can't repro this, tbh! Any more info?

**Comment by geerew** [comment]
I still see it 

here’s a video, where you can see the tooltip is always hidden and even if you scroll up it slides down again

I am on iOS and using safari

**Comment by geerew** [comment]
Sorry on mobile and the video isn’t uploading .. 

![IMG_7275](https://github.com/melt-ui/melt-ui/assets/494875/e7094505-3de7-46a7-b766-79186fed821c)

here’s a photo where I’ve scrolled to the bottom and tooltip is off the screen.

**Comment by huntabyte** [comment]
> I still see it
> 
> here’s a video, where you can see the tooltip is always hidden and even if you scroll up it slides down again
> 
> I am on iOS and using safari

Sorry for the lack of details, left this here as a reminder for myself to take care of! Going to look into this now, as I'm experiencing exactly what @geerew's screenshots show!
