### ISSUE TITLE
📁Docs: mobile navigation menu performance

### ISSUE THREAD

**Issue by theetrain** [melt-ui/melt-ui#229]
Regarding the mobile navigation:

1. Sometimes the navigation bar does not stick to the bottom of the viewpoint 
2. Scrolling up and down the menu items has a delayed response. It seems to be a paint issue; CSS compositing may help

Tested on Brave (Chromium-based).

Demo: https://1drv.ms/v/s!AiYkuFzTVuydrEHxcVfBL1ya3fW6

**Comment by huntabyte** [comment]
There's another bug with the mobile nav as well #226 - is this something you'd want to try to take care of @theetrain ?

**Comment by theetrain** [comment]
I probably don't have the capacity to contribute at this time, sorry.

**Comment by huntabyte** [comment]
No worries, @theetrain! Opening issues are more than enough contribution :)

**Comment by huntabyte** [comment]
Can anyone confirm this issue still persists? I'm not able to reproduce but I have an iPhone/Mac so my testing options are limited here.

**Comment by theetrain** [comment]
No issue on my end!
