### ISSUE TITLE
Labels with Select

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#244]
### Discussed in https://github.com/melt-ui/melt-ui/discussions/194

<div type='discussions-op-text'>

<sup>Originally posted by **alexnguyennz** July 13, 2023</sup>
Hi is it possible to use labels with Select? Like on [this page](https://www.melt-ui.com/docs/builders/label) but with Select e.g. where clicking on labels gives focus to normal selects. Thanks.</div>

**Comment by huntabyte** [comment]
Agreed. I can tackle this if you haven't already? @TGlide

**Comment by TGlide** [comment]
> Agreed. I can tackle this if you haven't already? @TGlide

No worries, I'm on it!
