### ISSUE TITLE
⚙Tech Debt: Standardize hidden input behaviour

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#249]
Some builders expose hiddenInput stores, such as `createSelect` and `createRadioGroup`. They vary in usage though, as with `createSelect`, you have an optional `name` prop that's passed to the hidden input, that's missing in `createRadioGroup`.

We should standardize the API to improve expected usage.

**Comment by Silbad** [comment]
Hi, how do I add the name / id attributes to the hidden field? I have version 0.73.0.
Thanks

**Comment by TGlide** [comment]
> Hi, how do I add the name / id attributes to the hidden field? I have version 0.73.0. Thanks

You add them via HTML attributes:

```html
<input use:melt={$hiddenInput} name="name" id="id" />
```
