### ISSUE TITLE
🌟Feature request: Builtin transition utility that works with hidden

### ISSUE THREAD

**Issue by david-plugge** [melt-ui/melt-ui#256]
**Is your feature request related to a problem? Please describe.**

If you want to hide something in svelte you are most likely end up with an if block. While that´s awesome DX it can lead to UX issues (I´m far from beeing a UX expert, i just read about all that stuff). Since this library focuses on accessibility it would be awesome to have a builtin solution to this problem.

**Describe the solution you'd like**

Provide a component (or builder function to match the library style) that makes it easier to use the `hidden` attribute without overwriting the default behavior `[hidden] { display: none; }`.

**Describe alternatives you've considered**

Do it on your own.

**Additional context**

I´ve been playing around alot and came up with a component that can be used like so:

```svelte
<script>
  let show= false;
</script>

<button on:click={() => show= !show}>toggle</button>

<Transition {show} let:target let:hidden>
  <div use:target class:translate-y-4={hidden}>
    ...
  </div>
</Transition>
```

`let:hidden` is true when the element is *leaving* or *hidden* and the component waits for all animations running on the elements with `use:target` before `hidden` is set.

A builder pattern could look like this:

```svelte
<script>
  const { root, visible, show } = createTransition();
</script>

<button on:click={() => $show= !$show}>toggle</button>

<div melt={root} class:translate-y-4={!$visible}>
  ...
</div>
```

If you think this could be a nice addition to the library, i´d be happy to contribute!

**Comment by TGlide** [comment]
Thanks for the well thought-out issue! 

What UX problems have you encountered with using `#if`? We do know about certain issues it causes in certain builders, such as Select. But I'd really like to find a solution for it with native Svelte transitions support.

Regarding CSS or JS transitions without Svelte's `transition` directive, we have plans for a `forceMount` option, that'd remove the `hidden` attributes. That way, you can use the builder store value and apply CSS/JS transitions however you'd like. I think this is more versatile than a `createTransition` builder:

```html
<script>
  const { root, visible, show } = createTransition();
  const { open, root } = createDialog();
  
  open.subscribe($open => show = $open)
</script>

<div melt={root} class:translate-y-4={!$visible}>
  ...
</div>
```

versus

```html
<script>
  const { open } = createDialog();
</script>

<div melt={$root({ forceMount: true }} class:translate-y-4={!$open}>
  ...
</div>
```

Let me know what you think!

**Comment by david-plugge** [comment]
Thanks for the detailed reply!

I´ll always vote for native svelte functionality if possible, far more readable and elegant.

My main thought was if you remove elements from the dom, would you still get full aria support? What about `id` and `aria-controls` for example. A trigger may point to a non existing id. As i said, i´m fairly new to this whole accessibility stuff but to me that doesn´t make sense.

Not sure if i fully understand `forceMount`. How do you hide the element without `hidden`, is that up to the developer and the library only adds attributes like `aria-hidden`?

**Comment by TGlide** [comment]
@david-plugge I just noticed I never answered you, and I apologise!

Yes, we probably shouldn't be removing elements from the DOM because of ARIA attributes. Currently we have the  `forceVisible` prop and you can animate using it. So I think we can close this issue!
