### ISSUE TITLE
🌟Feature request: Dropdown/popover trigger on hover

### ISSUE THREAD

**Issue by iivankin** [melt-ui/melt-ui#267]
**Is your feature request related to a problem? Please describe.**
Currently only the click event is supported in dropdown menu. It should be possible to hover on a desktop and touch on a mobile.

**Describe the solution you'd like**
https://floating-ui.com/docs/useHover

**Describe alternatives you've considered**
HoverCard only works on desktop.

**Comment by TGlide** [comment]
Touch should be working for dropdown menu, is it not working for you?

Regarding hover functionality, the Dropdown Menu trigger follows the [Menu Button WAI-ARIA pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/), and Popover follows the [Dialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/), both not specifying hover functionality. I do advise following these behaviours!

Regardless, we're working on improved controlled usage #257. You'll be able to add custom functionality and control the stores however you'd like.

Closing in favor of #257

**Comment by iivankin** [comment]
Hover is not working in dropdown. When I set `$open = true` in mouseenter it causes weird positioning behavior
