### ISSUE TITLE
🌟Feature request: use default Tailwind config

### ISSUE THREAD

**Issue by kenbankspeng** [melt-ui/melt-ui#273]
Thank you for melt-ui. 

I know this is a very minor thing but if your examples used the default tailwind configuration for styling, no reference to a custom config would be required, and for those not so interested in a custom tailwind config, or in one that doesn't align with your custom config (independent of how good yours might be), then the user wouldn't have to do a find and replace. 

But not a big deal, as the find and replace only takes a moment. So just a suggestion.

**Comment by TGlide** [comment]
Hi @kenbankspeng, thanks for the suggestion! I figure users will already be replacing a lot of the examples code anyways to fit their own needs, so I'd rather keep it as is, mostly to fit the site's palette. While I could use inline values (e.g. `bg-[#fafafa]`), there are some utilities and more complex values that'd make authoring the examples harder.

I'll be closing this issue as non-planned, but I appreciate you reaching out with this!

**Comment by kenbankspeng** [comment]
I agree that users are editing the examples anyway. Thanks.
