### ISSUE TITLE
🐛Bug: Dropdown bugs with transition and state

### ISSUE THREAD

**Issue by iivankin** [melt-ui/melt-ui#274]
**Describe the bug**
- Svelte `out` transition not working at all. `in` working as expected.
- When you update something with a variable in `CreateDropdownMenuProps` (for example `gutter`), it does not change the state in any way and is probably ignored
- In stackblitz I noticed that when you click many times on the trigger, the dropdown starts to slide downward

**To Reproduce**
[Stackblitz](https://stackblitz.com/edit/github-6fpcgh?file=src%2Froutes%2F%2Bpage.sveltel)

**Expected behavior**
Things should not break

**Additional context**
ETA for The Big Bad™?

**Comment by huntabyte** [comment]
The in/out behavior is related and _should_ be solved by #70.

As for the other issues are certainly bugs that we will look into!

**Comment by huntabyte** [comment]
Touching back on this issue, you were attempting to update the props being passed to the builder. With the next release, the options will be returned from the builder as stores that you can update reactively.

The transition pieces are closed by #234
