### ISSUE TITLE
🐛Bug: Combobox Input Clicks

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#277]
**Describe the bug**
When the combobox menu is open and you click the input, it quickly closes and then opens again. The same thing happens when you click the label which probably shouldn't be the case.

**To Reproduce**
1. Go to https://melt-ui.com/docs/builders/combobox
2. Click the input (the menu should open)
3. WIth the menu still open, click the input again

**Expected behavior**
If you click the input and the menu is already open, it shouldn't close and reopen again

**Proposed Solution**
Use the `handler` within the internal `clickOutside` action to ignore the click if the target was the label, content within the label, or the input itself.

**Comment by fkling** [comment]
It appears that the fix (or maybe some other change after that) now causes the menu to close when clicking inside the input again while it's already open. That feels wrong to me for two reasons:
- The user might click inside the input to open it but then wants to move the caret  to a different position via the mouse. Now when they click on another character the input closes.
- Double clicking on the input, to select it, causes the menu to appear and disappear.

Arguably it's likely that in both cases the user then uses the keyboard to change the value of the input, which would show the menu again, but I still find it surprising that the menu disappears.

I'm happy to file a new bug for this if desired.

**Comment by TGlide** [comment]
> It appears that the fix (or maybe some other change after that) now causes the menu to close when clicking inside the input again while it's already open. That feels wrong to me for two reasons:
> 
> * The user might click inside the input to open it but then wants to move the caret  to a different position via the mouse. Now when they click on another character the input closes.
> * Double clicking on the input, to select it, causes the menu to appear and disappear.
> 
> Arguably it's likely that in both cases the user then uses the keyboard to change the value of the input, which would show the menu again, but I still find it surprising that the menu disappears.
> 
> I'm happy to file a new bug for this if desired.

You have a point. Feel free to open up a new issue.
