### ISSUE TITLE
🐛Bug: [Docs] Toolbar preview cutoff on mobile

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#281]
**Describe the bug**
On mobile devices, the toolbar seems to be cutoff/too large.

![image](https://github.com/melt-ui/melt-ui/assets/64506580/12eef1fc-d565-4e07-81cc-c99e3b1f13fe)

![image](https://github.com/melt-ui/melt-ui/assets/64506580/adf32733-63a1-4e6d-adf3-e7b2d2d10dce)

**Comment by TGlide** [comment]
Fixed!
