### ISSUE TITLE
Vaul: Unstyled drawer component. Worth porting to Melt-UI?

### ISSUE THREAD

**Issue by maietta** [melt-ui/melt-ui#293]
An unstyled drawer component for React was just released a few days ago and it is super smooth and in my opinion, would be a great component to port to Melt-UI. It's best suited for mobile, not desktop unless perhaps slide in from left or right? idk.

https://vaul.emilkowal.ski/

[![image](https://github.com/melt-ui/melt-ui/assets/11745020/a5905879-dea8-4314-bab5-b468ec0024b7)](https://github.com/emilkowalski/vaul/assets/36730035/fdf8c5e8-ade8-433b-8bb0-4ce10e722516)

**Comment by TGlide** [comment]
You can make this *with* Melt UI (some people were actually discussing it over discord!), just like it was built with Radix over on React, but what makes this component good, is the custom animation and drag handling, which is not unopionated as we'd like to be. So I feel this wouldn't be a good fit, even though it's an awesome component!

**Comment by maietta** [comment]
> 

Thanks for the response and explanation!

**Comment by TGlide** [comment]
> > 
> 
> Thanks for the response and explanation!

Thank you for the suggestion!
