### ISSUE TITLE
🐛Bug: Form Actions Dont Work Inside Context Menu

### ISSUE THREAD

**Issue by rondDev** [melt-ui/melt-ui#309]
**Describe the bug**
Forms don't seem to work inside of a context menu.

**To Reproduce**

Create a [Context Menu](https://www.melt-ui.com/docs/builders/context-menu#usage).
Something like:
```html
<div style="width: 10rem; height: 10rem;" melt={$trigger}></div>
  <div class="menu" melt={$menu}>
    <form action="?/someaction" method="POST">
      <input type="hidden" name="file" value={"somevalue"} />
      <button melt={$item} type="submit">Trigger</button>
    </form>
</div>
```
Where you have the action `someaction` in +page.svelte.ts:
```ts
const someaction: Action = async ({ request }) => {
  doSomething();
};

export const actions: Actions = { remove };
```

This should in theory submit a form action, but doesn't seem to be doing anything.

**Expected behavior**
Form action should be submitted when button in context menu is pressed.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox Developer Edition ( Version 116.0b8 (64-bit )) and Chrome ( Version 115.0.5790.110 )

[Template to recreate the issue on stackblitz](https://stackblitz.com/github/ronddev/melt-ui-context-menu/tree/main)
On Stackblitz an action is called when hitting the 'Delete' button, but doesn't get triggered when you try to use the context menu button even though they call the same form action.

**Comment by huntabyte** [comment]
Sorry for taking so long to address this issue - this is 100% some sort of race condition. We most likely need to wait for a tick before taking action in the click event handler of the items.

Will do some tests and open a PR once I can resolve it.
