### ISSUE TITLE
🐛Bug: Select hover then mouse move

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#31]
**Describe the bug**

With the select 'component' there are bugs whereby you open the menu, hover the mouse over an option, say the 3rd one, then start pressing the down/up arrow.

1. 2 elements will be 'highlighted'. I know this is to do with the css (hover: and focus:) but something should happen to stop the hover: effect when the keyboard down/up is pressed, for example https://captaincodeman.github.io/svelte-headlessui/listbox/ handles this somehow.

2. The loop around from the end to the start is incorrect. Say I hover over the 3rd item, then keep pressing down, I will get to the bottom, and loop back around. However, the first 2 elements are skipped and it jumps to the 'hovered option

**To Reproduce**
1. go to https://www.melt-ui.com/docs/builders/select
2. click the trigger
3. hover over orange
4. press the down arrow on your keyboard (now 2 items are hightlighted)
5. keep pressing down until you loop back around (apple and banana are skipped)

**Expected behavior**
Only 1 option is highlighted, regardless of hover: and focus:. The looping functionality does not skip options

**Screenshots**

**Desktop (please complete the following information):**
- Mac
- Firefox

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by TGlide** [comment]
Hi! Thanks for the issue. I definitely agree with the first point! 

I couldn't reproduce the 2nd one, except when the page scrolled down because the focused item was out of focus, which led to the cursor moving to another item and focusing that instead. Is that what happened in your case? If so, this should be solved with overflow detection which I want to implement.

**Comment by geerew** [comment]
I tested your latest change and issue 1 is fixed.

It also seems like issue 2 is not longer a problem anymore (possibly due to the issue 1 fix)

This can be closed.
