### ISSUE TITLE
🌟Feature request: Pin input requires pressing backspace twice to delete digit

### ISSUE THREAD

**Issue by cd-slash** [melt-ui/melt-ui#319]
**Describe the bug**
Removing a digit in the pin input requires pressing backspace twice.

**To Reproduce**
Seen on the [MeltUI demo page](https://www.melt-ui.com/docs/builders/pin-input) for the pin input.

**Expected behavior**
 a single backspace should remove the current digit and each subsequent press should remove another digit until the pin input is clear (in my opinion)

**Desktop (please complete the following information):**
 - Browser: Chrome, Polypane

**Comment by wesharper** [comment]
I agree that the behavior is a bit odd although I could go either way. However, based on the documentation, `backspace` does the following: `Deletes the value of the current input. If the input is empty, moves to the previous input.`. I'd recommend changing this to a feature request instead.

**Comment by cd-slash** [comment]
I did a bit of investigation by logging into various services that I know require OTP including eBay, PayPal, Amazon and various others to understand what users might expect based on typical OTP experiences. In all cases, backspace removes the previous digit.

I think this is consistent with a normal typing experience, i.e. if this was 1 single input field instead of separate inputs, a backspace would remove a character, rather than just moving to the next character and not removing it. If the user is not looking at the input and trying to type e.g. "1234" but types "1,2,4", realises they've made a mistake, hits backspace and types "3,4" in a normal input they'd get "1234" but with this behavior they'd get "1243" with the last "4" lost because the digit limit is reached.

Happy to adjust to a feature request since the current behavior was intended, it just seems inconsistent with what a given user would (probably) expect.

**Comment by wesharper** [comment]
@cd-slash I've changed the functionality in my draft PR. Will wait for the maintainers to give the green light before I polish it up and attempt to get it merged.
