### ISSUE TITLE
🐛Bug: No way to define a combobox value

### ISSUE THREAD

**Issue by jordigagomerino** [melt-ui/melt-ui#326]
**Describe the bug**
On the version before there was a $selectedItem store on the combobox. That was very useful to set a first value. So for example an update form was possible, this option is gone and there is no way to set this value. I think this is a bug because it was working before.

**To Reproduce**
Try set the first value on the combobox.

**Expected behavior**
Be able to set a value on the combobox as other elements do like switch.

**Comment by TGlide** [comment]
This is definitely an oversight on our end! Will try and resolve this quickly.

**Comment by jordigagomerino** [comment]
Thank you!!
