### ISSUE TITLE
🐛Bug: Popover remains open during development

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#33]
**Describe the bug**
While styling a popover, I would open it to see what it looks like, then head back to my editor and update it.

There is a bug that when the popover is open, and an change is made to the page, the popover will 'glitch', move to the top left of the screen and remain open.

An example of this can be seen here -> https://stackblitz.com/edit/node-fdgwxx?file=src%2Froutes%2F%2Bpage.svelte,.prettierrc)

**To Reproduce**

1. Open the stackblitz example
2. open the popover
3. make a change in the editor (while the popover is still open) and save

**Expected behavior**
The popover is destroyed due to a reload

**Screenshots**
n/a

**Desktop (please complete the following information):**
- OS: Mac OS
- Browers: Firefox, Safari, Chrome

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by geerew** [comment]
The same things happens with dialog

**Comment by TGlide** [comment]
@geerew The issue is not happening with me on the latest version of Melt UI. Can you confirm? Thanks 😄
