### ISSUE TITLE
🌟Feature request: allow value selection based on something other than `index`

### ISSUE THREAD

**Issue by wesharper** [melt-ui/melt-ui#340]
**Is your feature request related to a problem? Please describe.**
I'd like to build something similar to this TailwindUI example:
![image](https://github.com/melt-ui/melt-ui/assets/13283469/f0281868-2572-4b95-801f-07dd512546a4)

Unfortunately, the existing combobox API is a bit limiting because in order to select an item, the following conditions must be met:
1. `items` must be defined
1. `items` must be a flat array
1.  `index` on `$item` must correspond with an index in `items`

These constraints make it hard to implement a combobox with distinct categories as seen in the image. Consider the following snippet that searches for employees in a company directory on a remote data source:
```svelte
<script lang="ts">
  import { GlobeAltIcon } from 'heroicons-svelte/24/outline';
  import { createCombobox, melt } from '@melt-ui/svelte';

  let results: {
    categoryName: string;
    matchedResults: { id: string, name: string }[];
  }[] = [];
  let searchPromise: Promise<void>;

  const {
    elements: { input, menu, item, label },
    states: { open, inputValue, value },
  } = createCombobox<{ data: any }>({
    items: [],
    itemToString: (employee) => employee.name,
    filterFunction: () => true
  });

  async function search(query: string) {
    const result = await fetch(
      `${import.meta.env.VITE_API_BASE_URL}/api/v1/search?query=${query}`,
    );
    const { data } = await result.json();
    results = data.attributes.records;
  }

  inputValue.subscribe((query) => {
    searchPromise = search(query ?? '');
  });
</script>

<h1>This will never get set: {$value}</h1>
<div class="relative flex flex-1">
  <div class="relative flex flex-1">
    <label use:melt={$label} for="search-field" class="sr-only">Search</label>
    <input
      use:melt={$input}
      placeholder="Search..."
      type="search"
      name="search"
      role="combobox"
      aria-expanded={$open}
      aria-controls="options"
      value={$inputValue}
    />
  </div>
  {#if $open}
    <div use:melt={$menu}>
      {#await searchPromise}
        <div class="border-t border-gray-100 px-6 py-14 text-center text-sm sm:px-14">
          <GlobeAltIcon class="mx-auto h-6 w-6 text-gray-400" />
          <p class="mt-4 font-semibold text-gray-900">Searching...</p>
        </div>
      {:then}
        <ul
          class="max-h-80 scroll-pb-2 scroll-pt-11 space-y-2 overflow-y-auto pb-2"
          id="options"
        >
          {#each results as category}
            <h2 class="bg-gray-100 px-4 py-2.5 text-xs font-semibold text-gray-900">
              {category.categoryName}
            </h2>
            <ul class="mt-2 text-sm text-gray-800">
              {#each category.matchedResults as employee, index (employee.id)}
                <li
                  use:melt={$item({
                    index: index,
                    item: employee
                  })}
                  class="cursor-default select-none px-4 py-2 data-[highlighted]:bg-purple-700 data-[highlighted]:text-white"
                >
                  {employee.name}
                </li>
              {/each}
            </ul>
          {/each}
          <!-- empty state -->
          {#if results.length === 0}
            <div class="border-t border-gray-100 px-6 py-14 text-center text-sm sm:px-14">
              <FaceFrownIcon class="mx-auto h-6 w-6 text-gray-400" />
              <p class="mt-4 font-semibold text-gray-900">No results found</p>
              <p class="mt-2 truncate text-gray-500">
                We couldn't find anyone filed under <span class="text-gray-900"
                  >{$inputValue}</span
                >.
              </p>
            </div>
          {/if}
        </ul>
      {/await}
    </div>
  {/if}
</div>
```

This renders well and the key bindings generally work. However, selection is broken because in order to create a categorized layout using the above approach, `items` is ignored to facilitate the looping structure. To either build the categorized markup using a flat array, or to use the existing markup but create a matching flat array with corresponding item indexes is cumbersome.

**Describe the solution you'd like**

In a perfect world the following would happen:
1. `items` would become opaque and build itself out of the items registered using `use:melt={$item}` instead of having to be set/updated manually
1. `$selectedItem` would be determined using a unique key rather than an array index 

**Describe alternatives you've considered**

One potentially lighter-weight alternative would be to expose $isActive. It may have the same pitfalls, but the internal state of `$isActive` seems like it would work because the keyboard navigation works to highlight the correct item: this is linked in [another request](https://github.com/melt-ui/melt-ui/issues/341). However, I may be misunderstanding how Melt is determining highlighted state.

Some workarounds I've considered are:
1. Manually hijacking the selection logic on click and upon hitting `return`
1. Removing the categories from the top level and adding categories to the list item element

**Additional context**

**Comment by wesharper** [comment]
Currently, I'm manually augmenting the `m-keydown` event and querying for `data-highlighted`, then manually updating the value.

**Comment by huntabyte** [comment]
Hey @wesharper , does the recent update to the combobox close this issue for you?
