### ISSUE TITLE
🌟Feature request: add $isActive store

### ISSUE THREAD

**Issue by wesharper** [melt-ui/melt-ui#341]
**Is your feature request related to a problem? Please describe.**
I'd love to build something like this:
![image](https://github.com/melt-ui/melt-ui/assets/13283469/657e37a2-5222-441f-8126-4feb0ecadcc3)

Here, there is a clear distinction between `activeItem` and `selectedItem`. The first returns the item that's highlighted, so the values of the item can be used to render more information, while the `selectedItem` is used to set the actual `value` of the input.

**Describe the solution you'd like**
Add a store called `$isActive` that has the same consumer API as `$isSelected`

**Describe alternatives you've considered**
I still haven't thought potential alternatives all the way through because this feature is still a "nice to have" for my project for the time being.

**Additional context**
None

**Comment by huntabyte** [comment]
I think I see what you're getting at. Basically you're wanting isActive to represent whatever is being focused while still keeping selected the same. So you could flip through a big combo box type menu (like in your picture) and have some kind of preview of the active item's info render on the right side, without changing the selected value.

I don't think this is a bad idea, nor a super edge case and from my initial thoughts it _shouldn't_ be a heavy lift to implement.

**Comment by TGlide** [comment]
@wesharper do you feel like this would be better implemented as the command center I've mentioned?

**Comment by wesharper** [comment]
@TGlide it definitely fits better in a command center, my only concern is that depending on the implementation of command center, it may be too opinionated in its own right. Basically, I'm building this layout:

<img width="817" alt="image" src="https://github.com/melt-ui/melt-ui/assets/13283469/f970e44f-dcb5-44a2-a5ea-49a3a444deab">

Essentially, we want the search bar in the header to trigger a command-center-like global search behavior. The way TailwindUI accomplishes this is by using their HeadlessUI Combobox primitive, which is in turn the foundation for their implementation of their command center. The internals do more work, but the user-facing API is relatively straightforward and flexible.

I get the sense that the command center would do everything I want, but making the combobox flexible enough to be the underlying primitive could also be useful for people who have customized needs. Here's a look at what I've built using the Melt combobox for an idea:

https://github.com/melt-ui/melt-ui/assets/13283469/dba3a59b-158a-48b1-8998-babf8ff37e71

If you feel like the command center you're building gives me all of what I need, I'm happy to hold tight. Also happy to contribute (and ultimately want to do so on a more regular basis) but still trying to wrap my head around what's happening in the source code.

**Comment by huntabyte** [comment]
> EDIT: In any case, I do think we can revisit the combobox. Right now it's more of an `Autocomplete` component.

Agree with this one. I think it needs a bit more flexibility. One of the more challenging components to get right! It's great for what it can do right now, but if you want to do something a bit more unique, it has some limitations!
