### ISSUE TITLE
🌟Feature request: update menu so it can be opened without a trigger

### ISSUE THREAD

**Issue by wesharper** [melt-ui/melt-ui#342]
**Is your feature request related to a problem? Please describe.**
It's possible that I missed something obvious, but I would love for a menu or dropdown menu primitive that can be opened programmatically without a trigger button. I attempted to update the `$open` store directly, but the dropdown menu internals were still setting `display: none` and `hidden` to the elements.

**Describe the solution you'd like**
Add an `openMenu` helper that fires all the same events as `trigger`.

**Additional context**
This came out of wanting a complex combobox that could render categories but ultimately be used for navigation rather than setting a form value (think Mac's command palette).

**Comment by TGlide** [comment]
The menu components need a trigger to anchor itself to. When a trigger is present, you can programatically set the open store though.

Also, I'm designing a command center builder. So I think this will be more inline with what you want!

**Comment by wesharper** [comment]
Nice, good to know, thanks! Awesome to have a command center builder coming!
