### ISSUE TITLE
🌟Feature request: Export selectedItem from createCombox builder

### ISSUE THREAD

**Issue by winston0410** [melt-ui/melt-ui#343]
**Is your feature request related to a problem? Please describe.**
In the past I rely on `selectedItem` exported from `createCombox` to update the value of the input, as I binded that input to the form's value(I am using `superforms`). 

Since the latest update, the `selectedItem` store is no longer exported

**Describe the solution you'd like**
Export `selectedItem` store

**Describe alternatives you've considered**
Subscribe to `inputValue`. But this will not work, as `inputValue` will be updated `on:input` by default, and there is no way to tell if `inputValue` is updated because of input or selection options of combobox

**Additional context**

**Comment by TGlide** [comment]
This is now called the value store.
