### ISSUE TITLE
🐛Bug: Submenu inside dropdown menu not fully visible on mobile

### ISSUE THREAD

**Issue by marvwebdev** [melt-ui/melt-ui#346]
**Describe the bug**
On mobile, when clicking on the Profiles submenu entry inside the dropdown menu in the official docs, the submenu is not fully visible.

**To Reproduce**
1. Go to https://www.melt-ui.com/docs/builders/dropdown-menu on mobile
2. Click on the menu icon
3. Click on Profiles

**Expected behavior**
I excepted the submenu to be fully visible.

**Screenshots**
![bug](https://github.com/melt-ui/melt-ui/assets/127395156/2685198b-5ab4-4ca7-b2d1-56ccf7308c62)

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy A02s
- OS: Android 12
- Browser: Firefox
- Version: 115.2.1

**Comment by TGlide** [comment]
Fixed in `develop`branch
