### ISSUE TITLE
🐛Bug: selectedText for select comes from innerText

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#36]
**Describe the bug**
When using the select component, you use `selectedText.set(selectedOption.innerText);` to store the selected text. 

This leads to issues, for example

**1**

It breaks reactive statments on $selectedText. 

In the doc example, if you add `$: console.log('>' + $selectedText + '<');` and selected `Apple`, in console you will see`> Apple <` with a space before and after. This is because the {item} is on a new line and so there is technically whitespace before and after

If you then open the select menu again. the reactive statement is triggered again and you will see a console output of `>Apple<`, with no whitespace before or after. Opening and closing the menu via and outside click will keep triggering that reactive statement

**2**

This approach stops you from having additional text in the option, as it gets added to the $selectedText. For example, I may want to add a prefix of numbers to my options (1, 2, 3, ...)

**3**

It means that selectedText will ALWAYS be a string and will never return a number. However, a recent enhancement means that you can pass numbers as options. If I pass in a number, I would expected the $selectedText to be a number

**To Reproduce**
1. Add `$: console.log('>' + $selectedText + '<');` to the select doc example
2. Open the menu
3. Select Apple and monitor the console to see ` Apple ` (with spaces)
4. Open the menu and close it via outside click. Check console to see the reactive statement fired again, when it should not have

**Expected behavior**
The selectedText should be exactly what the option is. If the option is `bob` then selectedText should be `bob` (if selected)

Additionally, If I select bob and then open and close the menu without selecting anything else, my reactive statement should not run because selectedText will not have changed

Also, If my option is a number, I expect SelectedText to be a number

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Firefox, Safari, Chrome

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by TGlide** [comment]
> Can we mark this as complete with the PR merge? I know @huntabyte has opened a ticket to improve it.

I'd rather leave it as open, because it addresses some issues that the ticket doesn't mention, and I would love to improve this 😄

**Comment by TGlide** [comment]
Resolved by #44
