### ISSUE TITLE
📁Docs: In code examples always should index.svelte first

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#361]
In the `view code` section of examples, make it that `index.svelte` is always first.

Also it might be worth changing the color of the scrollbar or giving more padding. I was trying to click on the source code but was unknowling clicking on the scroll bar color..

**Comment by huntabyte** [comment]
Is this solved? @geerew

**Comment by geerew** [comment]
Sorry, I forgot to reply. Yeah it’s solved from what I see
