### ISSUE TITLE
🐛Bug: Combobox opens below then opens above (Occurs in doc)

### ISSUE THREAD

**Issue by duthanhduoc** [melt-ui/melt-ui#366]
**Describe the bug**
Combobox opens below then opens above

**To Reproduce**
1. Go to [https://www.melt-ui.com/docs/builders/combobox](https://www.melt-ui.com/docs/builders/combobox)
2. Click on Combobox example
3. See error

**Expected behavior**
Open above (like Radix UI)

**Video**

https://github.com/melt-ui/melt-ui/assets/33114640/2e952757-29c0-46f8-9aed-eb5c9618cba7

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.4
 - Browser Chrome 
 - Version 115.0.5790.114

**Comment by TGlide** [comment]
Fixed! (The website should be auto-updated in a few moments)
