### ISSUE TITLE
Switch does not work with Superforms

### ISSUE THREAD

**Issue by AndreasFaust** [melt-ui/melt-ui#369]
I am trying to connect the `Switch`-Component with [Superforms](https://superforms.rocks/get-started). Unfortunately the required binding `bind:checked={$form.confirmed}` seems not to work. Has this something to do with the preprocessor?

```svelte
<script lang="ts">
    import { createSwitch } from "@melt-ui/svelte";
    import { superForm } from "sveltekit-superforms/client";

    const { root, input, checked } = createSwitch();

    export let data;
    const { form, enhance } = superForm(data.form);
</script>

<form
    use:enhance
    method="POST"
>
    <button
        {...$root}
        use:root
        class={clsx(
            "relative h-6 w-11 flex-shrink-0 cursor-default rounded-full bg-black/20 transition-colors",
            "data-[state=checked]:bg-black/50"
        )}
        id="confirmation"
    >
        <span
            class="block h-5 w-5 translate-x-0.5 rounded-full bg-white
                transition-transform will-change-transform
                {$checked && 'translate-x-[22px]'}"
        />
        <input
            use:input
            {...$input}
            type="checkbox"
            name="confirmed"
            bind:checked={$formBinding.confirmed}
        />
    </button>

    <button>Send</button>
</form>
```

**Comment by TGlide** [comment]
Hi @AndreasFaust! We've recently discussed Superforms usage in our Discord. I came up with a simple Demo of how to integrate it with Checkbox: https://github.com/melt-ui/reproduction-template/tree/checkbox-superforms

It should be similar for Switch!

**Comment by AndreasFaust** [comment]
Thank you @TGlide for the quick reply! 
I cloned the repo and checked out the branch, but unfortunately the example does not work. I also tried out the solution in my project without success.
Is this in general the final implementation or just a workaround?

**Comment by TGlide** [comment]
> Thank you @TGlide for the quick reply! I cloned the repo and checked out the branch, but unfortunately the example does not work. I also tried out the solution in my project without success. Is this in general the final implementation or just a workaround?

I created an example with Switch: https://github.com/melt-ui/reproduction-template/tree/switch-superforms

https://github.com/melt-ui/melt-ui/assets/26071571/c78ab5bf-e91a-47c6-93e4-0fbfceecb798

The string version will only update SuperDebug on submit, which I believe should be fine. Let me know if this works for you, and if it doesn't, please send in a reproduction (Stackblitz or https://www.sveltelab.dev/ are good ways to share reproductions!)

**Comment by TGlide** [comment]
Marking as solved, but glad to re-open if the issue still persists.

**Comment by AndreasFaust** [comment]
It works. Thank you very much!
