### ISSUE TITLE
🐛Bug: Menubar lagging

### ISSUE THREAD

**Issue by Lakelimbo** [melt-ui/melt-ui#373]
**Describe the bug**
The [Menubar builder](https://www.melt-ui.com/docs/builders/menubar) is presenting a significant lag when clicking/touching. On mobile (or maybe touchscreen specifically) it seems like the focus closes the dropdown when alternating between menus.

**To Reproduce**
1. Build a Menubar, or just go to the one on the [docs](https://www.melt-ui.com/docs/builders/menubar)
2. Click on any of the menus
3. Notice the lag, and the weird behavior on touch

**Expected behavior**
The dropdowns should not lag, and the menu should not close this way on mobile/touch.

 - OS: Windows, Android, iOS (geerew on Discord)
 - Browser: Chrome, Edge, Firefox, Safari (geerew on Discord)

**Comment by wesharper** [comment]
This is actually not unique to mobile, the desktop version is slow on hover as well
