### ISSUE TITLE
🌟Feature request: Allowing bring your own store for `disabled` 

### ISSUE THREAD

**Issue by winston0410** [melt-ui/melt-ui#383]
**Is your feature request related to a problem? Please describe.**
I want to control whether a component is disabled based on certain condition. For example, make the Collapsible disabled, when condition X is not met.

**Describe the solution you'd like**
I want to bring my own store for `disabled` props, just like `open`.
For example I want to use Writable<boolean> for `disabled`

**Describe alternatives you've considered**
Passing the value of store into builder, but that is not reactive:

```ts
const disabled = writable(false)

// ...

createCollapsible({
  disabled: $disabled
})

// ...

disabled.set(true) //Doing this would update the store, but would not make the component disabled
```

**Additional context**

**Comment by TGlide** [comment]
Hey! I believe there is an alternative you haven't tried:

```
const { options: disabled } = createCollapsible()

// ...

$: disabled.set(condition)
```

Nonetheless, I agree with you that it'd be nice to allow passing in your own store in these situations. WIll leave this open!

**Comment by winston0410** [comment]
Indeed, I havn't tried that option yet, I will do it and come back to you, thank you so much. And yes being able to pass a store initially will be great

**Comment by TGlide** [comment]
Closing as I figure you'd probably need it for every option, and that'd be a nightmare for us to manage. Runes will also probbly solve this.
