### ISSUE TITLE
🐛Bug: opened dialog does not close when parent component is destroyed

### ISSUE THREAD

**Issue by maxhoffmann** [melt-ui/melt-ui#388]
**Describe the bug**
I have a component, which uses a Dialog. When the component unmounts/gets destroyed with the dialog being open, it continues to be displayed and becomes non-interactive. I’ve tried closing the dialog manually with a custom writable store for the open state and setting it to `false` in Svelte’s `onDestroy` hook, but this doesn’t work unfortunately.

**To Reproduce**
1. Create a component with a dialog
2. Open the dialog
3. Unmount the component with the dialog
4. The dialog stays visible, but becomes non-interactive

**Expected behavior**
I’d expect the dialog to close when the parent component unmounts.

**Example pseudo code**
In my project it looks something like this. Depending on the viewport width, the component with the dialog mounts/unmounts. Making the viewport smaller destroys the component, but the dialog remains visible and cannot be closed.

```svelte
  {#if viewportWidth >= BREAKPOINT_LG}
    <ComponentWithDialog />
  {/if}
```

**Comment by huntabyte** [comment]
Hey Max, if you wouldn't mind linking a repro stackblitz or similar, I'm happy to take a look @maxhoffmann

**Comment by maxhoffmann** [comment]
@huntabyte Finally was able to reproduce the bug: https://stackblitz.com/edit/melt-ui-playground-addfdp?file=src%2Froutes%2F%2Bpage.svelte

The issue seems to happen as soon as the component with the dialog is not a direct child of the svelte condition:

**This works:**
```svelte
{#if viewportWidth < 1024}
  <Dialog />
{/if}
```

**This does not work:**
```svelte
{#if viewportWidth < 1024}
  <div>
    <Dialog />
  </div>
{/if}
```

**Comment by maxhoffmann** [comment]
Thanks @huntabyte @TGlide! `v0.41.2` fixed this bug. 🙂

**Comment by TGlide** [comment]
Hey @maxhoffmann, thank you for raising the issue 😄
