### ISSUE TITLE
🐛"Bug": disabled="false" should not be applied

### ISSUE THREAD

**Issue by fabian-michael** [melt-ui/melt-ui#390]
**Describe the bug**
Not really a bug but CSS libraries like daisyUI solely check if the disabled attribute is apparent in order to apply disabled styles so disabled="false" will enable the selector. According to the HTML specification "false" isn't a valid value for disabled either.

**Expected behavior**
No disabled attribute should be applied if disabled is false. 

[StackBlitz](https://stackblitz.com/edit/vitejs-vite-ab5wjy?file=src%2Flib%2FListbox.svelte)

**Comment by fabian-michael** [comment]
aria-disabled="true/false" could be applied instead and the disabled attribute only if disabled is true

**Comment by huntabyte** [comment]
Thanks for pointing this out! Definitely something we'll address!
