### ISSUE TITLE
🐛Bug: Multiselect doesn't show correct default labels and also have wrong typing on $option({ value...

### ISSUE THREAD

**Issue by mpiorowski** [melt-ui/melt-ui#392]
**Describe the bug**
When You set up multiselect types, by either `createSelect<string[], true>` or by providing `defaultValue: ["string1, "string2"]`, the option directive is not working properly. It starts to demand the string[] as value. Also the label for multiselect is showing incorect values.

```
use:melt={$option({ value: item, label: item })}
```
The item here is typed as `string[]`.

**To Reproduce**
1. Create 
```
    const {
        elements: { trigger, menu, option, label },
        states: { valueLabel, open, value },
        helpers: { isSelected },
    } = createSelect<string[], true>({
        forceVisible: true,
        multiple: true,
        defaultValue: ["string1", "string2"],
    });
```
2. Check for label and option directive.

**Expected behavior**
The label should show "string1, string2", and the option value key shoudl still expected only string.

**Screenshots**
![image](https://github.com/melt-ui/melt-ui/assets/26543876/6426c346-52c5-4fed-a017-2b3b511a0d13)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser chrome
 - MeltUI vesrion: 0.34.6

**Comment by wesharper** [comment]
Have you tried using `[{value: course1.id, label: course1.name}, {value: course2.id, label: course2.name}]` as the defaultValue?

**Comment by wesharper** [comment]
I think that what you want is `createSelect<string>`, as this is the expected `value` for each option. For instance, if the type param was set to `{name: string; age: number;}`, it would expect each option's value to conform to that interface.

**Comment by mpiorowski** [comment]
Maybe, i would like just to have a working types multiselect :) The easiest way to show this problem is to create a select without generic and try assign value. You will get a typescript error.
```
const {
        elements: { trigger, menu, option, label },
        states: { valueLabel, open, value },
        helpers: { isSelected },
    } = createSelect({
        forceVisible: true,
        multiple: true,
        defaultValue: ["string1", "string2"],
    });
```

**Comment by TGlide** [comment]
@mpiorowski The Select API has changed a bit. I'll be closing this issue as I believe the errors you mention are no longer present, but please let me know if that's not the case
