### ISSUE TITLE
🐛Bug: Combobox doesn't respect padding top/bottom for first and last item

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#397]
**Describe the bug**
When using the keyboard to navigate through the items, the first item's top and last item's bottom doesn't have enough separation between the magnum box and the container (you have to scroll a little bit more). Shouldn't this be the default behaviour?

**To Reproduce**
1. Go to [melt-ui.com/builders/combobox](https://www.melt-ui.com/docs/builders/combobox)
2. Click on the input
3. Press bottom arrow key

**Expected behavior**
It should respect the space. Like this: (I'm not sure if it's a CSS issue?)
![image](https://github.com/melt-ui/melt-ui/assets/105121122/c200f871-99f0-4ddd-94aa-21e89c3c1e54)
![image](https://github.com/melt-ui/melt-ui/assets/105121122/0468d7b0-20e7-40f6-a52f-b249c3f8eb50)

**Screenshots of the bug**
![image](https://github.com/melt-ui/melt-ui/assets/105121122/5b5500be-c9bd-41c8-b023-2585b2268ff4)
![image](https://github.com/melt-ui/melt-ui/assets/105121122/8a8271bb-ad0a-470f-a3e0-6b386c7833a0)

**Desktop (please complete the following information):**
 - OS: Windows 11 (64 bits)
 - Browser: Chrome
 - Version: 115.0.5790.171 (Build oficial) (64 bits)

**Comment by Tyneor** [comment]
In my opinion it is a CSS issue and I would not change the builder, maybe only the demo.
(You may have done it yourself in your example, but I didn't know so here it is:)
Adding a `scroll-my-2` class to the `<li>` here solves the issue: https://github.com/melt-ui/melt-ui/blob/95d193321bf940c4a66811f159efeb0dd092a622/src/docs/previews/combobox/main/tailwind/index.svelte#L133
(2 comes from the parent `<div>`)

**Comment by TGlide** [comment]
> In my opinion it is a CSS issue and I would not change the builder, maybe only the demo. (You may have done it yourself in your example, but I didn't know so here it is:) Adding a `scroll-my-2` class to the `<li>` here solves the issue:
> 
> https://github.com/melt-ui/melt-ui/blob/95d193321bf940c4a66811f159efeb0dd092a622/src/docs/previews/combobox/main/tailwind/index.svelte#L133
> 
> (2 comes from the parent `<div.py-2>`)

Oh I was about to do the hackiest JS solution ever. Thank god there are smarter people than me, thanks! 

Updated the docs. Will close this issue since yeah, it's a CSS issue!
