### ISSUE TITLE
🐛Bug: Context menu not closing when clicking on svg element

### ISSUE THREAD

**Issue by Theta-Dev** [melt-ui/melt-ui#405]
**Describe the bug**
If you click on a SVG element (for example an icon) outside of a context menu, the context menu does not close.

The issue lies in the `isHTMLElement` check in the `handleClickOutside` function:

https://github.com/melt-ui/melt-ui/blob/0ff5341f24fdbf0489017a0f33c86a8b750a6081/src/lib/builders/context-menu/create.ts#L111

I replaced this line with `if (!(target instanceof Element)) return;` and it works as expected.

**To Reproduce**
1. Open the context menu example page (https://www.melt-ui.com/docs/builders/context-menu)
2. Open the context menu
3. Click on a svg icon (for example a checkmark in the features section)
4. Context menu stays open

**Comment by huntabyte** [comment]
Ohh this is an interesting one! Thanks for catching it! We may have some other situations like that throughout the other menus as well!

**Comment by Theta-Dev** [comment]
Since the other menus handle outside clicks in a different way, the do not have this issue.
