### ISSUE TITLE
🐛Bug: Pressing "Enter" to submit form with `Select` in place opens the `Select` instead

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#410]
**Describe the bug**

As can be seen in the short video below, when clearly focusing other fields, `Select` is intercepting the "Enter" command to submit the form.

The problem is somewhere within `use:melt={$trigger}`, since the old behavior is restored when commenting it out temporarily.

**Expected behavior**
`Select` shouldn't intercept all "Enter" commands, ONLY when the button having `$trigger` is in focus.

**Screenshots**

Pasting contract address and pressing "Enter" used to submit the form and redirected to another page before melt-ui.
Now even when clearly focusing other fields, `Select` is intercepting the "Enter" command.

[Screencast from 2023-08-18 11-28-49.webm](https://github.com/melt-ui/melt-ui/assets/16797721/2f9be539-786a-4931-a71e-86ea4a999953)

**Comment by huntabyte** [comment]
Can you link a reproduction so we can investigate further? This definitely should be the case. From first glance, it appears like it may be an issue with the DOM structure of your elements, but want to confirm!

**Comment by mcmxcdev** [comment]
I was able to find out that this happens only when the `Select` is within a `form` HTML tag in the DOM.

**Comment by mcmxcdev** [comment]
Actually, I found another issue related to the existence of `Select` component on a page:

You can see in https://github.com/pheuter/select-open-bug-repro that the "First name" input has `tabindex="-1"` set, although that was never added by the dev. As soon as you comment/remove the code related to `Select`, `tabindex="-1"` will disappear from `<input />`. 

melt-ui shouldn't modify DOM nodes which it doesn't control.

**Comment by TGlide** [comment]
Thanks @pheuter for the repro and @mcmxcdev for the feedback. This is obviously a big issue, but should be easy to solve! I'll look into it as soon as I can.
