### ISSUE TITLE
🐛Bug: Combobox allows to select hidden items

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#414]
**Describe the bug**
When you write something in the input (e.g. 1984), you can still loop through the other options with the arrow keys (up/down).

**To Reproduce**
1. Go to https://www.melt-ui.com/docs/builders/combobox
2. Click on the input
3. Write `1984`
4. Press `up` or `down` key
5. Press `enter`
6. See the error

**Expected behavior**
Combobox shouldn't allow you to select items that are not displayed on screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Version [115.0.5790.171 (Build oficial) (64 bits)]

**Comment by TGlide** [comment]
Fixed!
