### ISSUE TITLE
🐛Bug: Multiple popovers open at the same time

### ISSUE THREAD

**Issue by lolcabanon** [melt-ui/melt-ui#416]
**Describe the bug**
Multiple Popover open at the same time, even if they are supposed to close when clicked outside.

**To Reproduce**

1. Open Stackblitz below
2. Click any row "actions" icon
3. Click another row "actions" icon while first still open
4. Now multiple popovers are open

Bonus : Click "close" button closes only one. Click inside one closes all others. Click outside closes all.

#367
> if your code isn't private you just do `stackblitz.com/github/lolcabanon/<YOUR_REPO_NAME>` and it will spin up a stackblitz with it!

It is, but here's a stripped out clone : https://stackblitz.com/github/lolcabanon/melt-ui_367

**I suspect the library `svelte-headless-table` which I used to build the table has a role to play, since it uses a lot of `e.preventDefault()` and `e.stopPropagation()`. I added some stuff to it recently, so I noticed it after my last comment on thread #367.**

**Expected behavior**
Other popover would close when another open (as it works in other places)

**Screenshots**
![image](https://github.com/melt-ui/melt-ui/assets/90099349/4221ad86-ab51-4340-93d8-48efe60f0f54)

**Desktop :**
 - OS: Manjaro Plasma
 - Browser : Chrome 116

**Additional context**
See https://github.com/melt-ui/melt-ui/issues/367#issuecomment-1671950804

**Comment by lolcabanon** [comment]
Hey @TGlide ! Thanks for looking into my issue!

Weirdly enough, the PR solved the issue on the demo I shared yesterday... But not in my main project (which is work for a client I cannot share as is) ^^ Just updated `pn i @melt-ui/svelte@latest @melt-ui/pp@latest` and I can still open many popovers...

Also tried it on the same page but outside the table (see https://stackblitz.com/github/lolcabanon/melt-ui_367 for context) and in another page without the table : it is also happening. (Firefox & Chrome)

Once again, I feel like I cannot provide reliable reproduction... This can stay closed for the moment, and I'll keep you updated if I find something useful!

**Comment by TGlide** [comment]
> Hey @TGlide ! Thanks for looking into my issue!
> 
> Weirdly enough, the PR solved the issue on the demo I shared yesterday... But not in my main project (which is work for a client I cannot share as is) ^^ Just updated `pn i @melt-ui/svelte@latest @melt-ui/pp@latest` and I can still open many popovers...
> 
> Also tried it on the same page but outside the table (see [stackblitz.com/github/lolcabanon/melt-ui_367](https://stackblitz.com/github/lolcabanon/melt-ui_367) for context) and in another page without the table : it is also happening. (Firefox & Chrome)
> 
> Once again, I feel like I cannot provide reliable reproduction... This can stay closed for the moment, and I'll keep you updated if I find something useful!

Oh, that's quite odd! Yes, if you manage to create a reproduction, please let me know!

**Comment by lolcabanon** [comment]
@TGlide Just letting you know 5d41f20 fixed this issue on my end! Thanks a lot :) You guys are unreal :astonished:
