### ISSUE TITLE
🌟Feature request: Provide an option to prevent combobox from removing values not found in the list

### ISSUE THREAD

**Issue by winston0410** [melt-ui/melt-ui#422]
**Is your feature request related to a problem? Please describe.**
At the moment combobox will remove user's input, when user inputted something not in the suggested list and focus else where. For example, if the item list has `foo`, `bar` and user inputted `hello`, the input will be cleared once user focus else where and the input received blur.

Keeping user's input is useful in some use case, for example a combobox that accept postcode. It is possible that user lives in a new area, and their postcode is not included in the database that stores postcode yet.

**Describe the solution you'd like**
Provide an option to disable the input clearing behavior

**Describe alternatives you've considered**
I don't believe there is other alternative that can solve this issue

**Additional context**

**Comment by TGlide** [comment]
I agree that'd be nice as an option. As a workaround, you can set the selected value whenever inputValue changes.

**Comment by TGlide** [comment]
Looking at the [Combobox examples](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/), it seems we shouldn't even be clearing the input! And it's easy enough to add the clear behaviour manually.

I think this should be the default.

**Comment by TGlide** [comment]
We now don't clear the input whenever something has not been found.
