### ISSUE TITLE
🌟Feature request: Allow Popover to be opened on hover too

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#424]
**Is your feature request related to a problem? Please describe.**

We have tooltips in our application which are triggered on hover (desktop) and on press (mobile).

Both `Tooltip` and `Popover` only serve one use case each, so my options are limited, and I would need to toggle between these components based on device in use.

It would be great to be able to use one component to serve both desktop and mobile users.

**Describe the solution you'd like**
https://mantine.dev/core/popover/#controlled solves this by offering custom `onMouseEnter` and `onMouseLeave` methods.

**Comment by TGlide** [comment]
Why not do `on:mouseenter={(e) => open.set(true)}`? We could even show an example of how to do it in the docs. 

**But**, my a11y advice is don't use tooltips for the same purpose as popovers. I'd have to know your specific use-case to advise more on that though.

**Comment by mcmxcdev** [comment]
Yeah, the docs could use more examples of what a component supports and doesn't, but I know you guys are super busy.

Then I either go down the `on:mouseenter` route or really toggle between both comps. Good to know about the a11y advice though, thanks!
