### ISSUE TITLE
📁Docs: Document differences between tooltip and link-preview

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#432]

**Comment by harshita1611** [comment]
Hey, I would like to work on this issue, can you please assign it to me

**Comment by TGlide** [comment]
@harshita1611 Done!

**Comment by adeleke5140** [comment]
@TGlide, since this issue hasn't been closed. Can I jump on it?

Where should this difference be located in the docs? I belive the Link Preview docs page is a great place to put it. After the accessibility section.
