### ISSUE TITLE
🐛Bug: Wrong props passed to radio input

### ISSUE THREAD

**Issue by Stefano-Labianca** [melt-ui/melt-ui#434]
**Describe the bug**
When I use the RadioGroup builder, `use:melt={$itemInput(id)}` doesn't pass the right props to the `<input>` element.

**To Reproduce**
1. Copy the example code from the [docs](https://www.melt-ui.com/docs/builders/radio-group)
2. When calling `createRadioGroup`, specify the `required` option
3. Add a custom `<input>` element. Like this `<input use:melt={$itemInput(id)}>`
4. Wrap the component with `<form>` element and submit it

**Expected behavior**
When the user does not select any element, the form should focus the required radio group, but the form gets submitted without any error.

**Screenshots**
![image](https://github.com/melt-ui/melt-ui/assets/58400415/af7e6066-20c6-4132-8885-dab65c4b7081)

![image](https://github.com/melt-ui/melt-ui/assets/58400415/2d28be23-add5-4d2d-94b2-b0fd912c304d)

**Desktop (please complete the following information):**
 - OS: Debian WSL
 - Browser chrome
 - Version @melt-ui/svelte 0.37.5

**Additional context**
The input element should probably be of type `radio` instead of `hidden` (At least I suppose so).

**Comment by TGlide** [comment]
@Stefano-Labianca Please fill the issue description

**Comment by Stefano-Labianca** [comment]
> @Stefano-Labianca Please fill the issue description

My bad, I miss-clicked

**Comment by huntabyte** [comment]
@TGlide was this issue solved with the PR you merged?

**Comment by TGlide** [comment]
> @TGlide was this issue solved with the PR you merged?

Yes! @Stefano-Labianca I'll be closing this, but if you still have issues, let us know.
