### ISSUE TITLE
🌟Feature request: Slider root should have `position: relative` by default.

### ISSUE THREAD

**Issue by f-elix** [melt-ui/melt-ui#438]
The Slider root element is required to have `position: relative` for the thumb to be correctly positioned. I believe this should be enforced through inline styles by the builder, or at the very least document that the root has to be relative.

**Comment by huntabyte** [comment]
We try our best not to apply styles, beyond `display: none` and a few other minor things, like the arrow size for floating UI builders, which can be controlled via an option. It's my understanding that the `style` tags we apply take precedence over other styles unless they are `!important`.

Are you sure the ***only*** way to position it properly is to use `position: relative`?

**Comment by f-elix** [comment]
Well the thumb is styled internally (via a style tag) as `position: absolute`, and I don't think the thumb should ever be positioned relatively to another element than the root, which is what will happen if the root doest not have `position: relative`.

**Comment by iolyd** [comment]
Without a warning in the docs, hard-setting `position: relative` on the root through inline styles could become a _minor_ headache for people working with `absolute` or `sticky` positioned sliders (although one can argument these are very rare use cases).

**Comment by TGlide** [comment]
> Without a warning in the docs, hard-setting `position: relative` on the root through inline styles could become a _minor_ headache for people working with `absolute` or `sticky` positioned sliders (although one can argument these are very rare use cases).

Agreed, one could use position absolute on the root slider, or another property, and thumb would still be absolute relative to the root. I'll be closing this issue
