### ISSUE TITLE
🌟Feature request: Another level of abstraction

### ISSUE THREAD

**Issue by kenbankspeng** [melt-ui/melt-ui#444]
**Is your feature request related to a problem? Please describe.**
If I am interpreting correctly, your example code seems to promote the concept that your builders are the fundamental unit of reuse. For example, Tabs shows a contrived example implementation of a set of tabs. If someone has a need for 5 different sets of tabs in their application, they could copy and paste the example 5 times, and make implementation specific modifications as needed.

**Describe the solution you'd like**
In my opinion, it would be more desirable that your example code for all components have 2 layers. The first being code that, using your builders, implements a generic reusable component (without application specific details). Then on top of that would be a contrived example of how to use the provided generic reusable component.

So if someone has a need for 5 different tab sets, there is only one generic reusable component which they copy from your example (possibly making modifications but possibly not), and 5 much smaller application specific calls to the generic component, which they would get from your second layer example and most certainly modify it for their own needs.

The end result is that melt-ui continues to only distribute the builder level code, but the fundamental unit of reuse is not your builders but a generic component which uses your builders which you provide via example code for.

**Comment by huntabyte** [comment]
Thanks for the issue! Closing this as this is already being tracked by #382
