### ISSUE TITLE
🐛Bug: Dialog cannot be closed programatically when `closeOnOutsideClick: false`

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#452]
**Describe the bug**
The dialog cannot be closed when setting `closeOnOutsideClick: false` (even after adding a `on:click={() => open.set(false)` or `use:melt={$close}` to the overlay.

**To Reproduce**

For the Select bug:
1. Go to https://www.sveltelab.dev/2kezbln53cyozjz
2. Set `closeOnOutsideClick: false` on line 16 inside `src/lib/Dialog.svelte`
3. Refresh the viewer panel inside sveltelab to allow the changes propagate to the iframe
![image](https://github.com/melt-ui/melt-ui/assets/105121122/bf015033-2a06-4c5d-a892-83cdbc49131a)
5. Click on 'Open Dialog' button
6. When the dialog is open, click on the Overlay or the 'Close Dialog' button
7. See error (dialog doesn't close)

**Expected behavior**
- Dialog _should_ close when setting `closeOnOutsideClick: false` and adding `on:click={() => open.set(false)` anywhere outside the dialog (e.g. overlay or outside button)

**Comment by huntabyte** [comment]
This works if you change `on:click` to `on:pointerdown`. I can try to investigate tomorrow but it's likely due to something intercepting the `click` events when the dialog is open.

**Comment by buhodev** [comment]
> This works if you change `on:click` to `on:pointerdown`. I can try to investigate tomorrow but it's likely due to something intercepting the `click` events when the dialog is open.

This works on desktop but not on mobile (somehow when you click on the close button, the event is passed to the open button after it's rendered conditionally and the dialog is triggered again, `on:pointerdown|self` doesn't work). What I attempted is `on:touchstart` and it worked (only on mobile, of course)

**Comment by AndreasHald** [comment]
@huntabyte any idea where the click events are being intercepted? I think this is causing my issue with having a close button outside of the dialog content.

**Comment by buhodev** [comment]
I discovered that it's better to use `on:pointerdown` WITHOUT rendering one or other button  using `{#if $open}` because it removes the buttons from the page and they cannot be referenced by melt anymore. Instead, I use:

```html
<button class:hidden={$open} on:pointerdown={() => open.set(true)}>Open</button>
<button class:hidden={!$open} on:pointerdown={() => open.set(false)}>Close</button>
```
