### ISSUE TITLE
🌟Feature request: export interface types

### ISSUE THREAD

**Issue by kenbankspeng** [melt-ui/melt-ui#456]
**Is your feature request related to a problem? Please describe.**
I use typescript. If I want to expose a builder option as a property of my component, as far as I can tell I must reconstruct the type that you internally have in $lib/internal/types.js.

For example, createTabs has an Orientation option. If I know I want "vertical" I can simply pass `createTabs({ orientation: "vertical" });`, but if I want to expose orientation as a property of my component, I do the following, even though you already have an Orientation type.

```
type MyReconstructedOrientation = "horizontal" | "vertical";
export let orientation:MyReconstructedOrientation = "horizontal";
... = createTabs({ orientation });
```

**Describe the solution you'd like**
I would like you to expose any types that are part of your interface.

**Comment by huntabyte** [comment]
Hey @kenbankspeng, you should be able to do something like:

```ts
import type { CreateTabsProps } from '@melt-ui/svelte'
export let orientation = CreateTabsProps["orientation"]
```

Let me know if this solves this issue!

**Comment by kenbankspeng** [comment]
Yes, thank you. I completely missed it.

`export let orientation: CreateTabsProps["orientation"]`
