### ISSUE TITLE
🌟Feature request: expose isInputValid to helpers in tags-input

### ISSUE THREAD

**Issue by Bubbet** [melt-ui/melt-ui#457]
**Is your feature request related to a problem? Please describe.**
Adding tags to tags-input is possible through the store, but I'd like to include the validation from isInputValid into my modification to the store. Currently there is no way to access that function from outside the builder.

**Describe the solution you'd like**
Have isInputValid, addTag, updateTag and removeTag exposed in helpers.

**Describe alternatives you've considered**
I could reimplement the validation done inside isInputValid myself, but thats a less than ideal solution.

**Comment by huntabyte** [comment]
Closing as added by #458
