### ISSUE TITLE
🌟Feature request: allow the option of disabling typeahead 

### ISSUE THREAD

**Issue by AndreasHald** [melt-ui/melt-ui#466]
**Is your feature request related to a problem? Please describe.**
We are attempting to use the dropdown menu for context relating to each table column in our app - for this case we use an input field to search for the facet value you would wish to filter the column to.

<img width="338" alt="Screenshot 2023-08-28 at 12 49 09" src="https://github.com/melt-ui/melt-ui/assets/8914722/7137db35-5446-4787-ac86-705f955b055b">

However because typeahead is always on if you happen to type something that is actuate in the menu, "sort" for example focus jumps from the input field to the corresponding button.

**Describe the solution you'd like**
I'd simply like an input for the dropDownMenu that let's me disable typeahead for cases such as this

**Describe alternatives you've considered**
Another alternative could be to ignore typeahead if an input has focus, but could be a little too "magic"

**Comment by huntabyte** [comment]
Closed by #467

**Comment by isamudev** [comment]
@huntabyte Could you do the same for the "Select" builder please?
