### ISSUE TITLE
🐛Bug: Dialog overlay doesn't stop touch events from firing elements behind it

### ISSUE THREAD

**Issue by GingerAdonis** [melt-ui/melt-ui#468]
**Describe the bug**
Dialog overlay doesn't stop touch events from firing other elements like it does with click events.

**To Reproduce**
Steps to reproduce the behaviour on desktop:
1. Go to: https://www.melt-ui.com/docs/builders/dialog
2. Scroll to 'Drawer' example component.
3. Enable responsive UI via dev tools. When clicking/touching any clickable element which is behind the overlay the event goes through.

**Expected behaviour**
Overlay stops touch events just like click events.

**Video**
https://github.com/melt-ui/melt-ui/assets/2751672/358bceea-ea04-4ed7-b7ba-18b1c81fa16b

**Desktop**
 - OS: Win11 x64
 - Browser: Chrome 116

**Smartphone**
 - OS: Android 13
 - Browser: Chrome 116

**Comment by GingerAdonis** [comment]
This problem also occurs for me on a Pixel 5 with Android 13 (Chrome 116).

Video:
https://github.com/melt-ui/melt-ui/assets/2751672/9f728566-46fc-4e61-8b49-378748246e3f

**Comment by alireza-ahmadi** [comment]
I experience the same issue on Safari (iOS 16.6). After digging a bit deeper, I found out using `transition:fade` causes this issue (if you remove the transition, everything works as expected).

As a temporarily workaround, you can break your overlay to two separate element and apply the background color and transition to the child element. In my case, it was something like this:

```svelte
<div
  {...$overlay}
  use:overlay
  class="fixed inset-0 z-50 bg-primary-950/50"
  transition:fade={{ duration: 250, easing: sineInOut }}
/>
```

turned into this:

```svelte
<div {...$overlay} use:overlay class="fixed inset-0 z-50">
  <div
    class="w-full h-full bg-primary-950/50"
    transition:fade={{ duration: 250, easing: sineInOut }}
  />
</div>
```

**Comment by GingerAdonis** [comment]
Can confirm the work-around 'fixes' the issue. Thank you @alireza-ahmadi

**Comment by evelinabe** [comment]
So we know the solution, it just needs a PR? I can do that :)

**Comment by evelinabe** [comment]
This workaround bugs me, because that extra div shows as an example in the code in the docs and does not seem to make sense. And since this is more of a workaround to fix a bug in Svelte my vote would be to not fix it, perhaps mentioning it as a suggestion somehow.
<img width="860" alt="Skärmavbild 2023-10-14 kl  22 28 18" src="https://github.com/melt-ui/melt-ui/assets/19805312/865dbbd6-de59-472b-96d9-3a2e9759cede">

**Comment by TGlide** [comment]
Another fix should be found that does not involve extra elements.

**Comment by evelinabe** [comment]
@TGlide See edit under image in my comment above

**Comment by evelinabe** [comment]
https://github.com/melt-ui/melt-ui/pull/630

**Comment by TGlide** [comment]
The issue was caused because a pointerdown event closed the overlay, and the pointerup triggered whatever element was beneath the overlay.

It should be fixed with the latest release.
