### ISSUE TITLE
🐛Bug: Slider step bug

### ISSUE THREAD

**Issue by abdel-17** [melt-ui/melt-ui#470]
**Describe the bug**
When the slider oversteps, it goes to the max value rather than stay in place.

As an example, this is what happens when `min = 0, max = 7, step = 6`.

https://github.com/melt-ui/melt-ui/assets/88583085/658eb1a7-97d9-4e72-bb14-36a22e0acead

**To Reproduce**
1. Go to https://stackblitz.com/edit/github-wgnbi5-ryrhwl?file=src%2Froutes%2F%2Bpage.svelte
2. Drag the slider all the way to the right (or use keyboard navigation)
3. See error

**Expected behavior**
The slider should stay in place at the value 6. This is the default HTML behavior and what `react-slider` does.
 
https://github.com/melt-ui/melt-ui/assets/88583085/51909cc2-e6cb-41d6-babe-84f7d78c93fe

**Comment by babakfp** [comment]
The expected behavior that you are describing sounds like a bug! If you have more values, they should be selectable. What is the point of having values that you can't select?

**Comment by abdel-17** [comment]
No, it’s not a bug. A slider with a step of 3 cannot advance from 6 to 7. It breaks intuition. Granted, it is dumb to make a slider with unreachable values, that’s on the user’s end, but that doesn’t mean the slider should behave incorrectly just to jump to the last value.

**Comment by babakfp** [comment]
Hmm,
Well, there can be an option for this. If this is going to be the default, then there should be a message on the docs explaining that! I don't really like the idea of making it the default behavior, because if the developer misses the message on the docs, then they can face issues, thinking that this is a bug...

**Comment by abdel-17** [comment]
I don’t mind clarifying in the docs, but I also think this should be the default behavior as it is the behavior of HTML’s range input and other libraries like react-slider.

**Comment by TGlide** [comment]
> I test it out and it doesn't behave the way that you say it does 🤔
> 
> [stackblitz.com/edit/web-platform-sab1rv?file=index.html](https://stackblitz.com/edit/web-platform-sab1rv?file=index.html)
> 
> Note: The native range input is kind of buggy because it completely ignores the value `9`!

You made the min be 1, so your example doesn't test this out (1 + 3 -> 4 + 3 -> 7 + 3 -> 10)

**Comment by babakfp** [comment]
Oooo, that's so funny 😅

> what @abdel-17 says is accurate.

yes yes, that's accurate 👍
