### ISSUE TITLE
🌟Feature request: Sheet Component like in Shadcn UI

### ISSUE THREAD

**Issue by PrabhuKiran8790** [melt-ui/melt-ui#477]

**Comment by buhodev** [comment]
Hi! You can use [shadcn-svelte](https://www.shadcn-svelte.com/docs/components/sheet) 😉

**Comment by NDOY3M4N** [comment]
You can achieve this using the [Dialog](https://www.melt-ui.com/docs/builders/dialog#drawer) builder. There's an example in the **Example section -> Drawer**

**Comment by TGlide** [comment]
Closing this for the reason@NDOY3M4N mentioned
