### ISSUE TITLE
🐛Bug: Clicking popover trigger when popover is open creates duplicate popover body elements.

### ISSUE THREAD

**Issue by twcus** [melt-ui/melt-ui#481]
**Describe the bug**
When a popover trigger is clicked while the popover is open, the popover does not close. Instead, the popover remains open, a duplicate instance of the popover body content is created and stacked directly on top of the original one.

Melt version 0.41.2
Preprocessor version 0.1.2

**To Reproduce**
1. Create a popover.
2. Click the trigger to open it.
3. Click the trigger again while the popover is still open.

REPL to reproduce: https://svelte.dev/repl/28a6698ead6d4cff98106f612592efa1?version=4.2.0

**Expected behavior**
I would expect the popover to close. Instead, it remains open, and a duplicate instance of the popover body is created.

**Screenshots*
<img width="1509" alt="Screenshot 2023-09-01 at 12 57 22 PM" src="https://github.com/melt-ui/melt-ui/assets/4195194/8fd42035-42b9-467f-b925-4babccc7a756">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 13.5

**Comment by TGlide** [comment]
Thank you for raising the issue! 

It seems this happens when using `{#if $open}` without a transition. This is obviously a bug, and I'll look into fixing it, but here are some workarounds while it's not fixed:
- If you don't need a transition, no need to use an if. The content will auto-hide accordingly.
- If you do need a transition, put it into the content element, then just make sure to set `forceVisible` to `true` in the options

**Comment by TGlide** [comment]
Repro of it working with transitions: https://svelte.dev/repl/614cf93347934228bf34c47866aa835c?version=4.2.0

**Comment by TGlide** [comment]
P.S. The preprocessor won't properly work on the Svelte REPL

**Comment by twcus** [comment]
> If you don't need a transition, no need to use an if. The content will auto-hide accordingly.

I tried this, but then the content is visible (and positioned incorrectly) when the component initially loads. 

<img width="1094" alt="Screenshot 2023-09-01 at 1 19 34 PM" src="https://github.com/melt-ui/melt-ui/assets/4195194/6977fd09-ce37-41dc-b6b8-f3c3d28da0ed">

**Comment by TGlide** [comment]
> > If you don't need a transition, no need to use an if. The content will auto-hide accordingly.
> 
> I tried this, but then the content is visible (and positioned incorrectly) when the component initially loads.
> <img alt="Screenshot 2023-09-01 at 1 28 08 PM" width="1088" src="https://user-images.githubusercontent.com/4195194/265100684-80b164ce-1406-48c6-97ac-5537cb98664c.png">
> 
> Clicking the trigger makes the popover appear as I'd expect.
> <img alt="Screenshot 2023-09-01 at 1 25 19 PM" width="796" src="https://user-images.githubusercontent.com/4195194/265100375-dd2ff03d-4b79-48a9-86eb-39ed0e474f94.png">
> 
> Clicking it again still does not close the popover, it remains open. Not sure if that is the expected behavior. Personally I would expect the trigger to toggle the state between open and closed, not keep it open.

Take a look at my repro. Using the preprocessor doesn't work on the REPL and causes issues.

**Comment by TGlide** [comment]
@twcus Releasing a new version that should fix it, let me know how it goes :)

**Comment by twcus** [comment]
@TGlide Seems to be working as expected now!

**Comment by TGlide** [comment]
> @TGlide Seems to be working as expected now!

Awesome! Closing :)
