### ISSUE TITLE
🐛Bug: Combobox submits form when presenting Enter

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#513]

**Comment by mcmxcdev** [comment]
Seems to be the same issue as was fixed for the `Select` in https://github.com/melt-ui/melt-ui/pull/442

I would recommend enabling https://sveltejs.github.io/eslint-plugin-svelte/rules/button-has-type, fixing all reported issues and then avoid problems like this once and for all.

**Comment by TGlide** [comment]
> Seems to be the same issue as was fixed for the `Select` in #442
> 
> I would recommend enabling [sveltejs.github.io/eslint-plugin-svelte/rules/button-has-type](https://sveltejs.github.io/eslint-plugin-svelte/rules/button-has-type), fixing all reported issues and then avoid problems like this once and for all.

In this case I believe it's different, as Combobox uses an input, not a button.
