### ISSUE TITLE
🌟Feature request: Better animation support

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#519]
Sometimes, users may want to implement more context-aware animations, e.g. knowing where a popover menu is placed. As an example, Radix exposes this via data-attributes and CSS vars: https://www.radix-ui.com/primitives/docs/components/popover#origin-aware-animations

**Comment by iolyd** [comment]
Other than not updating elements' data-attributes accordingly, builders currently do not reflect any automatic adjustments in the returned `positioning` store or any returned store. Is this also on the table? It feels a bit counter-intuitive to have an explicitly reactive value be returned but it not being representative of what is applied to the elements' styles.

**Comment by huntabyte** [comment]
> Other than not updating elements' data-attributes accordingly, builders currently do not reflect any automatic adjustments in the returned `positioning` store or any returned store. Is this also on the table? It feels a bit counter-intuitive to have an explicitly reactive value be returned but it not being representative of what is applied to the elements' styles.

This would certainly be cool. I agree it's a bit counter-intuitive that the updates only flow one direction.

I'm trying to imagine what that might look like - maybe observers that watch the element and update the store as it updates.

**Comment by iolyd** [comment]
I had in mind more something like hooking into floating-ui's state through some middleware or already available lifecycle callback. Just starting to look around, but maybe something here: https://github.com/melt-ui/melt-ui/blob/bb148fee4e263603b1679a48d65381018b3615fb/src/lib/internal/actions/floating/action.ts#L35-L147

**Comment by TGlide** [comment]
Allowing more fine-tuned control over floating UI, with middlewares or why not, is definitely something I want to implement :)

**Comment by iolyd** [comment]
> > Other than not updating elements' data-attributes accordingly, builders currently do not reflect any automatic adjustments in the returned `positioning` store or any returned store. Is this also on the table? It feels a bit counter-intuitive to have an explicitly reactive value be returned but it not being representative of what is applied to the elements' styles.
> 
> I'm confused what you mean by that? As the positioning store only reflects the configuration that is passed to floating-ui, rather than any actual values.

Sorry for the lack of clarity. But essentially I meant to say that when I first used builders with floating elements, I was expecting the `options.positioning` store would expose the (re-)computed [placement](https://floating-ui.com/docs/middleware#placement) rather than the initial placement.

**Comment by sebasmaltese** [comment]
https://github.com/melt-ui/melt-ui/pull/1082 just fixed this 🥳
