### ISSUE TITLE
⚙Tech Debt: Use generics in exported types

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#538]
Until now, Melt has relied on implicit return types for its exported types. 

e.g. 
```ts
export type Combobox = BuilderReturn<typeof createCombobox>;
export type ComboboxElements = Combobox['elements'];
export type ComboboxOptions = Combobox['options'];
export type ComboboxStates = Combobox['states'];
export type ComboboxHelpers = Combobox['helpers'];
```

This sometimes causes issues. In the case above, the return types will be overly broad and can cause TS errors. This is because Combobox uses generics in its markup. Instead, what we should do:

```ts
export type Combobox<
	Value = unknown,
	Multiple extends boolean = false,
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	S extends ComboboxSelected<Multiple, Value> = ComboboxSelected<Multiple, Value>
> = BuilderReturn<typeof createCombobox<Value, Multiple, S>>;
```

We should also do this for any builder that uses generics.

**Comment by huntabyte** [comment]
I think this is a good move and was actually struggling to get the right return type for the datepicker so will certainly make things better.

**Comment by buk0vec** [comment]
Hey all, opened a PR to fix this. Let me know if this is what you were thinking!
