### ISSUE TITLE
🐛Bug: Default values in Combobox multiple option are not set properly

### ISSUE THREAD

**Issue by rohanrajpal** [melt-ui/melt-ui#540]
**Describe the bug**
The default values in a combobox are set when it is in multiple option, but they are further added to the array when selected again

**To Reproduce**
1. Go to https://github.com/rohanrajpal/melt-combobox-multiple-repro
2. Start the server
3. The combobox would already have some values selected
4. Try to select a value from the combobox that is already selected
5. The same value is added again instead of remaining the same

**Expected behavior**
The $selected array should not have duplicate values when an already selected value is selected

**Screenshots**
Here is a screen recording: https://spur-uploads.s3.ap-south-1.amazonaws.com/360/melt%20issue%20reproduction.mov

Melt Version: 0.50

**Comment by TGlide** [comment]
Fixed by https://github.com/melt-ui/melt-ui/pull/588
