### ISSUE TITLE
🌟Feature request: Option to close other tooltips when opening a new one

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#543]

**Comment by huntabyte** [comment]
What are your initial thoughts on how this would be implemented?

**Comment by TGlide** [comment]
> What are your initial thoughts on how this would be implemented?

Maybe a context setter helper? There needs to be a way to group certain tooltips. 

Otherwise, we can make it a global behaviour. Have a global tooltip store to check if any tooltip is open, and close other ones.

**Comment by TGlide** [comment]
To add to this: A suggestion was made by a community member in Discord to add a `group` prop. Group would either be a `string`, or a `boolean`.

When it's a boolean, whenever a tooltip is opened, all other ones will close. When grouped, only the tooltips which have the same `group` key will be closed.
