### ISSUE TITLE
🐛Bug: Select element incorrect focus behavior

### ISSUE THREAD

**Issue by dcheglakov** [melt-ui/melt-ui#55]
**Describe the bug**
After the `Select menu` has been opened, navigation with the tab key is not possible.

**To Reproduce**
1. Go to [Stackblitz link](https://stackblitz.com/edit/stackblitz-starters-zpwu19?file=src%2Froutes%2Fdemos%2Fselect%2F%2Bpage.svelte)
2. Navigate to `/demos/select` | `src/routes/demos/select/+page.svelte`
3. Try to navigate between select and "Test focus" button with tab key
4. Open select menu and close it
5. Try to navigate with tab key again

**Expected behavior**
Navigation with tab key should work after opening the select menu

**Additional context**
Tried to wrap menu with `{#if open}...{/if}` not helped. A similar problem was with `dialog`, focus trap didn't work until I wrap the dialog with `{#if open}...{/if}` this was not presented in the documentation.

**Comment by TGlide** [comment]
Fixed by release [v0.10.3](https://github.com/melt-ui/melt-ui/releases/tag/v0.10.3)

**Comment by dcheglakov** [comment]
All good. Thanks
