### ISSUE TITLE
✨ Builder: Dropzone

### ISSUE THREAD

**Issue by multivac61** [melt-ui/melt-ui#553]
Thank you for an amazing library ✨

It would be amazing to have a built-in dropzone, e.g., https://react-dropzone.js.org/, into Melt.

**Comment by 0xHati** [comment]
See: https://github.com/melt-ui/melt-ui/pull/385 😃  
You can preview it here: https://melt-bvw92orwz-melt-ui.vercel.app/docs/builders/sortable

**Comment by multivac61** [comment]
Thank you for sharing @0xHati.

Will this allow me to drag files from the OS and drop them into the browser, e.g., when uploading them to a given site?

**Comment by 0xHati** [comment]
Pretty sure it will.

**Comment by TGlide** [comment]
@multivac61 @0xHati Sortable is quite a different component. It's meant to allow dragging elements in a list/grid.

A dropzone is to allow adding files to an input/form by drag n drop. 

I definitely think we should have this!

**Comment by 0xHati** [comment]
My bad, thanks for correcting 😄

**Comment by geerew** [comment]
Agreed. It was silly of me to have a feature in sortable called drop zone as it will confuse. I recommend we change it to ‘static’ zone to better reflect its intent. 

A drop zone builder would be an excellent addition

**Comment by waffleflopper** [comment]
> Agreed. It was silly of me to have a feature in sortable called drop zone as it will confuse. I recommend we change it to ‘static’ zone to better reflect its intent.
> 
> A drop zone builder would be an excellent addition

It may be something I take a stab at here soon.  I've built a couple of them before and it was actually a fun little project.  Making a builder for it would be an interesting challenge.
