### ISSUE TITLE
🌟Feature request: individual toast close delay 

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#554]
**Is your feature request related to a problem? Please describe.**
At the minute the close delay is set on the toaster and defaults to 5 seconds. It would be nice if I could override this when adding individual toasts.

for example, maybe I want ‘error’ toast to show for a bit longer and I want ’success’ toasts to show for less time

**Describe the solution you'd like**
An option to be passed on to the addToast helper

**Describe alternatives you've considered**
Currently the only way to do it is to have multiple createToast builders will different timeouts. It’s not optimal.

**Additional context**
N/a

**Comment by lolcabanon** [comment]
I would also like to see this implemented! :)

**Comment by lolcabanon** [comment]
Ok I just looked at the code and it is already possible!

It is not really documented, tho, but here you go :

```js

const {
  elements,
  helpers,
  states,
  actions
} = createToaster({
  closeDelay: 5000 // this is the default (in ms)
});

helpers.addToast({
	data: {
		title,
		description,
		type
	},
	closeDelay: 10000 // this overrides the default (10 seconds instead of 5)
});
```

**Comment by geerew** [comment]
Good work. In that case this is a docs issue..
