### ISSUE TITLE
⚙Tech Debt: Select logic refactor

### ISSUE THREAD

**Issue by wesharper** [melt-ui/melt-ui#555]
The current behavior of the select builder is to set the input's value (and `$selected`) to the value of the entire object passed to the `$option()` builder. However, this results in the hidden input (and `$selected`) getting a value of something like "[object Object], [object Object]". I've found that this is usually not what is desired in most forms. It's one thing if the end-user wants to pass an object to the option builder like so `$option({label: 'myThing', value: {foo: 'bar'}})`, but for the vast majority of forms it feels like the default value type should be `string | string[] | undefined`, this makes the API easier to deal with when pairing with a library like `svelte-superforms` because you don't have to do something like this if you want to make your own component to bind the form value to: `$: value = Array.isArray($selected) ? $selected.map({value} => value) : $selected.value;`.

The proposed change would be to set the input value AND the $selected value to be of type `OptionValue | OptionValue[] | undefined`.

**Comment by TGlide** [comment]
I'm confused. We don't use the value when choosing the selectedLabel: https://github.com/melt-ui/melt-ui/blob/1a4ab239844daf5899773cb24aeaf4459fb583f9/src/lib/builders/select/create.ts#L260

**Comment by wesharper** [comment]
I'm referencing this:
  
```typescript
  const setOption = (newOption: SelectOption<Value>) => {
    selected.update(($option) => {
      const $multiple = get(multiple);
      if ($multiple) {
        const optionArr = Array.isArray($option) ? $option : [];
        return toggle(newOption, optionArr) as S;
      }
      return newOption as S;
    });
  };
```

I think we should use `newOption.value` and `Array.isArray($option) : $option.map({value} => value): []`. What are your thoughts?

**Comment by wesharper** [comment]
Happy to elaborate more about what I'm seeing with my custom component, I think we might not be on the same page. I think the label logic is fine.

**Comment by TGlide** [comment]
> I'm referencing this:
> 
> ```ts
>   const setOption = (newOption: SelectOption<Value>) => {
>     selected.update(($option) => {
>       const $multiple = get(multiple);
>       if ($multiple) {
>         const optionArr = Array.isArray($option) ? $option : [];
>         return toggle(newOption, optionArr) as S;
>       }
>       return newOption as S;
>     });
>   };
> ```
> 
> I think we should use `newOption.value` and `Array.isArray($option) : $option.map({value} => value): []`. What are your thoughts?

If you use newOption.value, the selected will be wrong. Selected should contain both the value and the label.

**Comment by wesharper** [comment]
Is that just because we want deep equality? It would be useful to use if there were some way to get the current value of the input, not a complex object containing the value. Additionally, I think that setting the hidden input's value to something that's not _necessarily_ a complex object is useful.

**Comment by wesharper** [comment]
The current system is also cumbersome when having to set a default value, because it requires an array of objects with the following shape: `{label: string, value: T}`. So if you get data back from the database and want to auto-populate an edit form, for example, you have to go in and map all of your values to corresponding options in the `$option()` builder.

For instance, my database might return `['foo', 'bar', 'baz']`, but for a default value, I can't just pass that array to the builder directly. Instead, I'd need to use some logic that maps those values to something that is guaranteed to deep equal some object that's been passed to one of the options builders i.e. `[{label: 'Foo', value: 'foo'}//...]`.

**Comment by mcmxcdev** [comment]
After migrating from an old melt-ui version to the newest one which included these changes, I agree that it's a bit cumbersome to use. We also have to map different values to satisfy the shape of `{label: string, value: T}` which is overhead.

**Comment by TGlide** [comment]
The hiddenInput's value should be the same as selected.value actually.

The reason for this change, is so that you're forced to change selected.label whenever you change the value, instead of us trying to autoamatically detect the correct label, which involved an unrealiable solution.

That being said, I'm open to alternatives!

**Comment by wesharper** [comment]
So should `selected.value` be an array of values in the multi-select scenario?

**Comment by wesharper** [comment]
We're working on a slightly outdated version, but `$selected` may be an array in the multi select scenario. I feel like one alternative could just be to have both a `selected` and a `value`.

**Comment by TGlide** [comment]
> So should `selected.value` be an array of values in the multi-select scenario?

Nope, rather in multi select, selected is an array of `{ value: unknown; label: string; }`

**Comment by wesharper** [comment]
Yeah okay that's what we're observing. The multi-select is the biggest pain-point for us right now. I'll put some thought into alternatives

**Comment by TGlide** [comment]
> Yeah okay that's what we're observing. The multi-select is the biggest pain-point for us right now (we have a lot of big, hairy forms). I'll put some thought into alternatives

Alright! I'll be closing this for now. But if you do come into any alternatives, feel free to discuss here/elsewhere, and if there's a suitable alternative we can reopen the issue :)
