### ISSUE TITLE
🐛Bug: MeltUI Wrong type definition for Elements

### ISSUE THREAD

**Issue by cycle4passion** [melt-ui/melt-ui#558]
**Describe the bug**
TS errors in Svelte Template (HTML). I have submitted this [Issue #2163](https://github.com/sveltejs/language-tools/issues/2163) with Svelte for VSCode Extension, and they were able to localize it down to an incorrect MeltUI type definition for elements.

> "The library melt-ui/svelte has a wrong type definition that overrides the element type definition. Can you open an issue on their repo?"

**ATTEMPTED To Do minial Reproduction -- Did not show error**

1. `pnpm create svelte@latest meltui_repro`
2. Select `Skelton project`
3. Select `Yes, using TypeScript syntax`
5. Add `ESLint and Prettier`
6. `cd meltui_repro`
7. `pnpm add @melt-ui/svelte`
8. `pnpm install -D @melt-ui/pp svelte-sequential-preprocessor`
9. `pnpm i`
10. `code .`
11. Make sure "Svelte for VSCode" extension in installed/enabled.
12.  Update `svelte.config.js`

```js
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';
import { preprocessMeltUI } from '@melt-ui/pp';
import sequence from 'svelte-sequential-preprocessor';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: ['.svelte'],
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: sequence([
		vitePreprocess(),
		preprocessMeltUI() // add to the end!
	]),

	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter()
	}
};

export default config;
```
13. Changes src/+page.svelte

```js
<script lang="ts">
  function handleClick(e: MouseEvent, num: number) {
		console.log(e, num);
	}
</script>

<button type="button" on:click={(e) => handleClick(e, 1)}>Click me!</button>
```

14. Unfortunately did not reproduce.

**Expected behavior**
As there is no TS available in Svelte template, errors should not be showing here. I cannot correct them.

**Screenshots form a much larger project**
![image](https://github.com/melt-ui/melt-ui/assets/6192217/f3d74e67-e14f-4226-9b66-621acfde364e)

Public [github repo](https://github.com/cycle4passion/my-skeleton-app) 
Look in src/routes/exam/Exam.svelte to see the errors.

**Desktop (please complete the following information):**
- OS: macOS Ventura 13.4.1 (c)
- IDE: VSCode

**Additional context**

To reproduce using Stackblitz, use this [template](https://stackblitz.com/edit/melt-ui-playground) and modify the `src/routes/+page.svelte` file.

N/A - Stackblitz does not have Svelte for VSCode Extension.

**Comment by huntabyte** [comment]
Hey @cycle4passion, it seems like you're running a pretty old version of Melt UI - 0.24.1 (current is 0.50). The version you're running is before we were able to solve the issue with typing the element events using actions.

**Comment by huntabyte** [comment]
Going to close this issue, but feel free to reach out if you have any further issues after updating!
