### ISSUE TITLE
🐛Bug: Link Preview unexpected text highlight behaviour

### ISSUE THREAD

**Issue by thijserven** [melt-ui/melt-ui#562]
**Describe the bug**
When highlighting text inside of the Link Preview popup it doesn't close when the mouse leaves the popup (which is expected). But when I open the popup again by hovering over the button it doesn't close when the mouse leaves to popup (this now also happens when there is no text highlighted inside the popup).

**To Reproduce**
1. Go to: https://www.melt-ui.com/docs/builders/link-preview and mouse over the button with the ice cream icon, the popup appears (as it should).
2. If you highlight any text inside of the popup and move the mouse away from the popup, the popup won't close (as it should since there is text highlighted).
3. If you click outside of the popup in order to close it (since it would disable the text highlight, thus allowing the popup to close since there's no text highlighted anymore and the mouse is outside of the popup) the popup closes (as it should).
4. **Here is where the bug happens**: Now when you hover over the button with the ice cream icon again the popup appears (as it should). But when you move the mouse away from the popup (and remember I haven't highlighted any text inside the popup now) it won't close.

**Expected behavior**
The popup should close when the mouse leaves the popup if there is no text highlighted inside the popup.

**Comment by huntabyte** [comment]
Hey there @thijserven,

Can you possibly provide a video? I tried reproducing using your steps and this is the result I got:

https://github.com/melt-ui/melt-ui/assets/64506580/8bb7e69f-27c1-4040-99a1-88ad51233082

I don't think(?) we've added a fix yet for this, so just want to confirm your browser and such so I can get to the bottom of this, thanks!

**Comment by thijserven** [comment]
@huntabyte I just tried reproducing it again and I get the same result as you so it seems like it's fixed now. I'm using Chrome as browser. When I opened the issue I was also using Chrome and I haven't changed any browser settings since then.

**Comment by huntabyte** [comment]
Awesome to hear! We did clean up some things within our floating elements, so maybe that cleanup accidentally fixed the bug. Going to close this now but feel free to reopen if you notice it again and we'll take a closer look.

Thanks for taking the time to create the issue!
