### ISSUE TITLE
🌟Feature request: Tree View with multiselect

### ISSUE THREAD

**Issue by beholdr** [melt-ui/melt-ui#563]
**Is your feature request related to a problem? Please describe.**
Sometimes I need a tree with multi several items to be selected.

**Describe the solution you'd like**
Tree view with checkboxes to select multiple items.

**Additional context**
Some libraries even have combined widget: treeselect (multi select with tags + tree view). But main component here is tree view with multiselect.

**Comment by huntabyte** [comment]
Going to close this issue as not planned in the immediate future. If someone would like to take a shot at implementing this, we're more than happy to accept a PR, but the core team doesn't have the cycles for this at the moment.
