### ISSUE TITLE
📁Docs: `melt` action JSDoc is wrong

### ISSUE THREAD

**Issue by abdel-17** [melt-ui/melt-ui#568]
<img width="829" alt="Screenshot_2023-10-01_at_9 32 19_PM" src="https://github.com/melt-ui/melt-ui/assets/88583085/e9a18b46-1022-44eb-a255-0e95408de712">

neovim btw (sorry 😆)

The JSDoc for the melt action is returned from the `createBuilder` function. It should be imported from `@melt-ui/svelte`

```svelte
<script>
  import { createLabel, melt } from '@melt-ui/svelte';

  const { elements: { root } } = createLabel();
</script>

<label use:melt={$root} />
```

**Comment by HeetVekariya** [comment]
Hii @TGlide .
If i am not wrong, does this issue is for to change **```@melt-ui/pp```** from this below documentation only ans set it to **```@melt-ui/svelte```**.

```
/**
 * A special action for Melt UI's preprocessor `@melt-ui/pp`.
 *
 * @see https://www.melt-ui.com/docs/preprocessor
 *
 * @example
 * ```svelte
 * <script>
 * 	const { builder, melt } = createBuilder();
 * </script>
 *
 * <div use:melt={$builder} />
 * ```
 */
```

If i have interpreted it wrong, then can you please correct me :+1:

**Comment by huntabyte** [comment]
Hey @HeetVekariya, the JSdoc comment is from when we were entertaining the idea of returning the function from the builders but decided against it.

Feel free to update the JSDoc to reflect the accurate usage!

**Comment by HeetVekariya** [comment]
So i just have to change the **```@melt-ui/pp```** to **```@melt/svelte```**.

I am taking this much care because i don't want to make the irrelevant changes. 

Thank you assigning me.
