### ISSUE TITLE
✨ Builder: Scroll Area

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#573]

**Comment by huntabyte** [comment]
My best wishes to you on this one buddy!

**Comment by huntabyte** [comment]
> My best wishes to you on this one buddy!

Oh how the turns have tabled 😂

**Comment by shyakadavis** [comment]
![turntables](https://github.com/melt-ui/melt-ui/assets/87414827/eb750b1b-0f27-406b-a4b3-6712681f9445)
