### ISSUE TITLE
📁Docs: Convert all previews to CSS-only

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#574]
Currently, previews for builders can be found in `src/docs/previews/BUILDER_NAME/EXAMPLE_NAME/STYLING/*`, where `STYLING` is either `tailwind` or `css`. All builders have tailwind examples, but some are missing CSS examples.

I want to do two things. First, add CSS examples to all previews. Then, I want to remove the Tailwind examples to make it easier to maintain. I need help with the first task.

In the branch `css-examples`, I've already converted `previews/accordion/main` to CSS. You can see an example there, and you can preview the component by heading to the `Accordion` preview in the docs, when running it locally. Anytime you add a CSS example, that's what's going to show in the preview docs of the `css-examples` branch instead of the `tailwind` example. As such, all PRs related to this matter should be based on `css-examples`, and point to it.

A single PR should not convert all of the previews! Instead, 1-5 previews would be best 😄 

## Please mention which examples you'll be working on!

**Comment by Dhoni77** [comment]
Hi @TGlide  Can you provide some information on what is expected in this issue

**Comment by TGlide** [comment]
Hi @Dhoni77! I updated the description :)

**Comment by Sanchita1304** [comment]
HI, I would like to do this. Can you assign me.
And In this I just need to make css file for all previews and paste the tailwind to css and delete the tailwind file right?

**Comment by TGlide** [comment]
> HI, I would like to do this. Can you assign me. And In this I just need to make css file for all previews and paste the tailwind to css and delete the tailwind file right?

Hi! This issue doesn't need assigning as multiple people can tackle it, working with different examples. 

Please refer to the description! Copy-pasting the Tailwind to CSS won't be enough. You need to actually convert the code to not use tailwind anymore. And no need to delete the Tailwind file, I'll do that after all examples have CSS code.

**Comment by Sanchita1304** [comment]
Ok I will do this

**Comment by Amanjot-001** [comment]
@TGlide Hi, i am working on it but need a little help in how to set the preview in docs to be loaded from css file so that i can check  the changes. and also how can i create a test.

**Comment by henrikvilhelmberglund** [comment]
I'm a bit confused, wouldn't having examples using Tailwind be more maintainable? I guess it doesn't matter in the end as they are unstyled but having some nice examples in Tailwind format too would be pretty useful, even if it's an unofficial unmaintained thing.

Anyway, a tip which may or may not be useful to the people writing PRs for this, you can use the UnoCSS extension to select the strings of classes and get a list of how it would look in vanilla CSS, then select the text from the bottom and copy paste it. It might be less annoying than going utility by utility. The output CSS contains some CSS variables which will need to be replaced 
or renamed but it could be useful I think. You may need an empty `uno.config.js` in the project root for the extension to load.

<details>
  <summary>Example gif</summary>
  
![unocssextension](https://github.com/melt-ui/melt-ui/assets/110549389/e2988ebc-ba7f-4c63-b919-0144c3644286)
  
</details>

**Comment by TGlide** [comment]
> I'm a bit confused, wouldn't having examples using Tailwind be more maintainable?

The issue is having both Tailwind and CSS examples. Whenever I change one example, I then need to make sure that the other file matches it in style 1:1, which is time-consuming.

I wanted to make a script that automatically converted Tailwind to CSS, but in the end, I couldn't figure out an easy way and there are more important issues to deal with. So I chose to have CSS as a base, as anyone using Svelte can use it without installing any additional dependencies.

**Comment by NDOY3M4N** [comment]
Hi, I wanna work on these (if nobody started working on them).
- Dropdown Menu
- Link Preview
- Menubar
- Progress

**Comment by TGlide** [comment]
> Hi, I wanna work on these (if nobody started working on them).
> 
>     * Dropdown Menu
> 
>     * Link Preview
> 
>     * Menubar
> 
>     * Progress

Go for it!

**Comment by suliskh** [comment]
Can I help for these components?
- Pil Input
- Radio Group
- Toggle
- Toggle Group

**Comment by TGlide** [comment]
> Can I help for these components?
> 
>     * Pil Input
> 
>     * Radio Group
> 
>     * Toggle
> 
>     * Toggle Group
> 
>     * Label

Go for it!

**Comment by Bakemono-san** [comment]
Hi i would like to work on :

1. Slider
2. Tag input
3. Tree

**Comment by TGlide** [comment]
> Hi i would like to work on :
> 
>     1. Slider
> 
>     2. Tag input
> 
>     3. Tree

Go for it!

**Comment by donmccurdy** [comment]
Hi! Just a drive-by comment to say thank you so much for doing this. I've been getting started with Melt UI recently, and have personally found plain CSS examples (where they exist) immensely easier to read. I'm not using Tailwind, so only having to learn one new thing (Melt UI, not Tailwind) to understand the examples is much appreciated. ❤️

**Comment by Vikram-Hegde** [comment]
#626

**Comment by NDOY3M4N** [comment]
> #626 
> 
> Hello @TGlide, I have added css example to menubar component, feel free to suggest required changes

Hi @Vikram-Hegde, I was working on this component in #589 and it was recently merged. Maybe we should add a comment tracking every component and their progress.

**Comment by Vikram-Hegde** [comment]
@NDOY3M4N first of all, I apologize for not going through the open pull requests, my fault for not noticing it. And as you mentioned it would be great to have tracker for who's working on which component

**Comment by NDOY3M4N** [comment]
No worries, I hope you didn't spend too much time on it though. I think the Switch component still has no CSS example

**Comment by Vikram-Hegde** [comment]
> No worries, I hope you didn't spend too much time on it though. I think the Switch component still has no CSS example

Appreciate the heads up, will start working on the switch component 👍🏻

**Comment by Vikram-Hegde** [comment]
added CSS only preview for switch component #627

**Comment by moaqz** [comment]
Can I help with the component Toolbar and Tooltip?

**Comment by Bakemono-san** [comment]
Hi i would like to work on :

1. Select
2. Combo-box
3. Toast

**Comment by TGlide** [comment]
> Hi i would like to work on :
> 
>     1. Select
> 
>     2. Combo-box
> 
>     3. Toast

Go for it!

**Comment by Bakemono-san** [comment]
hi i would like to work on **table of content**

**Comment by babakfp** [comment]
Hi 👋

![image](https://github.com/melt-ui/melt-ui/assets/44144724/3798c1e9-5b30-48c6-ba5c-3b03dbb5fffc)

What do you think about having something like this instead?

https://play.tailwindcss.com

@TGlide

**Comment by TGlide** [comment]
> Hi 👋
> 
> ![image](https://github.com/melt-ui/melt-ui/assets/44144724/3798c1e9-5b30-48c6-ba5c-3b03dbb5fffc)
> 
> What do you think about having something like this instead?
> 
> https://play.tailwindcss.com
> 
> @TGlide 

That wouldn't solve much, as the appeal of the examples is also having an easy way to paste them into your code

**Comment by babakfp** [comment]
> > Hi 👋
> > ![image](https://user-images.githubusercontent.com/44144724/282588330-3798c1e9-5b30-48c6-ba5c-3b03dbb5fffc.png)
> > What do you think about having something like this instead?
> > https://play.tailwindcss.com
> > @TGlide
> 
> That wouldn't solve much, as the appeal of the examples is also having an easy way to paste them into your code

Hmm, I see.

Then, I think the best solution would be auto-generation.

> I wanted to make a script that automatically converted Tailwind to CSS, but in the end, I couldn't figure out an easy way

I wrote a simple code that takes the classes and adds them inside the style tag. I added a `data-class` attr to every element for the selector. This solution worked, however, this doesn't count in the dynamic classes, and also the `class:my-class={true}` feature, and much more I guess. I'm not very good with parsers and I didn't find the Svelte parser to be fun to work with. It seems like things need to be parsed, walked, and a new AST to be generated and then converted to code. The styles for TW classes need to be generated. The new code also needs to be formatted with Prettier, with the same config used in the project (there were some errors that prevented me from using it!).

Maybe it would be easier to auto-generate TW from CSS? I'm not sure.

I may try again later.

**Comment by TGlide** [comment]
> I wrote a simple code that takes the classes and adds them inside the style tag.

This is quite interesting! If you want, feel free to open up a draft PR, I can try and fiddle around with it for the edge cases you mentioned

**Comment by babakfp** [comment]
> > I wrote a simple code that takes the classes and adds them inside the style tag.
> 
> This is quite interesting! If you want, feel free to open up a draft PR, I can try and fiddle around with it for the edge cases you mentioned

https://github.com/melt-ui/melt-ui/pull/890
