### ISSUE TITLE
🐛Bug: Collapsible shifts in docs

### ISSUE THREAD

**Issue by Ajitesh72** [melt-ui/melt-ui#577]
UX could be improved for the collapsible,currently when you click on the ChevronsUpDown the new list gets aligned to the center of the page the rfore the X buttom shifts further up.A user would prefer the ChevronsUpDown to get replaced by X and the list items gets pushed further down the initial items

https://github.com/melt-ui/melt-ui/assets/95878363/2a3f9a43-f329-40a0-ba06-e97103e378bd

I'd like to take a shot at fixing this bug. Can you assign this issue to me?

**Comment by TGlide** [comment]
Go for it!
