### ISSUE TITLE
⚙Tech Debt: Return the `id` object from builders

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#585]
We're currently generating unique IDs that are applied to various elements within the builders.

While this is great, it makes it hard to bring in custom elements to use alongside builders. For example, if you wanted to use a label that wasn't provided by a builder, you'd need to know the ID of whatever element the label is `for`.

We already have the `ids` that we use internally inside of nice objects within the builders, so we should also return them for users to access/use outside as well.

It would be another property of the object returned from the builders, so to access them, you'd do something like this:

```ts
const { 
	ids: { ... },
	elements: { ... },
	// etc...
} = createWhatever()
``` 

With access, you can now select specific elements via custom actions, use custom labels, etc. The possibilities are truly endless for this revolutionary change!

**Comment by 0xHati** [comment]
I can do that.
