### ISSUE TITLE
🌟Feature request: Uncouple Floating UI reference element from actions

### ISSUE THREAD

**Issue by MarkMVMNT** [melt-ui/melt-ui#586]
**Is your feature request related to a problem? Please describe.**
When stitching together multiple builders, more control is needed over Floating UI, specifically around what gets used as the reference element.

**Describe the solution you'd like**
It'd be useful to be able to have more control over what gets used as the Floating UI reference element when using certain builders such as the combobox. 

This would enable composing multiple builders together to create more complex components. A good example is a tags input component that also has a suggestion list. This could be created using the Tags Input builder and Combobox builder if we could specify what the Combobox builder sends to Floating UI as the reference element so that the menu could take the width of the entire tags input rather than the combox input, which will be smaller in this case.

**Describe alternatives you've considered**
Without this, to build such a component you likely have to just use Floating UI manually and forgo using the Combobox builder.

**Additional context**
This feature should probably be tacked project wide and apply to any builder that uses Floating UI. Might relate to https://github.com/melt-ui/melt-ui/issues/546.

**Comment by huntabyte** [comment]
I think this is a good idea, and we could actually apply this alongside #546, since they're nothing dealing with the same thing.

My initial thoughts are adding a `floating` prop, which would be a floating UI config object, where you can configure it however you'd like. 

If the prop was set to `null`, we'd disable the floating UI behavior (#546). If not provided / `undefined`, we would do the same default behavior we do today.

**Comment by bkdiehl** [comment]
Additionally, specific to the combobox, it would be nice to have more control of the Floating UI open state. I'm using the combobox with the tags input, and I'd like the Floating UI to remain open after I've selected an item. This would allow me to select multiple items at once to be included as values in the tags input.

**Comment by TGlide** [comment]
> Additionally, specific to the combobox, it would be nice to have more control of the Floating UI open state. I'm using the combobox with the tags input, and I'd like the Floating UI to remain open after I've selected an item. This would allow me to select multiple items at once to be included as values in the tags input.

You can make it remain open currently. Most builders (if not all) with an `open` prop have an `onOpenChange` prop as well, that you can use to override default behaviour.

**Comment by huntabyte** [comment]
Closing this for now. This would require some significant planning/consideration with how we approach this that we don't quite have the time for at the moment.
