### ISSUE TITLE
⚙Tech Debt: Try out Storybook for thorough testing

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#594]
We already use Storybook, although it's not up-to-date at all. Storybook recently introduced some interesting updates, where it'll allow visual testing, and vitest integrations. 

Since we already have to create components for unit tests anyways, it could be a good idea instead to use Storybook for all our testing needs. That way we'd also do away with some file duplication as currently you have to create a story cmp and a test cmp. 

We need to try it out first to see if it works well for our use case, of course.

**Comment by huntabyte** [comment]
We tried and it works a little bit, but at the moment not worth the limited time we have to spend here - maybe for Svelte 5?
