### ISSUE TITLE
📁Docs: make importance of preprocessor setting more obvious in examples

### ISSUE THREAD

**Issue by harshbarger** [melt-ui/melt-ui#606]
First, thank you for what is already a great library.

But in writing my first component with it, I discovered a potential onboarding issue. After installing, I skipped straight to the example for the component I wanted to use and thought "Wow, that looks easy." And then proceeded to spin my wheels for quite some time trying to figure out why my radio buttons did absolutely nothing when I clicked them. 

_Eventually_ I figured out that I had to turn off the preprocessor switch in the lower left to see the code sample for my use case. To spare the next users who jump straight to the examples a similar frustration, perhaps something could be done to make the significance of that setting more prominent??

**Comment by TGlide** [comment]
Thank you for the kind words 🧡 

@AdrianGonz97 gave a good suggestion: Making the melt action throw an error when used in a non-pp environment, with a link to the PP docs. What do you think?

**Comment by TGlide** [comment]
> That would likely have helped. Though my ideal solution would probably be to place the preprocessor/non-preprocessor selector right next to the Tailwind/CSS selector. When I see a setting above the code like that, I know almost instantly that it affects that code sample. Had the selector been in that position, I might well have tried the right code the first time, and even if not, I probably would have found the issue quickly.

The issue is that we'd have to put the switch next to every code snippet, not only the component previews... But it's not a bad idea to be honest!
