### ISSUE TITLE
📁Docs: Wrong line highlighted

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#619]
In https://www.melt-ui.com/docs/transitions there's a mistake with the line highlighting ![image](https://github.com/melt-ui/melt-ui/assets/105121122/692a32cf-cacb-43f4-b54c-9b8ab5e42f4a)

**Comment by HeetVekariya** [comment]
@buhodev I would like work on this issue, can you please assign it to me

**Comment by buhodev** [comment]
> @buhodev I would like work on this issue, can you please assign it to me

Sorry, @HeetVekariya, I didn't see your comment and already fixed it in https://github.com/melt-ui/melt-ui/pull/620

**Comment by HeetVekariya** [comment]
No worries, go for it :+1:
