### ISSUE TITLE
🌟Feature request: [Radio Group] "Native" Handling for boolean values (and others?)

### ISSUE THREAD

**Issue by lolcabanon** [melt-ui/melt-ui#628]
**Is your feature request related to a problem? Please describe.**

Using **radio buttons** to answer simple **yes/no** questions seems to be a common pattern.

Neither native technologies (HTML, JS, CSS)[^1] or front-end frameworks (Svelte[^2][^3], React[^5]) seem to implement a de facto solution (except maybe Angular[^4]?).

[^1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/radio#value
[^2]: https://stackoverflow.com/questions/65841762/bind-radio-group-to-a-boolean-value-using-svelte
[^3]: https://github.com/sveltejs/svelte/issues/2300
[^4]: https://stackoverflow.com/questions/38097472/radio-button-for-boolean-property
[^5]: https://stackoverflow.com/questions/34547733/reactjs-how-to-use-boolean-values-in-radio-buttons

**Describe the solution you'd like**

Some native way to do this easily with MeltUI would be awesome! Like the `$item(value)` being able to accept `boolean` values? An option in the builder function?

I honestly don't know enough about MeltUI architecture (or even Svelte) to be able to suggest a well thought solution...

**Describe alternatives you've considered**

I've solved this problem using two-way binding, similarly to [this REPL](https://svelte.dev/repl/dc963bbead384b69aad17824149d6d27). It works great but took me a little bit to figure out how to make it work (take an initial value, bind the radios to it, update the value according to the radio group...), and also rely on dirty comparisons like `x == YesNo.YES` to convert from `string` to `boolean` (I guess this is the way, but handling this logic "inside" the builder in a standard way would probably minimize errors and duplication).

Knowing that in JS `Boolean("false")` and `!!"false"` are `true`, and `if ("false") console.log("true")` will indeed log "true", this is rather annoying...

(For context, I use an object `const YesNo = { YES: 'Yes', NO: 'No' }` and many other "enums" like this, and it works great for `string` based radio group, but in DB I have some `boolean` fields I now need to "translate" between `bool` and `string`. Not a big deal, but annoying enough to look for a better solution!)

**Additional context**

Just wanted to start the discussion on the subject! No pressure, you are already doing a wonderful piece of software as-is! :)

I also understand that there are some limitations to HTML form submission (`boolean` values cannot be sent except in JSON[^6]) so maybe that is out of scope for a front-end solution and should be handled on the server!

[^6]: https://stackoverflow.com/questions/33625248/formdata-sends-boolean-as-string-to-server
https://stackoverflow.com/questions/43471645/how-to-pass-boolean-values-between-php-html-forms-and-javascript

**Comment by huntabyte** [comment]
Closing as not planned for now.
