### ISSUE TITLE
🐛Bug: $selectedText value is null on initial render with controlled select

### ISSUE THREAD

**Issue by davidkupyn** [melt-ui/melt-ui#64]
**Describe the bug**
WIth controlled select component, $selectedText is null on initial render.

**To Reproduce**

**Expected behavior**
$selectedText should be set to label from the start, not null

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc
 - Version 0.107.1

Demo: [showcase](https://essence-ui.vercel.app/preview) -> "Form with Select component";
 [Component code](https://github.com/davidkupyn/ui/tree/main/src/lib/ui/select).
 
```svelte
<script lang="ts">
  import { Select, Option } from '$lib/ui/select';
  let customSelectValue = 'david';
</script>

<label class="input-label w-full" for="select1">
  Custom Select
  <Select
    placeholder="Select an option"
    id="select1"
    name="custom"
    bind:value={customSelectValue}
  >
    <Option value="witalina">Witalina</Option>
    <Option value="david">David</Option>
    <Option value="wiktor">Wiktor</Option>
    <Option value="gustaw">Gustaw</Option>
  </Select>
</label>
```

**Comment by geerew** [comment]
For me $selectedText is null by default, even when setting `selected` while creating the builder.

For example, the following should set `$selectedText` to `Apple` but will show `null`

```
const { selectedText, trigger, menu, option, isSelected } = createSelect({ selected: 'Apple' });
```


I guess this is a result of #44

**Comment by TGlide** [comment]
Solved. The only issue is it's not set in SSR. You can solve it by manually setting it after the creator function, although it's not ideal.
