### ISSUE TITLE
🐛Bug: $selectedLabel not working with initial value

### ISSUE THREAD

**Issue by leonardodipace** [melt-ui/melt-ui#669]
**Describe the bug**
When using `createSelect` with the `selected` property initialized to a value, the `$selectedLabel` store is not populated automatically with the corresponding label.

**To Reproduce**
1. Copy the code snippet below into a Svelte component:
``` svelte
<script lang="ts">
  import { createSelect, melt } from "@melt-ui/svelte"
  import { writable } from "svelte/store"

  const options = ["Caramel", "Chocolate", "Strawberry", "Cookies & Cream"]

  const {
    elements: { trigger, menu, option },
    states: { selectedLabel, open },
    helpers: { isSelected },
  } = createSelect({
    forceVisible: true,
    selected: writable({ value: "Strawberry" }),
    positioning: {
      placement: "bottom",
      fitViewport: true,
      sameWidth: true,
    },
  })
</script>

<div class="flex flex-col">
  <button class="text-left" use:melt={$trigger} aria-label="Food">
    {$selectedLabel || "Select a flavor"}
  </button>
  {#if $open}
    <div use:melt={$menu}>
      {#each options as item}
        <div
          class="flex items-center justify-between"
          use:melt={$option({ value: item, label: item })}
        >
          {item}
          {#if $isSelected(item)}
            <div>x</div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>
```
2. The placeholder text will still be visible instead of the selected label "Strawberry".
3. However, it works as expected when the label is specified manually in `selected`:
```
selected: writable({ value: "Strawberry", label: "Strawberry" }),
```

**Expected behavior**
The `$selectedLabel` store should be populated automatically with the corresponding label "Strawberry" without needing to specify it manually.

**Screenshots**
![image](https://github.com/melt-ui/melt-ui/assets/63299726/1e55c0eb-6604-48a2-915b-6093516c98bd)

**Desktop (please complete the following information):**
 - OS: Debian on WSL
 - Browser: Google Chrome 118.0.5993.90
 - Version: 0.56.0

**Comment by TGlide** [comment]
It is not populated because you did not pass in a `label` key to `selected`. This is intended behaviour
