### ISSUE TITLE
🐛Bug: Combobox cursor misbehaving with $open = false

### ISSUE THREAD

**Issue by Bubbet** [melt-ui/melt-ui#670]
**Describe the bug**
Combobox home and end keys not jumping the cursor when the dropdown isn't open.

**To Reproduce**
Make a combobox. Click it. Put some text in. Close the dropdown. Try to jump to the start or end of the text.

**Expected behavior**
Cursor jumps to the start or end.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.55.3

**Comment by huntabyte** [comment]
I'm not able to reproduce this issue with the latest combobox. Feel free to reopen with a reproduction if you can still reproduce!
