### ISSUE TITLE
🐛Bug:

### ISSUE THREAD

**Issue by jzillmann** [melt-ui/melt-ui#678]
**Describe the bug**
Using the `Popover` component. But instead of using a `trigger` element I'm calling `open.set(true)` (want the Popover on a long press). But the Popover isn't visible.

(everything work when using the trigger) 

**Expected behavior**
Was expecting the `open` writable to have an effect.

**Screenshots**
n/a

To reproduce using Stackblitz, use this [template](https://stackblitz.com/edit/melt-ui-playground) and modify the `src/routes/+page.svelte` file.

**Comment by TGlide** [comment]
Hi! Please send in a reproduction. Also, when creating issues, please put in a title.

Closing until these are addressed

**Comment by jzillmann** [comment]
Hey @TGlide added reproduction and title (sorry, for my sluggish late night action). Can you have a look ?

**Comment by TGlide** [comment]
You need a trigger for the popover content to anchor itself to.

**Comment by jzillmann** [comment]
Can I add a trigger but disable the `on:click` behavior ?

**Comment by jzillmann** [comment]
Ah figured it out. Just
```
{...$trigger}
```
instead of 
```
use:melt={$trigger}
```

Thanks for your help!

**Comment by TGlide** [comment]
> Ah figured it out. Just
> 
> ```
> {...$trigger}
> ```
> 
> instead of
> 
> ```
> use:melt={$trigger}
> ```
> 
> Thanks for your help!

That's not the recommended way. You can use change functions to cancel the click handler https://www.melt-ui.com/docs/controlled
