### ISSUE TITLE
🌟Feature request: Allow numeric type input for Pin Input

### ISSUE THREAD

**Issue by tobiassern** [melt-ui/melt-ui#681]
**Is your feature request related to a problem? Please describe.**
I use OTP codes (numerical) in my app, and for the input I use Pin Input. My OTP codes are always numerical. But when a user is going to write their OTP code on iOS safari (as an example). The default keyboard get switched back to (ABC keyboard), and the user needs to change keyboard type for each number they enter.

**Describe the solution you'd like**
In addition to type text and password, I would like to add type number to createPinInput()

```
const {
 elements: { root, input },
 states: { valueStr }
} = createPinInput({
 type: 'number',
 value
});
```

**Describe alternatives you've considered**
The alternatives I have considered is to code the pin input myself in order to solve this issue. I have also tried to do some wonky coding to override the type of each input in Pin Input.

**Additional context**
Here is a video of how it looks like trying to enter a purely numerical OTP with the pin input on iOS safari.
![CleanShot 2023-10-29 at 19 57 32](https://github.com/melt-ui/melt-ui/assets/7224143/749ba6f8-b54a-4b5d-b569-b06d609c71ed)

**Comment by augustoedt** [comment]
i had this same issue, then i made a temporary workaround

```typescript
	const {
		elements: { root, input },
		options: { type }
	} = createPinInput({
		defaultValue: []
	});

	// @ts-ignore
	$type = 'number';
```

now, it works fine on mobile

**Comment by tobiassern** [comment]
You're a wizzard @augustoedt 
Thanks!

**Comment by GimpMaster** [comment]
I was able to get this working by forcing number types I noticed I get this error.

```
Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
```

Would be cool for melt-ui to figure out a way to make it work for number inputs.
