### ISSUE TITLE
🐛Bug: Is disabling clicks (but not pointer events) outside dialogs the expected behavior?

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#682]
**Describe the bug**
On mobile, I have a BottomSheet component that opens behind the header, the component is using the dialog builder with `closeOnOutsideClick: false`. When it's open, I can't click any link on my header, *however* clicking on elements with `on:pointerup` works as expected.

**To Reproduce**
1. Go to https://www.sveltelab.dev/d4mrlmmcg8rsh8j
2. Click on 'Open dialog'
3. Click on 'pointerup works' (alert is fired)
4. Click on 'home' (nothing happens)
5. See error

**Expected behavior**
A system alert dialog should be fired when clicking on the 'home' link. Also, both links should work as well but they doesn't because page navigation might be handled by a click events under the hood and they're disabled when dialog is open.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 118.0.5993.118 (Official build) (64 bits)

**Additional context**
I realized about this when trying to click on the logo link to go home and it didn't do anything. 

- First workaround is to add `on:click|preventDefault` and `on:pointerup={() => goto('/')` to all links in the header, but this is not ideal.
- ~Second workaround is to set `closeOnOutsideClick: true` but I need to control click outside, so this is less ideal for me.~

Edit: it turns out that second workaround doesn't work

**Comment by eliasdefaria** [comment]
+1 to this. I'm trying to allow the user to download a file from within the modal. Doing so requires I create an invisible `<a>` tag and append it to the body. I've tried several workarounds, but most of them result in some rough side effects (i.e. the modal closing as it registers the click of the `a` as an outside click). The hardest one to debug was to try and understand why all the click events were just getting absorbed and the download wasn't being queued at all. Would love a simpler way to accomplish this. Open to brainstorming!

**Comment by TGlide** [comment]
Definitely a mistake on our end. Thanks for raising this issue, will look into it!
