### ISSUE TITLE
🐛Bug: Slider thumb loop issue

### ISSUE THREAD

**Issue by abdel-17** [melt-ui/melt-ui#684]
I have a `SliderThumb.svelte` component that just renders a single thumb. It receives the `thumb` builder through context, which is set in `Slider.svelte`.
```html
<!-- SliderThumb.svelte -->
<div use:melt={$thumb()}>
    <slot />
</div>
```
Inside `Slider.svelte`, I render each thumb in an each block.
```html
<!-- Slider.svelte -->
{#each $value as _}
    <SliderThumb />
{/each}
```
This causes some really strange layout shift. The reason is that, without JS, the thumbs are all positioned at the same place (the first thumb). Apparently, `$thumb()` just returns the same value for all thumbs.

If I move the each block inside the `<SliderThumb>` component itself, it works as expected.

Reproduction:
https://stackblitz.com/edit/github-y956xc?file=src%2Froutes%2F%2Bpage.svelte

**Comment by huntabyte** [comment]
Are you still able to reproduce this @abdel-17 ?

**Comment by abdel-17** [comment]
My ISP blocked Stackblitz for some reason and now I can’t access the reproduction. Can you send it to me on discord? A gh repo works too.

**Comment by huntabyte** [comment]
Is this resolved with the recent changes to the slider?
