### ISSUE TITLE
📁Docs: Add 'Skip to Main Content' Button

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#687]

**Comment by huntabyte** [comment]
This would be an accessibility enhancement to the docs that would allow users navigating via a screenreader to skip the main content rather than having to go through each of the menu items. It would be visually hidden.

**Comment by evelinabe** [comment]
Is this issue about documentation by adding a section in the docs or implementing a 'Skip to main content'-button?

**Comment by TGlide** [comment]
> Is this issue about documentation by adding a section in the docs or implementing a 'Skip to main content'-button?
> 
> @huntabyte @TGlide

The latter!
