### ISSUE TITLE
🌟Feature request: hiddenInput should fire input & change Events

### ISSUE THREAD

**Issue by LorisSigrist** [melt-ui/melt-ui#690]
**Describe the bug**
The idea behind `hiddenInput` components is to allow melt-ui components to be used in forms. However, they currently do not fire the same events a real input would. This is a problem because adding change event listeners to a `form` element directly is a very common pattern, which this breaks.

**To Reproduce**
Use melt-ui to create a form component with a hiddenInput, place it inside a `<form>` and add an input event listener to the form.
It will not fire.

**Expected behavior**
The hiddenInput should fire the same events that an equivalent native component would.

**Comment by TGlide** [comment]
Input elements don't trigger change events when its value changes programatically, that's just how JS works.

We couls dispatch custom events, but I can't think of an use case where that'd be better than using our onChange listeners we currently provide.

What is your use case? What do you need that onChange listeners do not provide you?

**Comment by LorisSigrist** [comment]
When you have very very deep forms, it's often convenient to do the form-validation by adding an `input` listener to the `<form>` element, using the `FormData` API to get the values & running the validation on those. Without Events this isn't possible. 

Dispatching Events programatically would be necessary to implement this. 
I would understand if this is out of scope for the moment. If that's the case adding a disclaimer in the docs about the lack of events would be welcome.

**Comment by TGlide** [comment]
@LorisSigrist I see what you mean. I'll change this to a feature request.
