### ISSUE TITLE
🌟Feature request: Allow non-floating mode for menu

### ISSUE THREAD

**Issue by silenceofthewans** [melt-ui/melt-ui#696]
**Is your feature request related to a problem? Please describe.**
I want my select and comboxes to float on desktops just like they do now but on mobile I want them to become a 'bottom-sheet'. Like following image: _(taken from this [issue](https://github.com/floating-ui/floating-ui/discussions/1937))_

| Desktop | Mobile |
| --- | --- |
| <img width="1357" alt="Popover on a wide viewport" src="https://user-images.githubusercontent.com/35560568/178956423-897c8db7-edcf-4f60-893d-c9f8f345e086.png"> | <img width="320" alt="Bottom sheet on a narrow viewport" src="https://user-images.githubusercontent.com/35560568/178956542-6ad08d45-fd5c-48cc-8c78-03ddd26ea04b.png"> |

**Describe the solution you'd like**
I use CSS grids for overlaying content as I find it more logical to work with so not using `position` on menu based on some option property should do the job. Then I can just place it however I want using CSS grid or if I want melt to handle it then I toggle that option property back on.

**Describe alternatives you've considered**
I tried using option element inside a nested dialog (my select is inside a dialog) but option element is coupled with menu as was mentioned in [this discord thread](https://discord.com/channels/1116682155809067049/1153965462200274945)

**Comment by TGlide** [comment]
You can disable floating UI on any builder. Just set position to null
