### ISSUE TITLE
🐛Bug: ERR_SSL_VERSION_OR_CIPHER_MISMATCH on www.melt-ui.com

### ISSUE THREAD

**Issue by tgorman31** [melt-ui/melt-ui#72]
# Bug Report - ERR_SSL_VERSION_OR_CIPHER_MISMATCH on www.melt-ui.com

## Description:
I am experiencing an issue while trying to access the website www.melt-ui.com on my work laptop. I receive the following error message:

This site can't provide a secure connection. [www.melt-ui.com](http://www.melt-ui.com/) uses an unsupported protocol. ERR_SSL_VERSION_OR_CIPHER_MISMATCH.

## Error Details:
The error suggests that the client (my work laptop) and the server (www.melt-ui.com) do not support a common SSL protocol version or cipher suite. This mismatch prevents a secure connection from being established.

## Steps to Reproduce:
1. Open a web browser on my work laptop.
2. Enter the URL www.melt-ui.com in the address bar.
3. Observe the error message: This site can't provide a secure connection. [www.melt-ui.com](http://www.melt-ui.com/) uses an unsupported protocol. ERR_SSL_VERSION_OR_CIPHER_MISMATCH.

## Expected Result:
I should be able to access www.melt-ui.com without encountering any SSL protocol or cipher suite issues.

## Actual Result:
The website www.melt-ui.com fails to establish a secure connection due to an unsupported SSL protocol version or cipher suite.

## Additional Information:
- I have attempted to access other websites without encountering similar SSL issues, indicating that the problem is specific to www.melt-ui.com.
- I have tried accessing www.melt-ui.com from a different device and network, and it works correctly, suggesting the issue may be isolated to my work laptop.
- I have cleared my browser cache and cookies but still face the same error.

## Computer Information:
- Operating System: Windows 10 Pro 21H2
- Web Browser: Google Chrome Version 114.0.5735.134 (Official Build) (64-bit), Microsoft Edge Version 114.0.1823.51 (Official build) (64-bit)

I thought I would highlight this happening but understand if this is not something you can fix on your end

Thanks

**Comment by TGlide** [comment]
Hey! Thank you for the issue. I have failed to reproduce it, unfortunately 🙁 Is it still happening?
