### ISSUE TITLE
🐛Bug: Listbox - when going from one listbox to another, scrollbar becomes visible

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#733]
**Describe the bug**

https://github.com/huntabyte/shadcn-svelte/assets/44144724/0d861df8-a260-4a3b-8b89-068dd77820f7

**Comment by huntabyte** [comment]
Any ideas for how we may tackle this @TGlide? I am more than happy to investigate/attempt to implement.

A wild idea I have but have yet to explore before hearing your thoughts is tracking the latest component actively removing the scroll, likely based on some internal `id` that represents the entire builder/component.

We could then update some dummy element to have that ID as part of a `data-attr,` when we close a piece, we check if that dummy element's ID matches the `scrollLockId` of the current builder, and if so, we re-add the scroll. Otherwise, we don't.

**Comment by TGlide** [comment]
I wonder if this was always the case? Or if it was implemented with the transition support. Tough nut to crack... I'll have to play around. I have loads of issues to address and want to work through them, so we no longer have 72 issues 😅 then I can play with this too. Ofc feel free to play around yourself too!

**Comment by huntabyte** [comment]
Actually realizing it now this is only happening with Listbox components.
