### ISSUE TITLE
🌟Feature request: Slider should dispatch an event when a value is committed

### ISSUE THREAD

**Issue by AdrianGonz97** [melt-ui/melt-ui#734]
**Is your feature request related to a problem? Please describe.**
It would be nice if the `Slider` builder dispatches an event (it could be called `m-change`) when the user releases control. Similarly to how the native slider works with the `on:change` event: 

https://svelte.dev/repl/5bbb8d49c61645db9e2881c940a04c09?version=4.2.3

Note how the event only fires when the user releases control, rather than every time `value` changes

**Comment by TGlide** [comment]
Wouldn't an `on:pointerup`listener resolve this?

**Comment by AdrianGonz97** [comment]
> Wouldn't an `on:pointerup`listener resolve this?

If only it was that easy 🥲

https://stackblitz.com/edit/melt-ui-playground-vrlk2y?file=src%2Froutes%2F%2Bpage.svelte

Note how `on:pointerup` only fires if the cursor is still hovering over the thumb element. If it's released outside of the element, nada. I also added the native `input` slider for quick comparisons.
