### ISSUE TITLE
📁Docs: missing elements in API reference for Context Menu

### ISSUE THREAD

**Issue by symsmith** [melt-ui/melt-ui#736]
The Context Menu `createContextMenu` [API Reference](https://www.melt-ui.com/docs/builders/context-menu#:~:text=to%20the%20trigger.-,Elements,-Open%20popover) is missing 3 elements (`item`, `group`, `groupLabel`)

**Comment by FarhanAliRaza** [comment]
hello can i help?

**Comment by huntabyte** [comment]
Of course! Just assigned it to you! @FarhanAliRaza

**Comment by FarhanAliRaza** [comment]
what is the descriptions of these elements?

**Comment by FarhanAliRaza** [comment]
The preview component should also have these elements implemented.   Should it? And if yes do we need to add it in another issue ? or can it be added in this issue? I implemented an example.
![image](https://github.com/melt-ui/melt-ui/assets/62690310/b90f20b1-d782-4fb3-95c3-228b37b3362a)

**Comment by FarhanAliRaza** [comment]
hello,  i opened a pr here https://github.com/melt-ui/melt-ui/pull/761
