### ISSUE TITLE
🐛Bug: Calendar: navigating with keyboard makes it possible to access disabled months

### ISSUE THREAD

**Issue by ollema** [melt-ui/melt-ui#745]
**Describe the bug**
Calendar: navigating with keyboard makes it possible to access disabled months

**To Reproduce**
1. Go to the [calendar documentation](https://www.melt-ui.com/docs/builders/calendar)
2. Click on Minimum & Maximum Values
3. In the example, focus any date. Notice how it's not possible to paginate to March since a max value is set.
4. Using the keyboard, press right arrow key until you do end up in March anyways, where there are no available dates to select.

**Expected behaviour**
Navigating to disabled months outside the min/max values should not be allowed

**Screenshots**
<img width="935" alt="Screenshot 2023-11-16 at 19 35 54 1" src="https://github.com/melt-ui/melt-ui/assets/31876997/5e746c87-bcb0-445a-934b-145950577e80">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome and Safari

**Comment by huntabyte** [comment]
Yep, definitely an issue! Will investigate as soon as I can, if anyone else wants to take a look feel free! We should also have a test case for this scenario.

**Comment by ollema** [comment]
I could try to work on this myself today! I'll let you know if I get stuck

**Comment by TGlide** [comment]
I'm not sure this is entirely unexpected to be honest. Otherwise people might think the calendar is broken, when in fact you only have some disabled dates.

**Comment by ollema** [comment]
I think it’s fair to assume that we should be consistent with the disabling of the next/prev month buttons though?

if those buttons are disabled, then it should also not be possible to circumvent this with the keyboard?

**Comment by ollema** [comment]
a keyboard user also gets stuck if this happens as there is no way to navigate back with the arrow keys

**Comment by TGlide** [comment]
Hmm true! That's fair.

**Comment by ollema** [comment]
using the prev/next buttons as a source of truth, it was easy to disable navigation with the keyboard.

however, I'm having some troubles with adding a test for this, see #748. maybe I'm missing something obvious
