### ISSUE TITLE
🐛Bug: Svelte 5 breaks component actions

### ISSUE THREAD

**Issue by proof-llc** [melt-ui/melt-ui#749]
**Describe the bug**
A toast has a button that cannot be pressed in Svelte 5.
https://github.com/proof-llc/melt-ui-demo/blob/main/src/routes/%2Bpage.svelte#L83

**To Reproduce**
1. Clone and run: https://github.com/proof-llc/melt-ui-demo
2. start toast and press TEST
3. it works
4. pnpm i -D svelte@next
5. now it doesn't work

**Comment by huntabyte** [comment]
We aren't accepting issues for Svelte 5 until it has reached a stable version
