### ISSUE TITLE
🌟Feature request: allow initial open section in Accordion

### ISSUE THREAD

**Issue by maxhoffmann** [melt-ui/melt-ui#75]
**Is your feature request related to a problem? Please describe.**
I’d like to define which section of the accordion should be open by default. I’m mostly interested in the `single` type, but to be consistent, this should also work for the `multiple` type.

**Describe the solution you'd like**
I would like to be able to pass an open argument to the items:

```js
<div class="accordion-item" {...$item({ value: 'item-3', open: true })}>Item 3</div>
```

**Describe alternatives you've considered**
Currently I’m setting the default value in the `createAccordion` function:

```js
createAccordion({
  value: initialValue,
})
```

**Comment by TGlide** [comment]
The alternative you've described is the correct way of doing, specially because of SSR concerns. What benefit would it bring for your use-cases to having open on the item attribute?

**Comment by maxhoffmann** [comment]
The benefit of declaratively deciding which element to open, doesn’t require know what the ID of the first item is beforehand. It decouples the open state from the content. One could for example add the open state to the first item without knowing what it is.

**Comment by TGlide** [comment]
> The benefit of declaratively deciding which element to open, doesn’t require know what the ID of the first item is beforehand. It decouples the open state from the content. One could for example add the open state to the first item without knowing what it is.

The item store function already requires an id on the same object where you proposed the open state. I can see the value if you're creating multiple components with the builder, e.g. <AccordionRoot /> and <AccordionItem />. But if you wanted to have an open prop on AccordionItem, you could:

```ts
// AccordionRoot
const {value, ...} = createAccordion()
setContext('accordion', {value})

// AccordionItem (type: single)
export let open = false;
export let id = false;

const {value} = getContext('accordion');
value.subscribe(v => open = v === id);
$: if (open) value.set(id)
```

While having it on the $item function creates a lot of complexity. What if open=true, but I change the value store directly? This creates multiple sources of truth with non-intuitive outcomes. With the example above, you'd be setting open only on AccordionItem and not on the root, which is fine.

**Comment by TGlide** [comment]
I'm closing this for the reasons I've mentioned above, but if anyone wants to discuss this further, please feel free, my mind can always be changed 🙂
