### ISSUE TITLE
📁Docs: Some Builders references props that are non-existant (Menubar with $item store and disabled prop)

### ISSUE THREAD

**Issue by omar-abdul** [melt-ui/melt-ui#758]
A small example is the  [menubar builder example in the docs](https://www.melt-ui.com/docs/builders/menubar#item) its item store states that there is a disabled prop, but trying to access the prop I keep getting errors, and when I call it regardless it get an error on the webpage, so I know its not there, even with the ts definition.

Solution:
Correct the docs 

thanks for all the work and effort

**Comment by TGlide** [comment]
@huntabyte I never realised item worked with disabling via data attributes. It's a bit weird, right? Maybe we should make it be both an object and a function? Or just a function with optional props

**Comment by huntabyte** [comment]
Yeah I think making it a function with optional props would be better.
