### ISSUE TITLE
🐛Bug: CLI uses yarn to install Melt

### ISSUE THREAD

**Issue by brittneypostma** [melt-ui/melt-ui#759]
**Describe the bug**
Regardless of the package manager, the CLI chooses yarn as the default package manager when installing melt.

**To Reproduce**
1. Create a svelte site `pnpm create svelte@latest`
2. cd in
3. add melt cli `pnpx @melt-ui/cli@latest init`
4. See yarn install and yarn.lock

**Expected behavior**
Use correct package manager, in my case pnpm.

**Screenshots**

![image](https://github.com/melt-ui/melt-ui/assets/45889730/36624ab7-97ea-4cac-9dab-c3b4683d6204)

**Comment by AdrianGonz97** [comment]
Thanks for raising the issue! 

This is a _bit_ to be expected as the we use `@antfu/ni` to determine the user's PM based on the lockfile type in the project. As this was a fresh project that didn't have a lockfile, it's _supposed_ to default to `npm`, which is very odd that it didn't for you 🤔

In any case, I pushed a patch to the CLI that should resolve this by defaulting to the current PM that's specified in the process's user-agent if a lockfile isn't present: https://github.com/melt-ui/cli/releases/tag/v0.0.5

Feel free to check it out and let us know if this resolves the issue!

**Comment by TGlide** [comment]
(Will be closing as solved, but let us know in case something's still amiss)
