### ISSUE TITLE
🐛Bug: clicking child of select menu trigger does not close menu

### ISSUE THREAD

**Issue by aaronjbecker** [melt-ui/melt-ui#798]
**Describe the bug**
If you have an icon or something as a child of a button that's a select menu trigger, you can click that child to open the menu, but not to close it.
[This StackBlitz](https://stackblitz.com/edit/melt-select-trigger-child-clicking?file=src%2Froutes%2F%2Bpage.svelte) provides an example with an exaggerated chevron icon and a formatted span; you can click on those elements to open the menu, but only a click on the trigger's own content will close the menu when it's open.

**To Reproduce**
See [this stackblitz](https://stackblitz.com/edit/melt-select-trigger-child-clicking?file=src%2Froutes%2F%2Bpage.svelte) for a reproduction

**Expected behavior**
Clicking on child elements in a select menu trigger while the menu is open should close the menu as if the trigger itself had been clicked.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome (also occurs on firefox and safari)

**Additional context**
Reactive `console.log` on the $open state shows that clicking the child element causes the menu to close and then open again rapidly (as if some event were being fired twice). So maybe this is related to click event bubbling?

**Comment by huntabyte** [comment]
Thanks for raising the issue and including a reproduction @aaronjbecker, much appreciated! I'm looking into this now, should be a simple fix!

**Comment by huntabyte** [comment]
Hey @aaronjbecker I knew this looked familiar, it was actually fixed in https://github.com/melt-ui/melt-ui/pull/735, if you update to the latest version of Melt UI this should be resolved!

**Comment by aaronjbecker** [comment]
@huntabyte glad this was already on your radar screen! I didn't check closed issues b/c I thought I was already running the latest version (according to package.json & package-lock.json)...
TBH not sure what's going on with dependencies in StackBlitz, deleting `node_modules/` and reloading the page seems to have fixed it in the linked reproduction on my end. Sorry for the confusion!

**Comment by huntabyte** [comment]
No worries!
