### ISSUE TITLE
🌟Feature request: children popovers

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#80]
**Is your feature request related to a problem? Please describe.**
It would be nice to have children popovers. That is to say, a parent popover can open a child popover.

I am trying to implement a table filter. The filter button opens a popover with a list of clickable item; id, name, etc. 

When an item in the parent popover is clicked, a child popover will open. This child popover allows the user to enter additional information, for example `is: id` or `is not: id`

at the moment this is not possible for 2 reasons

1. A button inside a popover can not trigger another popover. There is a workaround for this which is to manually manipulate the open store but this is hacky
2. If you use the hacky approach to open the second popover, when you click on the ‘child’ popover the ‘parent’ closes, which is bad ux

I know this breaks accessibility, or at the very least changes it but I do believe this is a worthwhile enhancement as there are many different scenarios it could be used. 

**Describe the solution you'd like**
It would be nice to open a parent popover and allow that parent popover to open 1 or more child popovers. 

When the child popover is closed (via a close button or outside click), it closes but the parent remains open. At this point the parent then closes normally via a close button or outside click

This is almost like a stack.

**Describe alternatives you've considered**
None. I would have to implement floating ui myself and go outside of this library

**Additional context**
None

**Comment by huntabyte** [comment]
I think this is a reasonable ask and something that ***should*** be possible as the use case you've presented isn't uncommon.

If we do it right it shouldn't break accessibility, as the dropdown menu has nested popovers that are perfectly accessible. Once I finish the dropdown menu I'll apply the same nested logic to the popover as I applied to it, so we can keep things consistent throughout (from an internal builder perspective).

@TGlide if you want to assign this to me I'll take it on soon!

**Comment by TGlide** [comment]
Sure, go for it @huntabyte!

I recently implemented nested dialogs. May be worth looking at the implementation!

**Comment by huntabyte** [comment]
Closed by: #234
