### ISSUE TITLE
🌟Feature request: Support label for Tags Input and PIN Input

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#829]
**Is your feature request related to a problem? Please describe.**
I noticed that "Tags Input" and "PIN Input" components don't use a label HTML tag in the examples.

We added a label to Tags Input on our end, but I think the example should cover this to avoid every developer having to add this themselves.

**Describe the solution you'd like**
Add support for label

**Describe alternatives you've considered**
Let the users do it themselves

**Comment by TGlide** [comment]
Right now our examples aren't super suitable for copy-pasting, I'd say. There are several improvements I want to do there, which hopefully will address stuff like this. 

For PIN Input, I'd say I prefer it this way, most of the time you won't use it with a label.
