### ISSUE TITLE
🐛Bug: Dialog component overlay does not block touch events for elements beneath it

### ISSUE THREAD

**Issue by luisfontes** [melt-ui/melt-ui#832]
**Describe the bug**
The dialog component overlay does not block touch events for elements beneath it.

**To Reproduce**
1. Go to [https://melt-ui.com/docs/builders/dialog](https://melt-ui.com/docs/builders/dialog)
2. Toggle device emulation on Chrome/Edge
3. Click on the "Open Dialog" button
4. Click on any bottom nav buttons under the overlay
5. Dialog closes and right after the action of the nav button is fired

**Expected behavior**
No event fired for anything beneath the dialog overlay.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 120.0.2210.77

**Comment by luisfontes** [comment]
This seems to have been fixed in one of the recent releases. Closing the issue.

**Comment by huntabyte** [comment]
I'm still able to reproduce this!

**Comment by huntabyte** [comment]
If you go to https://melt-ui.com/docs/builders/dialog (on a mobile device), open the dialog, and then click on the little toggle button behind the dialog, you'll see the event passes through to the toggle.

**Comment by luisfontes** [comment]
You're right, I forgot to toggle device emulation 🤦
