### ISSUE TITLE
🐛Bug: I am struggling with Type CreateComboboxProps

### ISSUE THREAD

**Issue by Ashaheen92** [melt-ui/melt-ui#835]
**Describe the bug**
Please confirm to me if it was intended or not 
export type CreateComboboxProps<Value, Multiple extends boolean = false, S extends ListboxSelected<Multiple, Value> = ListboxSelected<Multiple, Value>> = Omit<CreateListboxProps<Value, Multiple, S>, 'builder' | 'typeahead'>;

should Value = unknown?

**Comment by TGlide** [comment]
Yes, value is unknown if you don't pass it in.

Please do not open up a issue for doubts like these. You can instead open up a discussion in GitHub, or ask a question in support in our Discord server.
