### ISSUE TITLE
🌟Feature request: A way for the user to deselect a non-multiple Select

### ISSUE THREAD

**Issue by marcnajera** [melt-ui/melt-ui#840]
**Is your feature request related to a problem? Please describe.**
I haven't found a way for the final user to deselect an option from a Select. I think that if Select is not required, this should be available.

**Describe the solution you'd like**
Exactly the same behavior as when `multiple` is set to `true`. Clicking on a selected option unselects it, thus making `$selected === undefined`.

**Describe alternatives you've considered**
1. Manually inserting an option like `{label: placeholder, value: undefined}`, which displays the placeholder as an option in the menu.
2. Controlling the Select (although I haven't been able to make it work when selection happens via keyboard instead of click):
```
<div
  // This div represents an option
  {...$option({ value: item.value, label: item.label })}
  use:option

  // 👇 One way of achieving it 
  on:m-click={
    if (!multiple && $selected?.value == JSON.parse(e.target?.dataset.value)) {
      e.preventDefault()
      $selected = undefined
      $open = false
    }
  }
>{label}</div>
```

**Additional context**

**Comment by TGlide** [comment]
This is akin to how default selects work.. I'll look into it though, maybe we can add a prop.

**Comment by marcnajera** [comment]
Agree, and the default behavior could stay the same, it'd be nice though to be able to make it more user-friendly if choosing to "opt in" via a prop.

**Comment by TGlide** [comment]
Revisiting this, you can implement this behaviour currently. 

```html
<button on:m-click={(e) => {
		if ($isSelected(item)) {
			e.preventDefault();
			selected.set(undefined);
			open.set(false);
		}
	}}/>
```
