### ISSUE TITLE
🐛Bug: Date Field - Can't input times starting with 0

### ISSUE THREAD

**Issue by jannisrichter** [melt-ui/melt-ui#854]
**Describe the bug**
When using the date field it is currently not possible to input times that start with zeroes (e.g. 10:00). To input the minute part of the time you currently have to click a different number and then overwrite it with a zero.

**To Reproduce**
Create a date field with times. -> Input a time starting with zero.

**Expected behavior**
Be able to input zeros in the time field without having to input different numbers first.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.61.109

**Comment by sakibulalam** [comment]
I have created a PR for fixing this bug https://github.com/melt-ui/melt-ui/pull/893
