### ISSUE TITLE
🐛Bug: Dropdown Menu - Focus on trigger button after page load

### ISSUE THREAD

**Issue by azukiazusa1** [melt-ui/melt-ui#867]
**Describe the bug**
Immediately after the page loads, it automatically focuses on the element that opens and closes the Dropdown menu.

**To Reproduce**
1. Go to https://melt-ui.com/docs/builders/dropdown-menu

**Expected behavior**
It should not be in focus immediately after the page loads

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS Sonoma 14.2.1]
 - Browser [chrome]
 - Version [120.0.6099.129]

**Smartphone (please complete the following information):**

**Additional context**

To reproduce using SvelteLab, use the [Melt UI template](https://www.sveltelab.dev/?t=melt_ui) and modify the `src/routes/+page.svelte` file.

**Comment by shimkiv** [comment]
Just for the record.
This issue also caused the [Tasks example](https://www.shadcn-svelte.com/examples/tasks) filtering issue (when filtering input was loosing the focus after the data table update and action dropdown trigger was focused instead).
Filtering issue was introduced in [db84fdb](https://github.com/huntabyte/shadcn-svelte/commit/db84fdb1590a56e1fe7a12d39ee27023f4bdbd9a) and fixed  in [92ce738](https://github.com/huntabyte/shadcn-svelte/commit/92ce738b2400544c8f0647455f1dbf69eebc1582).

---

https://github.com/melt-ui/melt-ui/assets/4096154/aef0c43b-ebe7-4f79-b28a-066964071d69
