### ISSUE TITLE
🐛Bug: Checkbox example uses input inside button

### ISSUE THREAD

**Issue by amit13k** [melt-ui/melt-ui#878]
**Describe the bug**
While going through the documentation for checkbox https://melt-ui.com/docs/builders/checkbox, I found that an input tag is being used inside a button. This doesn't seem to be valid html. The latest svelte-5 release also fails to parse this code.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button suggests that button can not have interactive elements inside it.

**To Reproduce**
Check the documentation at https://melt-ui.com/docs/builders/checkbox

**Expected behavior**
An checkbox example which is valid html.

**Comment by amit13k** [comment]
Related Svelte-5 issue https://github.com/sveltejs/svelte/issues/10078

**Comment by huntabyte** [comment]
Closing this as it will no longer be an issue https://github.com/sveltejs/svelte/pull/10083
