### ISSUE TITLE
SvelteLab melt-ui template is not a great experience for submitting reproductions

### ISSUE THREAD

**Issue by jamesbirtles** [melt-ui/melt-ui#881]
Opening a recent bug report I was presented with the option to use sveltelab to create a reproduction using the melt-ui template (https://www.sveltelab.dev/?t=melt_ui). In theory this would make it nice and easy to create a reproduction, but in practise it has proved somewhat frustrating.

For starters, some dependencies are fairly out of date, e.g. prettier being pre v3. I got some errors around dependencies not being compatible etc. This includes melt-ui itself which is sat at version 0.30.

What I really wanted to be able to do is copy and paste an example from the melt-ui docs and then tweak it as necessary to show the bug in action. So I ended up needing to set up tailwind and copying over the custom tailwind config from the docs. Then I also needed to install lucide-svelte. 

This is all a lot of extra friction to creating a reproduction, putting me (and I'm sure others) off from doing it, which is unfortunate.

It would be great the have a template (the current one or otherwise) that you can copy any example from the docs into with zero other setup required to make adding a reproduction as easy as possible.

**Comment by huntabyte** [comment]
Thanks for the feedback @jamesbirtles, we'll update the template to include tailwind as well as our custom config!

**Comment by TGlide** [comment]
> Thanks for the feedback @jamesbirtles, we'll update the template to include tailwind as well as our custom config!

@huntabyte tbf I think that maybe we should go back to stackblitz. it doesn't make sense for SvelteLab's Melt template to include Tailwind. But we need to setup GH actions to automatically update versions in the stackblitz repo. I wonder how we could do it in an efficient manner though...

Maybe something that would copy all of the examples into the repo? Basically a streamlined version of the website, without docs or anything similar.

Stream of consciousness only, but it could work.

**Comment by huntabyte** [comment]
Once we get to 1.0+ pnpm should take care of installing the latest versions of everything, but yeah in the interim we need to come up with some sort of solution.

**Comment by TGlide** [comment]
> Once we get to 1.0+ pnpm should take care of installing the latest versions of everything, but yeah in the interim we need to come up with some sort of solution.

yeah, but would be nice to have our updated colors and what not there too.

**Comment by mcmxcdev** [comment]
For the sake of cross-linking, this is similar to https://github.com/melt-ui/melt-ui/discussions/814

**Comment by TGlide** [comment]
Solved, we updated the Stackblitz template, added a link to it (https://melt-ui.com/repro), and updated the bug report template. All thanks to @huntabyte!
