### ISSUE TITLE
🐛Bug: Tooltip with `disableHoverableContent: true` is glitchy

### ISSUE THREAD

**Issue by Xyzrr** [melt-ui/melt-ui#886]
**Describe the bug**
When a tooltip has `disableHoverableContent: true`, when your cursor approaches the trigger slowly from the left or the top, the tooltip flashes and disappears.

**To Reproduce**
1. Create a tooltip with these settings (the settings can vary but it's most evident like this):
```
createTooltip({
    positioning: {
      placement: `bottom`
    },
    openDelay: 0,
    closeDelay: 0,
    disableHoverableContent: true
  });
```
2. Move your cursor slowly onto the trigger, from the left edge or the top edge. The trigger can be any element; I've tested on both block and inline, `<a>` and `<div>`.
3. Observe the tooltip flicker, then remain closed even when the cursor is over the trigger.

**Expected behavior**
The tooltip should be open when the mouse is over the trigger, and closed when the mouse is not over the trigger.

**Screenshots**
https://github.com/melt-ui/melt-ui/assets/7032597/fb6209f0-204a-4e32-9a7d-6ec96edc8c73

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - Browser: Tested on both Chrome and Safari, latest

**Comment by huntabyte** [comment]
I see the behavior you're describing, but I'm not able to reproduce.

**Comment by Xyzrr** [comment]
Sure, I made a repro here:

https://www.sveltelab.dev/5d0ac2llmli1ccf?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte

A video of me triggering the flicker in that demo:

https://github.com/melt-ui/melt-ui/assets/7032597/8f44c85b-4966-4d7f-997b-92f54dda1aa7

**Comment by huntabyte** [comment]
I feel like one of your PRs will fix this issue @anatolzak, is that true?

**Comment by anatolzak** [comment]
@huntabyte my PRs don't fix this but I can confirm I am getting the same issue. I assume it's the `pointInPolygon` logic. I will look into this tomorrow
