### ISSUE TITLE
🌟Feature request: Allow passing default value/custom store for inputValue into combobox builder

### ISSUE THREAD

**Issue by winston0410** [melt-ui/melt-ui#887]
**Is your feature request related to a problem? Please describe.**
At the moment I struggle to change the initial value of an input field without user intervention. For example I am using combobox from melt-ui, and I am storing user's data in local storage. When the user visit the page, I want to update the `inputValue` based on the value I retrieve from local storage. At the moment it seems to be impossible

**Describe the solution you'd like**
Either the builder accept a new args, `defaultInputValue` for passing a string of default value, or the builder accept a user provider `inputValue` store in the args for `createCombobox` builder.

**Describe alternatives you've considered**
Passing the store from parent to combobox, and code the update logic there myself, but it is just very messy.

**Additional context**

**Comment by huntabyte** [comment]
This is currently possible, you can use the `defaultSelected` prop:

```ts
const {
		elements: { menu, input, option, label },
		states: { open, inputValue, touchedInput, selected },
		helpers: { isSelected },
	} = createCombobox<Manga>({
		forceVisible: true,
		defaultSelected: {
			value: userData.value,
			label: userData.label,
		},
});
```

If you need to update it after the page has loaded, you can use the store returned from the builder:

```ts
const {
		elements: { menu, input, option, label },
		states: { open, inputValue, touchedInput, selected },
		helpers: { isSelected },
	} = createCombobox<Manga>({
		forceVisible: true,
		defaultSelected: {
			value: userData.value,
			label: userData.label,
		},
});

// just an example, this could be trigger by a function call or whatever
$: if (userData) {
	selected.set({ value: userData.value, label: userData.label ?? userData.value })
}
```

**Comment by winston0410** [comment]
I see. Sorry for missing that option, thank you for your response.
