### ISSUE TITLE
Unable to select a date range of span 1 day from the picker

### ISSUE THREAD

**Issue by pepkin88** [melt-ui/melt-ui#898]
### Describe the bug

I can't find a way to select from the date range picker a range of span 1 day, i.e. where the starting and ending date is the same. That's because clicking on the same date for the ending date causes deselecting the starting date.
The only way I see how to set this, is to manually change the day number in the text fields above.

### Reproduction

1. Go to: https://melt-ui.com/docs/builders/date-range-picker
2. Try to select only a single day range:

https://github.com/melt-ui/melt-ui/assets/1028647/2d6fd549-855e-4ee5-b44b-d077f2c78ade

---

For comparison, similar component in shadcn/ui:

https://github.com/melt-ui/melt-ui/assets/1028647/d03fca0b-43db-4baa-b221-dc5cd2528338

### Logs

```bash
no logs
```

### System Info

```bash
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 155.55 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /usr/local/bin/node
    npm: 9.6.4 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Chrome Canary: 121.0.6125.0
    Safari: 16.6
    Safari Technology Preview: 17.4


There should be Vivaldi listed, but apparently it's not a browser, according to envinfo.
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Thanks for raising this issue!
