### ISSUE TITLE
🌟Feature request: Backspace Key Typeahead functionality

### ISSUE THREAD

**Issue by anatolzak** [melt-ui/melt-ui#901]
**Is your feature request related to a problem? Please describe.**
When using typeahead in (select, context menus, menubar, dropdown menus), currently there is no way to immediately reset the typed string. In native macOS typeahead components, you can press the backspace key to reset the typed string.

**Describe the solution you'd like**
Pressing the backspace key in typeahead components (select, context menus, menubar, dropdown menus) should reset the typed string.

**Additional context**
### Here is an example macOS menubar that demonstrates the use of the backspace key to reset the typeahead input.

https://github.com/radix-ui/primitives/assets/53095479/f024da3a-5d77-44bf-af7d-ed7c6cde7180

### And here is a Melt UI Menubar not responding to the backspace key

https://github.com/melt-ui/melt-ui/assets/53095479/2aa2bad3-a5ed-4f77-922a-bee4e6dedf28

**Comment by TGlide** [comment]
Closing in favor of #807, reasons listed [here](https://github.com/melt-ui/melt-ui/pull/902#issuecomment-1908023007)
