### ISSUE TITLE
🌟Feature request: Add flag for disable portal

### ISSUE THREAD

**Issue by Morbden** [melt-ui/melt-ui#903]
## The problem

I want create a menu in a absolute position element. I can't disable portal for this.

> **Example:**
> Before
> ![image](https://github.com/melt-ui/melt-ui/assets/5295072/15149b04-efa9-495b-bf83-1031058002c1)
> After
> ![image](https://github.com/melt-ui/melt-ui/assets/5295072/7f036f94-111c-4b49-8298-67439267a16a)

## The solution

Just solve the problem add a flag in function builder for disable portal.

```ts
const {
  elements: { menu, item }
} = createDropdownMenu({
  /**
   * @type { boolean }
   * @default false
   */
  disablePortal: true
})
```

**Comment by TGlide** [comment]
If you pass in `null` to the `portal` prop, it won't be portalled. Will update docs
