### ISSUE TITLE
🌟Feature request: Add open-on-hover functionality for Menu and Dropdown

### ISSUE THREAD

**Issue by Serpentarius13** [melt-ui/melt-ui#906]
**Is your feature request related to a problem? Please describe.**
I want to have on hover open functionality in my avatar-profile dropdown and I think it is tedious and unresponsive for users to click manually to open dropdown.

**Describe the solution you'd like**
Add openOnHover prop for dropdown and menu builders

**Describe alternatives you've considered**
Adding useHover hook and writing functionality myself

**Additional context**
I've implemented the feature in my fork, want to contribute

[screen-capture (1).webm](https://github.com/melt-ui/melt-ui/assets/112726943/d50ad47c-0135-4be5-8460-8bf26e6a5f11)

**Comment by huntabyte** [comment]
We make it possible for you to accomplish this yourself with a tiny amount of additional code, so it won't be exposed as a prop.

```svelte
<script>
	 const {
	    elements: { trigger, menu, item, separator, arrow },
	    states: { open },
	  } = createDropdownMenu();
</script>

<button use:melt={$trigger} on:pointerenter={() => open.set(true)}>
 	Hover me
</button>
<!-- ...  -->
```

**Comment by Serpentarius13** [comment]
> We make it possible for you to accomplish this yourself with a tiny amount of additional code, so it won't be exposed as a prop.
> 
> ```svelte
> <script>
> 	 const {
> 	    elements: { trigger, menu, item, separator, arrow },
> 	    states: { open },
> 	  } = createDropdownMenu();
> </script>
> 
> <button use:melt={$trigger} on:pointerenter={() => open.set(true)}>
>  	Hover me
> </button>
> 
> ```

Sorry for reopening, but with that use case I would need to write additional functionality for it to close automatically, when I get my mouse out instead of clicking. This is a bit more than just adding an event listener
