### ISSUE TITLE
`Select` doesn't allow `true` to be set for `multiple` prop

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#907]
### Describe the bug

We are updating our custom `Select` component to work with single and multiple selections.

When trying to provide `true` as default value for `multiple`, we encounter the following TS issue:

![Screenshot from 2024-01-12 10-55-06](https://github.com/melt-ui/melt-ui/assets/16797721/3eaef121-2320-4285-8718-7b951c6559ca)

`CreateSelectProps['multiple']` should allow `boolean | undefined` instead of `false | undefined`

### Reproduction

N/A

### System Info

```bash
N/A
```

### Severity

annoyance

**Comment by TGlide** [comment]
`CreateSelectProps` is a generic type. You can do `CreateSelectProps<any, boolean>` to "fix" this

**Comment by mcmxcdev** [comment]
I want to stick as closely to melt-ui types as possible, that's why I used `CreateSelectProps['multiple']` to not diverge when there are e.g. breaking changes.

Why don't you want to allow `boolean`?

**Comment by TGlide** [comment]
> I want to stick as closely to melt-ui types as possible, that's why I used `CreateSelectProps['multiple']` to not diverge when there are e.g. breaking changes.
> 
> Why don't you want to allow `boolean`?

Seems I was doing some things wrong honestly. Reopening this

**Comment by abdel-17** [comment]
> > I want to stick as closely to melt-ui types as possible, that's why I used `CreateSelectProps['multiple']` to not diverge when there are e.g. breaking changes.
> > Why don't you want to allow `boolean`?
> 
> Seems I was doing some things wrong honestly. Reopening this
> 
> EDIT: Not wrong exactly, but this is tricky. I believe we can improve nonetheless.

I noticed this issue a couple of days ago. The default generic type is set to `false`, but it should be `boolean` to correctly have `multiple: boolean` as the type.

**Comment by huntabyte** [comment]
I think we'd drastically reduce the complexity by splitting `Select` and `Multi-Select` into separate components given the number of issues and questions raised regarding types, etc.

**Comment by TGlide** [comment]
> I think we'd drastically reduce the complexity by splitting `Select` and `MultiSelect` into separate components given the number of issues and questions raised regarding types, etc.

This would screw up consistency or maintainability. We'd have to make accordion have a MultiAccordion, same for Combobox. We just need better docs and to improve types. It's doable
