### ISSUE TITLE
Svelte component libraries should use "NodeNext" for moduleResolution, not "bundler"

### ISSUE THREAD

**Issue by rsweeneydev** [melt-ui/melt-ui#909]
### Describe the bug

TypeScript types are not resolved property for a couple melt-ui components. This means intellisense doesn't work. For example, DatePicker component. This is caused by missing fully specified import specifiers. 

For example, in date-picker/index.ts 

```
export * from './create';
export * from './types';
```

Should be 

```
export * from './create.js';
export * from './types.js';
```

To prevent these types of issues, and support the widest range of uses, the authors of TypeScript and SvelteKit recommend that library authors *not* use moduleResolution "bundler". melt-ui is using moduleResolution "bundlers", so these issues are not detected at build and VS Code doesn't add file extensions when auto adding import statements.

Here are the relevant links to the documentation:

* [TypeScript guidance for library authors](https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-libraries)
* [SvelteKit guidance for component library authors](https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-libraries)

To fix this issue, melt-ui should add `"module": "NodeNext"` to it's tsconfig.json and remove `"moduleResolution": "bundler"`. ("module": "NodeNext" implies "moduleResolution": "NodeNext").

This will identify all the places in the library where import specifiers are invalid for modern node.

Note: I've filed a similar issue in bits-ui

### Reproduction

1. Create a new SvelteKit project
2. Set "module": "NodeNext" in tsconfig.json
3. Add melt-ui DatePicker
4. run svelte-check

Result:

```
/Users/robert/code/bits-ui/src/lib/bits/range-calendar/ctx.ts:1:15
Error: Module '"@melt-ui/svelte"' has no exported member 'CreateRangeCalendarProps'. 
import { type CreateRangeCalendarProps, createRangeCalendar } from "@melt-ui/svelte";
import { getContext, setContext } from "svelte";
```

### System Info

```bash
System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.62 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.12.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
    bun: 1.0.15 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.1.2
```

### Severity

annoyance

**Comment by rsweeneydev** [comment]
I'm working on a fix for this. 

I have submitted a [PR in bits-ui](https://github.com/huntabyte/bits-ui/pull/277) to fix the same issue.

**Comment by mcmxcdev** [comment]
I actually ran into this exact type issue with datepicker import before, looks like a legit import fix to make.
