### ISSUE TITLE
Dialog: closes when 1password icon is clicked

### ISSUE THREAD

**Issue by rafales** [melt-ui/melt-ui#917]
### Describe the bug

1Password - and other password managers - typically have a widget that shows up in password fields and which is appended to body.

This means that if I have a password field inside a modal and closeOnClickOutside is enabled - then clicking that widget will close the modal, which is not expected behavior.

This functionality should be probably implemented with "click on overlay" instead of catching clicks outside.

### Reproduction

https://www.sveltelab.dev/b7dn7stqhkjikd0

IT WILL NOT WORK IN SVELTELAB: In SvelteLab 1password shows button in top-level page, while app itself is rendered in an iframe. So contents of an iframe never see the click on 1password button.

In order to reproduce you need 1password installed, fork this locally, then try clicking on 1password's icon next to password button.

### System Info

```bash
-
```

### Severity

annoyance

**Comment by rafales** [comment]
https://github.com/melt-ui/melt-ui/assets/919812/2c007537-1645-4eb6-a354-7edd5f3d81c5

Here's a recording of the problem.

**Comment by moreorover** [comment]
Selecting text inside input field with your mouse and dragging it outside the input field closes the dialog as well. This is related I understand.
[dialog outside.webm](https://github.com/melt-ui/melt-ui/assets/17711314/384af6ff-f88d-4887-9015-66390057704e)

**Comment by huntabyte** [comment]
> Selecting text inside input field with your mouse and dragging it outside the input field closes the dialog as well. This is related I understand. [dialog outside.webm](https://github.com/melt-ui/melt-ui/assets/17711314/384af6ff-f88d-4887-9015-66390057704e)

This is actually unrelated to this specific issue.
