### ISSUE TITLE
Lots of ContextMenus causes a slow page navigation

### ISSUE THREAD

**Issue by williamoverton** [melt-ui/melt-ui#919]
### Describe the bug

I am using melt's context menus (Amazing btw!) but am suddenly suffering from slow paint times when I have lots of elements using context menus (~100). 
After debugging in the chrome profiler I found that every element adds a delay using setTimeout. (Images attached)

I think this relates to this line: https://github.com/melt-ui/melt-ui/blob/develop/src/lib/builders/menu/create.ts#L1053
It looks like svelte waits for each of these sleeps to complete sequentially when creating all the elements.

This is triggered by a single click event (the navigation) You can see lots of repeats in the first half, each one is a setTimeout
(if I comment out all the melt parts in the component the problem goes away)

![Screenshot_2024-01-15_at_16 46 31](https://github.com/melt-ui/melt-ui/assets/2838108/5652dc7f-c6ea-40c1-b24c-a220c132f864)
![Screenshot_2024-01-15_at_16 40 38](https://github.com/melt-ui/melt-ui/assets/2838108/7322052f-2313-4615-b92a-08f1b8c83030)
![Screenshot_2024-01-15_at_16 40 03](https://github.com/melt-ui/melt-ui/assets/2838108/7dc93d38-6ebd-45e8-8cc6-9cea4f7da52f)

### Reproduction

https://stackblitz.com/edit/meltui-context-slow-test?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 55.80 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.asdf/installs/nodejs/18.19.0/bin/node
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 16.1
  npmPackages:
    @melt-ui/svelte: ^0.70.0 => 0.70.0 
    @sveltejs/kit: ^1.27.6 => 1.27.6 
    svelte: ^4.0.5 => 4.2.7
```

### Severity

blocking all usage of Melt UI

**Comment by huntabyte** [comment]
Thanks for raising the issue and providing such detail! I'm investigating this now!
