### ISSUE TITLE
⚙Tech Debt: Define a consistent `data-melt-[name]` convention/standard

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#92]
The project is still early in development & we're moving fast, but I think defining a convention/standard for the `data-melt-part` attributes will not only improve our lives as maintainers/contributors but also those who wish to style their components using those attributes.

I know that we use the `data-melt-part` attributes internally to handle certain logic/functionality, but it'd be nice to advertise these to the users as well. I think [Zag](https://zagjs.com/overview/styling) handles this beautifully.

Ideally, we'd add that attribute to all the elements that we provide attributes/actions. Something that might come up that I've also considered is overlap. For example, if two different components within the same page have `data-melt-part="root"`. I think if you're running into that issue, it's probably best to break the component off into its own file and use scoped styles. The alternative is of course using some sort of prefix, which could get messy and makes the API less predictable.

This also brings to light that we're being a bit inconsistent with the names we're exposing. I understand it's nice to expose just `slider` or `progress`, but if we're going to do that for a few then we should do it for all or none. If the user wants to rename `root` to `slider`, they are capable of doing so themselves. It feels odd to have some of the "wrappers" named as their component name, and others just "root".

**Comment by huntabyte** [comment]
After thinking this through a bit more and digging into multiple different components, I think it makes more sense to replace `root` with the top-level component name wherever we're having to use `root`.

For example, if we look at the `Accordion` component, rather than have `root` be the wrapper, doesn't `accordion` make more sense?

There will of course still be conflicts between the different components for things like `item`, `trigger`, etc., but as mentioned previously it'll be up to the consumer to rename those if they're using multiple within the same component/page.

**Comment by TGlide** [comment]
I agree with everything here. We *should* expose data-melt-part for all components, and maybe we *should* change root to be the component name.

Leaving this open so we can work on it!

**Comment by huntabyte** [comment]
Okay after shipping some more complex components - I think a better approach is similar to how Radix handles it compared to Zag. Prevents overlap/conflicts and makes life a bit easier within the builders themselves.

### Accordion
Root: `data-melt-accordion`
List: `data-melt-accordion-list`
Trigger: `data-melt-accordion-list`

It might seem like a lot, but it's more explicit and improves the follow flow I find myself needing internally:


```ts

  const isAccordionTrigger = e.target.hasAttribute('[data-melt-accordion-trigger]')

```

vs something like:

```
const isAccordionTrigger = e.target.getAttribute('[data-melt-part]') === 'trigger'

```

Of course these are simplified examples but I've used both and the former is by far superior, especially when you're dealing with scoped elements / builders.

**Comment by huntabyte** [comment]
This is what I'm proposing after working with a few builders/components that have tons of "parts", and also after considering the global styling option mentioned in my previous comment.

If we named all the triggers "trigger", then the styles would have to be scoped to that specific component, which could be a pain for some users. Instead, if each element has it's own name, then styles can be set globally using those selectors.

I'd love to hear thoughts on this from the community, if there's no rebuttle, I'll open a PR to make all these changes :)

<details>
<summary> <b>Accordion</b> </summary>

- root ➡️ accordion: `[data-melt-accordion]`
- content - `[data-melt-accordion-content]`
- trigger - `[data-melt-accordion-trigger]`
- item - `[data-melt-accordion-item]`

</details>

<details>
<summary> <b>Avatar</b> </summary>

- image ➡️ avatar - `[data-melt-avatar]`
- fallback - `[data-melt-avatar-fallback]`

</details>

<details>
<summary> <b>Checkbox</b> </summary>

- root ➡️ checkbox - `[data-melt-checkbox]`
- input - `[data-melt-checkbox-input]`

</details>

<details>
<summary> <b>Collapsible</b> </summary>

- root ➡️ collapsible - `[data-melt-collapsible]`
- content - `[data-melt-collapsible-content]`
- trigger - `[data-melt-collapsible-trigger]`

</details>

<details>
<summary> <b>Context Menu</b> </summary>

- menu - `[data-melt-context-menu]`
- trigger - `[data-melt-context-menu-trigger]`
- item - `[data-melt-context-menu-item]`
- checkboxItem - `[data-melt-context-menu-checkbox-item]`
- separator - `[data-melt-context-menu-separator]`
- submenu - `[data-melt-context-menu-submenu]`
- subTrigger - `[data-melt-context-menu-subtrigger]`
- radioGroup - `[data-melt-context-menu-radio-group]`
- radioItem - `[data-melt-context-menu-radio-item]`

</details>

<details>
<summary> <b>Dialog</b> </summary>

- trigger - `[data-melt-dialog-trigger]`
- overlay - `[data-melt-dialog-overlay]`
- content - `[data-melt-dialog-content]`
- title - `[data-melt-dialog-title]`
- description - `[data-melt-dialog-description]`
- close - `[data-melt-dialog-close]`

</details>
<details>
<summary> <b>Dropdown Menu</b> </summary>

- menu - `[data-melt-dropdown-menu]`
- trigger - `[data-melt-dropdown-menu-trigger]`
- item - `[data-melt-dropdown-menu-item]`
- checkboxItem - `[data-melt-dropdown-menu-checkbox-item]`
- arrow - `[data-melt-dropdown-menu-arrow]`
- separator - `[data-melt-dropdown-menu-separator]`
- submenu - `[data-melt-dropdown-menu-submenu]`
- subTrigger - `[data-melt-dropdown-menu-subtrigger]`
- radioGroup - `[data-melt-dropdown-menu-radio-group]`
- radioItem - `[data-melt-dropdown-menu-radio-item]`

</details>
<details>
<summary> <b>Label</b> </summary>

- root ➡️ label - `[data-melt-label]`

</details>
<details>
<summary> <b>Menubar</b> </summary>

- menubar - `[data-melt-menubar]`
- menu - `[data-melt-menubar-menu]`
- trigger - `[data-melt-menubar-trigger]`
- item - `[data-melt-menubar-item]`
- checkboxItem - `[data-melt-menubar-checkbox-item]`
- arrow - `[data-melt-menubar-arrow]`
- separator - `[data-melt-menubar-separator]`
- submenu - `[data-melt-menubar-submenu]`
- subTrigger - `[data-melt-menubar-subtrigger]`
- radioGroup - `[data-melt-menubar-radio-group]`
- radioItem - `[data-melt-menubar-radio-item]`

</details>

<details>
<summary> <b>Pagination</b> </summary>

- root ➡️ pagination - `[data-melt-pagination]`
- pageTrigger - `[data-melt-pagination-page-trigger]`
- prevButton ➡️ prevTrigger - `[data-melt-pagination-prev-trigger]`
- nextButton ➡️ nextTrigger - `[data-melt-pagination-next-trigger]`
</details>

<details>
<summary> <b>Popover</b> </summary>

- content - `[data-melt-popover-content]`
- trigger - `[data-melt-popover-trigger]`
- arrow - `[data-melt-popover-arrow]`
- close - `[data-melt-popover-close]`

</details>

<details>
<summary> <b>Progress</b> </summary>

- progress - `[data-melt-progress]`

</details>

<details>
<summary> <b>Radio Group</b> </summary>

- root ➡️ radioGroup - `[data-melt-radio-group]`
- item ➡️ radioItem - `[data-melt-radio-item]`

</details>

<details>
<summary> <b>Select</b> </summary>

- root ➡️ radioGroup - `[data-melt-radio-group]`
- item ➡️ radioItem - `[data-melt-radio-item]`

</details>

<details>
<summary> <b>Separator</b> </summary>

- root ➡️ separator - `[data-melt-separator]`

</details>

<details>
<summary> <b>Slider</b> </summary>

- root ➡️ slider - `[data-melt-slider]`
- range - `[data-melt-slider-range]`
- thumb - `[data-melt-slider-thumb]`

</details>

<details>
<summary> <b>Switch</b> </summary>

- root ➡️ switch - `[data-melt-switch]`
- input - `[data-melt-switch-input]`

</details>

<details>
<summary> <b>Tabs</b> </summary>

- root ➡️ tabs - `[data-melt-tabs]`
- list - `[data-melt-tabs-list]`
- content - `[data-melt-tabs-content]`
- trigger - `[data-melt-tabs-trigger]`

</details>

<details>
<summary> <b>Tags Input</b> </summary>

Not sure about this one, so many tags/input variations, so some feedback is appreciated here, but here's a rough shot:

- root ➡️ tagsInput - `[data-melt-tags]`
- tag - `[data-melt-tags-tag]`
- input - `[data-melt-tags-input]`
- deleteTrigger - `[data-melt-tags-delete-trigger]`

</details>

<details>
<summary> <b>Toggle</b> </summary>

- root ➡️ toggle - `[data-melt-toggle]`

</details>

<details>
<summary> <b>Toggle Group</b> </summary>

- root ➡️ toggleGroup - `[data-melt-toggle-group]`
- item ➡️ toggleItem - `[data-melt-toggle-item]`

</details>

<details>
<summary> <b>Toolbar</b> </summary>

- root ➡️ toolbar - `[data-melt-toolbar]`
- button - `[data-melt-toolbar-button]`
- link - `[data-melt-toolbar-link]`
- separator - `[data-melt-toolbar-separator]`
- group - `[data-melt-toolbar-group]`
- item ➡️ groupItem - `[data-melt-toolbar-group-item]`

</details>

<details>
<summary> <b>Tooltip</b> </summary>

- trigger - `[data-melt-tooltip-trigger]`
- content - `[data-melt-tooltip-content]`
- arrow - `[data-melt-tooltip-arrow]`

</details>

**Comment by TGlide** [comment]
@huntabyte this is awesome! I agree. I don't think you need to worry about creating a PR, since I'm working on the builder wrapper mentioned on #100, where the data-attribute is given by the name. it currently uses data-melt-part, but that's easily changeable.

**Comment by geerew** [comment]
Thank you for this comment @huntabyte. As a contributor to this project I love seeing discussion around improving the standard as we drive to have more and more builders

**Comment by TGlide** [comment]
This was resolved!
