### ISSUE TITLE
🌟Feature request: declare explicitly which node versions are supported

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#925]
**Is your feature request related to a problem? Please describe.**
While helping out with upgrading deps, I realized that it is unclear to me which minimum supported node version melt-ui wants to keep compatibility with.

**Describe the solution you'd like**
Define minimum required node version and test against them in all PRs.

Looking at other OSS projects, most of them support node 18 (last LTS) and node 20 (current LTS) as of writing this. 

**Additional context**
If unclear, the way you would define it is like this in `package.json`:

```json
  "engines": {
    "node": ">=18.0.0",
    "pnpm": "^8.14.1" // Not relevant for consumers of the lib, but for contributors
  },
```

**Comment by TGlide** [comment]
I think this makes more sense for frameworks than libraries. I haven't seen this present in big libs (radix, chakra, etc) either, so I assume this is not an issue.
