### ISSUE TITLE
🌟Feature request: Close Dialog on trigger click

### ISSUE THREAD

**Issue by fromaline** [melt-ui/melt-ui#926]
Hi! Thanks for the project, it's awesome!

**Is your feature request related to a problem? Please describe.**
I'm reworking all dialog-like elements in my app to the melt-ui `createDialog` builder. Things work great except for a mobile menu. It's opened/closed by a conventional hamburger button, but the `createDialog` API doesn't allow me to implement this.

**Describe the solution you'd like**
I'd like to have a `toggleOnTrigger`/`closeOnTrigger` boolean prop in the `createDialog` API. If it's `false` the trigger element only opens a dialog, if it's `true` it toggles a dialog back and forth.

**Describe alternatives you've considered**
I can't think of any alternative solutions. The prop seems like an easy-to-use and intuitive solution to me.

**Additional context**
One button to toggle a dialog-like element is a common UI pattern, so it's worth implementing imo.

**Comment by TGlide** [comment]
Thanks for the kind words!

You can add an `on:m-click` and disable the default behaviour.
```html
<script>
const {elements: {trigger}, states: {open}} = createDialog();
</script>
<button use:melt={$trigger} on:m-click={(e) => e.preventDefault(); open.update(prev => !prev)} />
```

But tbh your use case does not fit a dialog, I'd say. You shouldn't be interacting with elements outside of a dialog once its open. 

Will be closing since this is solvable currently, and a prop wouldn't be fitting in this case I'd say!

**Comment by fromaline** [comment]
@TGlide, got your point, thanks! It's all clear now.

Btw, what should I use for this use case to align well with melt-ui high accessibility standards?

**Comment by fromaline** [comment]
@TGlide, sorry to bother you again. The solution you proposed doesn't seem to work. Here's a minimal reproducible example on StackBlitz: https://stackblitz.com/edit/vitejs-vite-cqyaes?file=src%2FApp.svelte

**Comment by TGlide** [comment]
> @TGlide, got your point, thanks! It's all clear now.
> 
> Btw, what should I use for this use case to align well with melt-ui high accessibility standards?

If you want a traditional hamburguer menu, you don't need much in terms of accessibility. Check out https://www.accede-web.com/en/guidelines/rich-interface-components/hamburger-menu/

**Comment by fromaline** [comment]
@TGlide, it works now! Thanks again for your help.
