### ISSUE TITLE
I can still get the error: The `use:melt` action cannot be used without MeltUI's Preprocessor.

### ISSUE THREAD

**Issue by EquinoxFlowerJG** [melt-ui/melt-ui#930]
### Describe the bug

I followed the installation section of the official documentation step by step, but I still encountered this error. Although it looks like to be solved on issue #616 . What should I do about it?

Versions:
vite: 5.0.8,
svelte: 4.2.8,
@sveltejs/vite-plugin-svelte: 3.0.1,
@melt-ui/svelte: 0.70.0,
@melt-ui/pp: 0.3.0.

This is the code in my svelte.config.js file:
```js
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import { preprocessMeltUI, sequence } from "@melt-ui/pp";

const config = {
    // ... other svelte config options
    preprocess: sequence([
        vitePreprocess(),
        // ... other preprocessors
        preprocessMeltUI(), // add to the end!
    ]),
};

export default config;
````

### Reproduction

this is my github repository site: https://github.com/EquinoxFlowerJG/svelte_melt_ui.git, it can show you the error.

### System Info

```bash
System: MacOS Sonoma 14.2.1
CPU: Intel Core i7
Node.js: v20.10.0
Browser: Google Chrome 119.0.6045.199
```

### Severity

blocking all usage of Melt UI

**Comment by TGlide** [comment]
Checked the reproduction and it also happens with me. @AdrianGonz97 any ideas?

**Comment by TGlide** [comment]
@EquinoxFlowerJG for now you can use Melt without the preprocessor, if that helps.

**Comment by AdrianGonz97** [comment]
Hi @EquinoxFlowerJG. I took a look at the repro and it looks like you're overriding the preprocess field of your Svelte config in your Vite config:
https://github.com/EquinoxFlowerJG/svelte_melt_ui/blob/39fb5d714f008d43a4cf5ebc31eede2bd5c4b70d/vite.config.ts#L18

Simply remove the argument from the Vite plugin like so:
```diff
// vite.config.ts
export default defineConfig({
	// ...
-	plugins: [svelte({ preprocess: sveltePreprocess() }), UnoCSS()],
+	plugins: [svelte(), UnoCSS()],
	// ...
});
```

**Comment by EquinoxFlowerJG** [comment]
> Hi @EquinoxFlowerJG. I took a look at the repro and it looks like you're overriding the `preprocess` field of your Svelte config in your Vite config: https://github.com/EquinoxFlowerJG/svelte_melt_ui/blob/39fb5d714f008d43a4cf5ebc31eede2bd5c4b70d/vite.config.ts#L18
> 
> Simply remove the argument from the Vite plugin like so:
> 
> ```diff
> // vite.config.ts
> export default defineConfig({
> 	// ...
> -	plugins: [svelte({ preprocess: sveltePreprocess() }), UnoCSS()],
> +	plugins: [svelte(), UnoCSS()],
> 	// ...
> });
> ```

Thank you very much for helping me solve the problem, buddy. 👍🏻o(￣▽￣)ｄ
