### ISSUE TITLE
Calendars onValueChange arguments have the wrong type

### ISSUE THREAD

**Issue by macmillen** [melt-ui/melt-ui#934]
### Describe the bug

I want to retrieve the ISO date of the calendar when clicking on a date. To do that I am using onValueChange which is supposed to have this type:
``` ts
onValueChange?: ChangeFn<ZonedDateTime | undefined> | undefined
```

The param that I'm trying to access is `next` which is of type `ZonedDateTime | undefined` which is supposed to have a `toAbsoluteString` method.
``` ts
onValueChange: ({ next }) => {
  if (next) {
    console.log(next);
    $form.date = next.toAbsoluteString();
  }
  return next;
}
```

But it fails:

![Screenshot_20240126_165739](https://github.com/melt-ui/melt-ui/assets/33156526/b8562a8f-06d1-4bc7-a1fc-c3181876d964)

### Reproduction

https://www.sveltelab.dev/ni9nta8oahbarke

### System Info

```bash
System:
    OS: Linux 6.1 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 13.41 GB / 31.02 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.volta/tools/image/node/18.19.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.2.3 - ~/.volta/tools/image/node/18.19.0/bin/npm
    pnpm: 7.16.1 - ~/.volta/bin/pnpm
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.85
    Chromium: 120.0.6099.224
  npmPackages:
    @melt-ui/svelte: ^0.70.0 => 0.70.0 
    @sveltejs/kit: 1.27.4 => 1.27.4 
    svelte: 4.2.2 => 4.2.2
```

### Severity

blocking all usage of Melt UI

**Comment by huntabyte** [comment]
Just specifying the `ZonedDateTime` as the generic to the prop won't update the runtime instance.

To do so, you need to pass a `defaultPlaceholder` in the format you'd like the dates to be in:

https://www.sveltelab.dev/es04mu0fw1d24ba?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte

I used the helpers `now()` and `getLocalTimeZone()` here but you could pass whatever `ZonedDateTime` you wanted. This is what the calendar will open with by default if no value is present.

**Comment by macmillen** [comment]
Thanks for the help. But to me it's still a bug because the value has a wrong type that results in a runtime error. I think the type should rather be `unknown`, `any` or some union.

**Comment by TGlide** [comment]
> Thanks for the help. But to me it's still a bug because the value has a wrong type that results in a runtime error. I think the type should rather be `unknown`, `any` or some union.

It's not a wrong type, you typed `CreateCalendarProps<false, DateValue, ZonedDateTime>`, and so that's why `onChange` has that type. By default, that is not the type we create.

**Comment by macmillen** [comment]
your'e totally right, thanks for the help!!
