### ISSUE TITLE
🌟Feature request: Listbox

### ISSUE THREAD

**Issue by danbulant** [melt-ui/melt-ui#936]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a command palette of sorts, and thought that melt could help with that. The closest thing to it is using a dialog with combobox, but combobox wants to position itself and wants to be triggered on/off - I'd like it to be part of the dialog always and not have to fight with it trying to position itself or hide.

**Describe the solution you'd like**
To me it seems like the already implemented listbox may solve parts of it, but for some reason is not exposed as a public API - even though it's not in the internal folder.
I'd like to have a way to couple input with a list of elements in a way that the combobox already does, but just without position or hiding, instead simply living next to the input element as it is.

**Describe alternatives you've considered**
Fighting with combobox or implementing it myself completely.

**Additional context**
![Example screenshot](https://github.com/melt-ui/melt-ui/assets/30036876/192eb305-9b63-448a-b293-fe1e8fa99d8d)

**Comment by TGlide** [comment]
You can achieve this with combobox today.

```ts
createCombobox({
  positioning: false,
  portal: null,
  forceVisible: true
})
```

**Comment by danbulant** [comment]
Thanks.

`positioning` doiesn't have `false` as a valid value in it's typedefs and I didn't see it mentioned in the docs.  
Furthermore, even if I set those three properties, the menu element will get `hidden` and `display: none`, even if I try to manually set the open store of the combobox to `true`.

[example in sveltelab](https://www.sveltelab.dev/2u31lzdor98as7y)

**Comment by TGlide** [comment]
My bad, I meant `positioning: null`. You also need the input for combobox to work. 

[Here you go, working example](https://stackblitz.com/edit/vitejs-vite-ghdbua?file=src%2FApp.svelte%2Cpackage.json&terminal=dev)

**Comment by danbulant** [comment]
Maybe just a FYI or info for someone who finds this:

For combobox to work, it needs to be used directly after creation. This means that the combobox elements (didn't test which one exactly, or if all of them) cannot be in an `if` block or similar. I tried using it in a dialog and it seems this was the actual reason it wasn't working.

Puttint it in a separate component that gets recreated instead works as expected.
