### ISSUE TITLE
Keyboard down does not work on select 

### ISSUE THREAD

**Issue by alexbjorlig** [melt-ui/melt-ui#950]
### Describe the bug

I expect keyboard down arrow, to navigate down in select

### Reproduction

https://github.com/melt-ui/melt-ui/assets/9967422/0f468291-ef9f-463e-936a-28c6009121c1

(my first time using sveltelab.dev, it seems a bit unstable), but the link is here:

https://www.sveltelab.dev/jwy0u5g3fenls2m?t=melt_ui&files=.%2Fsrc%2Froutes%2F%2Bpage.svelte%2C.%2Fpackage.json%2C.%2Fsrc%2Flib%2FCollapsible.svelte%2C.%2Fsrc%2Flib%2Findex.js%2C.%2Fsrc%2Froutes%2F%2Bpage.server.js

### System Info

```bash
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.61 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 10.2.5 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.12.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
  npmPackages:
    @melt-ui/svelte: ^0.71.1 => 0.71.1 
    @sveltejs/kit: ^2.4.1 => 2.4.3 
    svelte: ^4.2.2 => 4.2.8
```

### Severity

annoyance

**Comment by huntabyte** [comment]
![CleanShot 2024-02-02 at 15 23 27@2x](https://github.com/melt-ui/melt-ui/assets/64506580/a7bb9b32-cfb4-4945-bc4f-1f8cff771a75)

This is an issue with your styling. You're using tailwind classes without tailwind installed. The functionality still works. You can use the `[data-highlighted]` selector to style the highlighted items accordingly.
