### ISSUE TITLE
🐛 Bug: Unexpected Menu behaviors

### ISSUE THREAD

**Issue by vultix** [melt-ui/melt-ui#959]
The melt-ui context menu currently has a few different behaviors from the default browser context menu:
- Pointer events (hover, mousedown, click, etc) still register for elements outside of the context menu
- Clicking outside of the context menu both closes the menu and registers the click event to the clicked element
- Pressing tab closes the menu

These differences make the melt context menu feel unintuitive in our application.  It'd be great if we had options to configure these behaviors to feel closer to the native context menu.  Potentially a  `modal: boolean` would be good enough?

**Comment by huntabyte** [comment]
We should be able to apply similar logic to the menus as we did with #883 to the menus as well to get this behavior more consistent with the expected.

**Comment by huntabyte** [comment]
I reclassified this as a bug, because click events _shouldn't_ be passing through

**Comment by TGlide** [comment]
> Pointer events (hover, mousedown, click, etc) still register for elements outside of the context menu

This does happen in chrome and ff though 🤔

**Comment by huntabyte** [comment]
2/3 of these will be addressed by #1035.

As far as tab closing the menu, you can prevent this behavior using the `m-keydown` event on the `menu`.

**Comment by TGlide** [comment]
However I do like the `modal` option.
