### ISSUE TITLE
[Dialog] Scroll does not get disabled when trigger is inside of a dropdown

### ISSUE THREAD

**Issue by xiBread** [melt-ui/melt-ui#969]
### Describe the bug

I'm working on a website with a similar layout to this image:

![Untitled-2024-02-07-1856(1)](https://github.com/melt-ui/melt-ui/assets/60681223/84bd03d3-463b-4da1-ae85-2c81afc0c48e)

Where `Account` (1) is a dropdown containing a button, `Notifications` (2), that triggers a controlled store for the `Notifications` dialog (which is styled as a drawer) (3). The issue is that the scroll does not get disabled if there's overflowing content. However, it does get disabled if the trigger to change the store is outside of the dropdown. The two buttons in the header of the playground display this behavior.

As a workaround, I've added

```css
body:has([data-portal]:not(:empty):not(.scroll)) {
	overflow: hidden;
}
```

to my global `.css` file.

### Reproduction

https://stackblitz.com/edit/github-zi9mk9?file=src%2Flib%2Fcomponents%2FHeader.svelte

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 176.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.15.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
Browsers:
    Chrome: 121.0.6167.139
    Edge: 121.0.2277.106
    Safari: 17.2.1
npmPackages:
    @melt-ui/svelte: ^0.72.0 => 0.72.0 
    @sveltejs/kit: ^2.5.0 => 2.5.0 
    svelte: ^4.2.10 => 4.2.10
```

### Severity

annoyance

**Comment by huntabyte** [comment]
You're running into a race condition here, which when you think about it, it makes sense why this happens without you having to add a little bit on your end to make it work as expected.

You click on the item, which by default tells the menu to close, but not until the click handlers have finished executing. Inside the click handler you're opening another "prevent scroll" component, and _then_ the menu closes, which restores the scroll.

**Comment by huntabyte** [comment]
Here's an example of how you can accomplish what you're looking for.

https://stackblitz.com/edit/github-zi9mk9-m3wja8?file=src%2Flib%2Fcomponents%2FHeader.svelte

**Comment by xiBread** [comment]
Ah, thank you! I figured it had something to do with the fact that the menu was being closed but I couldn't wrap my head around it 😅
