### ISSUE TITLE
Rendering days of month changes to default calendar after selecting a day from calendar

### ISSUE THREAD

**Issue by B-Esmaili** [melt-ui/melt-ui#985]
### Describe the bug

I setup the date-picker with `persian-calendar`  and `fa-IR` locale. In First render it works as expected , but when i select a day (which is in other gregorian month than current month) it renders the days based on gregorian calendar (not persian clendar). To reproduce the issue just use following code and click over day 1.

### Reproduction

[https://stackblitz.com/edit/github-tsc74y?file=src%2Flib%2Fcomponents%2FAccordion.svelte](https://stackblitz.com/edit/github-tsc74y?file=src%2Flib%2Fcomponents%2FAccordion.svelte)

### Severity

annoyance

**Comment by B-Esmaili** [comment]
> Please provide a [reproduction](https://melt-ui.com/repro).
> 
> More info

I updated the post with link for playground.

**Comment by huntabyte** [comment]
Thank you for taking the time to do that! We'll look into it!

**Comment by B-Esmaili** [comment]
I investigated the issue , apparently the problem is the fact that [parseStringToDateValue](https://github.com/melt-ui/melt-ui/blob/c5cf4aa07222e574a14598960be239000426b383/src/lib/internal/helpers/date/utils.ts#L70C17-L70C39) function does not take into account the `Calendar` specified by default `DateValue`. The revamped version of this function could be something like following :

``` typescript
export function parseStringToDateValue(dateStr: string, referenceVal: DateValue): DateValue {
	let dateValue: DateValue;
	if (referenceVal instanceof ZonedDateTime) {
		dateValue = parseZonedDateTime(dateStr);
	} else if (referenceVal instanceof CalendarDateTime) {
		dateValue = parseDateTime(dateStr);
	} else {
		dateValue = parseDate(dateStr);
	}
	
	return toCalendar(dateValue, referenceVal.calendar);	 
}
```
This is my speculation , maybe i am wrong but this is based on my understanding of the code. I hope this would be a help for you to further investigate the issue.

**Comment by B-Esmaili** [comment]
Yes definitely i'll submit a PR in my next free time.
