### ISSUE TITLE
🔍 Radix feature parity tracking

### ISSUE THREAD

**Issue by NikiSkaarup** [melt-ui/melt-ui#99]
Remaining primitives until feature parity

todo:

- [ ] Form
- [ ] Navigation Menu
- [ ] Scroll Area

**Comment by TGlide** [comment]
Thank you for this! TBH I feel we can skip Aspect Ratio, since `aspect-ratio` has really nice browser support.

**Comment by TGlide** [comment]
I'm going to close this issue and create separate ones!
